### ISSUE TITLE
Salt-cloud not working in 2014.7.6

### ISSUE THREAD

**Issue by jtand** [saltstack/salt#24915]
When using salt-cloud in 2014.7.6 I get a traceback when trying to provision a vm. This works on 2014.7.1-2014.7.5 and 2015.2 +. I've noticed this issue on CentOS 7 with both Linode and RackSpace drivers. 

```bash
salt-cloud -p linode_cent7 test-cent7 -l debug

-----snip-----

[ERROR   ] There was a profile error: 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 231, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1318, in run_profile
    vm_ = main_cloud_config.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

Versions Report:
```bash
# salt --versions-report
           Salt: 2014.7.6
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

**Comment by jtand** [comment]
ping @techhat

**Comment by rallytime** [comment]
@jtand Did this fix work for you? Can this one be closed?

**Comment by jtand** [comment]
@rallytime yep.
