### ISSUE TITLE
[BUG] winrepo broken in 3001 with gitpython

### ISSUE THREAD

**Issue by wb529kq** [saltstack/salt#57801]
**Description**
running salt-run winrepo.update_git_repos fails

**Setup**
salt-run winrepo.update_git_repos on CentOS 7 with GitPython 3.1.3

**Steps to Reproduce the behavior**
run the command again .. 

**Expected behavior**
winrepo's are cloned

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.3
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Additional context**
could it be caused by https://github.com/saltstack/salt/pull/56647 ?

**Comment by oeuftete** [comment]
```text
# salt-run winrepo.update_git_repos
Failed to update winrepo_remotes: 'GitPython' object has no attribute 'fallback'
```

master log:

```text
2020-06-25 18:30:26,186 [salt.loaded.int.runners.winrepo:236 ][ERROR   ][2160] Failed to update winrepo_remotes: 'GitPython' object has no attribute 'fallback'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/runners/winrepo.py", line 233, in update_git_repos
    winrepo.checkout()
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 3367, in checkout
    cachedir = self.do_checkout(repo)
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 2796, in do_checkout
    return repo.checkout()
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1216, in checkout
    if self.fallback:
AttributeError: 'GitPython' object has no attribute 'fallback'
```

**Comment by oeuftete** [comment]
It looks like the following diff would be a workaround that would still allow any `fallback` option to be used, but it does appear there's a missing piece somewhere in the implementation of #56647 that prevents the `winrepo.update_git_repos` runner from working.  I couldn't immediately sort out the right place to add `fallback` in the global/per_remote fields, if that is where it needs to be changed.

@sathieu @bdrung As author and porter, respectively, of #56647, any ideas here on the right fix?

```diff
diff --git a/salt/utils/gitfs.py b/salt/utils/gitfs.py
index edb396f7f2..5d8a546352 100644
--- a/salt/utils/gitfs.py
+++ b/salt/utils/gitfs.py
@@ -233,6 +233,7 @@ class GitProvider(object):
     ):
         self.opts = opts
         self.role = role
+        self.fallback = None
         self.global_saltenv = salt.utils.data.repack_dictlist(
             self.opts.get("{0}_saltenv".format(self.role), []),
             strict=True,
```

**Comment by sathieu** [comment]
@oeuftete I think the correct patch would be:
```diff
diff --git a/salt/config/__init__.py b/salt/config/__init__.py
index 0b7cd0a9a3..3f2e4f2523 100644
--- a/salt/config/__init__.py
+++ b/salt/config/__init__.py
@@ -1178,6 +1178,7 @@ DEFAULT_MINION_OPTS = immutabletypes.freeze(
         "winrepo_remotes": ["https://github.com/saltstack/salt-winrepo.git"],
         "winrepo_remotes_ng": ["https://github.com/saltstack/salt-winrepo-ng.git"],
         "winrepo_branch": "master",
+        "winrepo_fallback": "",
         "winrepo_ssl_verify": True,
         "winrepo_user": "",
         "winrepo_password": "",
@@ -1498,6 +1499,7 @@ DEFAULT_MASTER_OPTS = immutabletypes.freeze(
         "winrepo_remotes": ["https://github.com/saltstack/salt-winrepo.git"],
         "winrepo_remotes_ng": ["https://github.com/saltstack/salt-winrepo-ng.git"],
         "winrepo_branch": "master",
+        "winrepo_fallback": "",
         "winrepo_ssl_verify": True,
         "winrepo_user": "",
         "winrepo_password": "",
```

Note: I won't be able to provide a PR before tuesday.

**Comment by xeacott** [comment]
@terminalmage does this look like a decent patch?

**Comment by terminalmage** [comment]
[This patch](https://github.com/saltstack/salt/issues/57801#issuecomment-649841676) is partially correct. It looks like `fallback` would also need to be added to the `PER_REMOTE_OVERRIDES` tuple in `salt/runners/winrepo.py`.

**Comment by twangboy** [comment]
What is fallback supposed to do, exactly? Do I need to document this setting in the master/minion config docs?
