### PR TITLE
fix(modules/aptpkg): fix recent regressions introduced in salt.modules.aptpkg

### LINKED ISSUE #62175: [BUG] Recent regression in `aptpkg`: Failed to configure repo ...': 'str' object has no attribute 'name'
**Description**

CC: @Ch3LL.

This is the first of two regressions encountered during the Formulas' weekly testing this week (`2022-W24`).

Using git bisect, I've traced it down to this commit: 409072c4314ec8f45c3c7323308b7a57b20d1f6a (#61760).

A specific example of a failure:

```sls
node-package-repo-pkgrepo-managed:
  pkgrepo.managed:
    - comps: main
    - dist: buster
    - file: /etc/apt/sources.list.d/nodesource.list
    - humanname: NodeSource Node.js Repository
    - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - keyserver: keyserver.ubuntu.com
    - name: deb https://deb.nodesource.com/node_16.x buster
    - url: https://deb.nodesource.com/
    - onlyif: True

...


      ID: node-package-repo-pkgrepo-managed
Function: pkgrepo.managed
    Name: deb https://deb.nodesource.com/node_16.x buster
  Result: False
 Comment: Failed to configure repo 'deb https://deb.nodesource.com/node_16.x buster': 'str' object has no attribute 'name'
```

Detailed logs can be checked from the following:

* https://gitlab.com/myii/apt-formula/-/jobs/2592332938#L1052
* https://gitlab.com/myii/carbon-relay-ng-formula/-/jobs/2592312962#L3117
* https://gitlab.com/myii/grafana-formula/-/jobs/2592324572#L1517
* https://gitlab.com/myii/lynis-formula/-/jobs/2592327062#L2685
* https://gitlab.com/myii/node-formula/-/jobs/2592330826#L1365
* https://gitlab.com/myii/openvpn-formula/-/jobs/2592333965#L4415
* https://gitlab.com/myii/php-formula/-/jobs/2592338375#L3219
* https://gitlab.com/myii/rabbitmq-formula/-/jobs/2592335615#L10220
* https://gitlab.com/myii/rspamd-formula/-/jobs/2592337850#L1916
* https://gitlab.com/myii/varnish-formula/-/jobs/2592349324#L1354

**Setup**
Kitchen CI for each of the formula repos above.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run Kitchen testing for any of the formulas mentioned above.

**Expected behavior**
The `pkgrepo.managed` state shouldn't fail.

**Versions Report**
A current `master` branch installation of Salt (8253b6cef00aaa97db0dac1d46b212c1bf220df9).

**Additional context**
I have a fix that I will propose here shortly.  I've rebuilt our `master` images with it and all jobs are passing again:

* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W24b

### LINKED ISSUE #62176: [BUG] Recent regression in `aptpkg`: Traceback: KeyError: 'index'
**Description**

CC: @Ch3LL.

This is the second of two regressions encountered during the Formulas' weekly testing this week (`2022-W24`).

Using interactive debugging, I've traced it down to this commit: b42487f5c01c630bb692715cfc93db0c5c143e0f (#61760).

There was just the one formula repo where this failed.

https://gitlab.com/myii/postgres-formula/-/jobs/2592354250#L4440:

```sls
postgresql-repo:
  pkgrepo.managed:
    - file: "/etc/apt/sources.list.d/pgdg.list"
    - humanname: "PostgreSQL Official Repository"
    - name: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt buster-pgdg main"

...

      ID: postgresql-repo
Function: pkgrepo.managed
    Name: deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt buster-pgdg main
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
     File "/usr/local/lib/python3.7/dist-packages/salt/state.py", line 2277, in call
       *cdata["args"], **cdata["kwargs"]
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 149, in __call__
       return self.loader.run(run_func, *args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 1201, in run
       return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
       return _func_or_method(*args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
       return f(*args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/states/pkgrepo.py", line 487, in managed
       sanitizedkwargs = __salt__["pkg.expand_repo_def"](repo=repo, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 149, in __call__
       return self.loader.run(run_func, *args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 1201, in run
       return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
       return _func_or_method(*args, **kwargs)
     File "/usr/local/lib/python3.7/dist-packages/salt/modules/aptpkg.py", line 3002, in expand_repo_def
       idx = repo_opts[opt]["index"]
   KeyError: 'index'
```

Notice that `signed-by` is the only option given:

```console
deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt buster-pgdg main
```

**Setup**
Kitchen CI for the `postgres-formula`.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run Kitchen testing for the formula mentioned above.

**Expected behavior**
The `pkgrepo.managed` state shouldn't fail.

**Versions Report**
A current `master` branch installation of Salt (8253b6cef00aaa97db0dac1d46b212c1bf220df9).

**Additional context**
I have a fix that I will propose here shortly.  I've rebuilt our `master` images with it and the jobs are passing again:

* https://gitlab.com/myii/postgres-formula/-/pipelines/565205991

### PR DESCRIPTION
**Pull request by myii**
### What does this PR do?
Resolve recent regressions in `salt.modules.aptpkg`, encountered when using the `pkgrepo.managed` state.

CC: @Ch3LL.

### What issues does this PR fix or reference?

* Fixes #62175
* Fixes #62176

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

File: salt/modules/aptpkg.py [hunk 1]
```diff
@@ -1686,7 +1686,10 @@ def _get_opts(line):
     Return all opts in [] for a repo line
     """
     get_opts = re.search(r"\[.*\]", line)
-    ret = {"arch": {"full": "", "value": ""}, "signedby": {"full": "", "value": ""}}
+    ret = {
+        "arch": {"full": "", "value": "", "index": 0},
+        "signedby": {"full": "", "value": "", "index": 0},
```
Comment (myii) [inline salt/modules/aptpkg.py:1691]: As mentioned in #62176, this entry is only using `signed-by`:

```console
deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] http://apt.postgresql.org/pub/repos/apt buster-pgdg main
```

Which hits a traceback on the last line here:

https://github.com/saltstack/salt/blob/8253b6cef00aaa97db0dac1d46b212c1bf220df9/salt/modules/aptpkg.py#L2999-L3002

In `_get_opts`, there's no guarantee that an `index` will be set for each by this block (e.g. when only the `arch` or the `signed-by` option is provided in the entry, as shown above):

https://github.com/saltstack/salt/blob/8253b6cef00aaa97db0dac1d46b212c1bf220df9/salt/modules/aptpkg.py#L1696-L1704

So a default `index` is provided for each.

**Comment by Ch3LL** [comment]
re-run full all

**Comment by Ch3LL** [comment]
re-run full all

**Review by MKLeb — APPROVED** [review]
