### ISSUE TITLE
[2016.11.1] Salt-cloud Throwing Query Error - NoneType object has no attribute __getitem__

### ISSUE THREAD

**Issue by bibana-cogint** [saltstack/salt#38274]
### Description of Issue/Question
When attempting to spin up any number of EC2 instances with salt-cloud, the following error is being thrown:

`[Error  ] There was a query error: 'NoneType' object has no attribute '__getitem__'`

The same provider/profile/map files work fine using 2016.3.4

### Setup

See attachments for profiles/providers/map 
[cloud_details.zip](https://github.com/saltstack/salt/files/655101/cloud_details.zip)

Place cloud.profiles into /etc/salt/cloud.profiles.d
Place cloud.providers into /etc/salt/cloud.providers.d
Place cloud.map anywhere on filesystem

### Steps to Reproduce Issue
Command:
sudo salt-cloud --map /path/to/map/cloud.map -y

Below is the result from salt-cloud command:
![salt-cloud-error](https://cloud.githubusercontent.com/assets/24590693/21231138/29c89f04-c2b5-11e6-88a6-9488b29ac31a.PNG)

I noticed that when this line:

`if 'Ebs.VolumeType' not in ex_blockdevicemappings[dev_index]:`

in salt/cloud/clouds/ec2.py (line 1891) was changed to this:

`if rd_type is not None:`

Everything worked as intended.  The latter code snippet is from 2016.3.4.  

### Versions Report

Below is the versions report on master:
![salt-versions-report](https://cloud.githubusercontent.com/assets/24590693/21231319/d27a8478-c2b5-11e6-9f98-7afd74fcc122.PNG)

Minions running 2016.11.1

**Comment by Ch3LL** [comment]
@bibana-cogint this was fixed here: https://github.com/saltstack/salt/pull/37967

But looks like it was never backported to 2016.11 branch. Let me see about getting this backported.

**Comment by Ch3LL** [comment]
@bibana-cogint looks like it was backported. Can you give that a try and then we will close this issue. Tahnks

**Comment by bibana-cogint** [comment]
Megan,

Appears to be working again.  Thanks!


[cid:image001.jpg@01D2196C.C4235D20]
Bryant Ibana | Senior DevOps
cogint (NASDAQ: COGT)
2650 N. Miltary Trail, Suite 300
Boca Raton, FL 33431
561-757-4064 Direct
bibana@cogint.com<mailto:bibana@cogint.com>
www.cogint.com<http://www.ididata.com/>

**Comment by Ch3LL** [comment]
Great thanks for getting back to me :)
