### ISSUE TITLE
Beacon configuration doesn't work as a list

### ISSUE THREAD

**Issue by Da-Juan** [saltstack/salt#38121]
### Description of Issue/Question

When configuring beacons as mentioned in the documentation I get a DeprecationWarning.
If I try to configure the beacon as a list I get a KeyError.

What is the good way to configure beacons?

### Setup
The following config gets a DeprecationWarning:
```
beacons:
  status:
    time:
      - all
    interval: 10
```

`2016-12-07 10:07:11,482 [py.warnings      ][WARNING ][28888] /usr/lib/python2.7/dist-packages/salt/beacons/__init__.py:56: DeprecationWarning: Beacon configuration should be a list instead of a dictionary.`

And this config gets the KeyError:
```
beacons:
  status:
    - time:
      - all
    - interval: 10
```

```
2016-12-07 10:33:33,391 [salt.minion      ][CRITICAL][22470] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2153, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 409, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 103, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/status.py", line 121, in beacon
    data = __salt__['status.{0}'.format(func)]()
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1086, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: "status.{'time': ['all']}"
```

### Steps to Reproduce Issue
Configure the beacons on a minion as above.

### Versions Report
This version report comes from Raspbian but I get the same errors on Debian/AMD64.
```
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 17 2016, 20:26:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.0 
        machine: armv7l
        release: 4.4.34-v7+
         system: Linux
        version: debian 8.0 
```

**Comment by Ch3LL** [comment]
@Da-Juan i tried a couple of other beacons and am seeing the same behavior.

It looks like this warning message was added here: https://github.com/saltstack/salt/pull/29027

Looks like the deprecation path is for nitrogen so we definitely need to get this fixed before the release to make sure all the beacons work with a list format. Thanks for the heads up on this one.

**Comment by sean-bennett112** [comment]
Is there any update on this? Was just going through the documentation on beacons as well and ran into this. Tried a few different modifications to no avail. Is there a correct syntax that will currently work, or are beacons currently not working on Salt 2016.11.x?

**Comment by fyb3r** [comment]
I have the same issue as sean-bennet112. Running 2016.11.1 and the beacons still give out this error.

Also the documentation for beacons has not been updated to show that configs need to be in list format.

**Comment by andrewlarioza** [comment]
Are there any update with this issue? I'm also having the same problem with Beacon.

**Comment by shaidar** [comment]
Any updates on this as we're running into the same issue as well on 2016.11.3 (Carbon). Tried formatting the beacon as a dict and as a list and get the same error reported when it's a dict and the following error when it's a list:
`AttributeError: 'list' object has no attribute 'get'`

**Comment by Ch3LL** [comment]
My understanding is this issue outlines not being able to configure a beacon as a list, but it works as a dictionary but spits out a deprecation warning.  If there is a beacon thats not actually working please open a seperate issue on this, we definitely want to get those fixed up sooner.

In terms of an update on this issue, this will be assigned out to an engineer and timeline wise the plan is to fix before nitrogen release.

**Comment by cachedout** [comment]
Fix has been merged.
