### ISSUE TITLE
Any/All Salt-SSH invocations in 2016.3.0 Fails with AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'

### ISSUE THREAD

**Issue by msummers42** [saltstack/salt#33709]
CC @basepi as this is a total road block with salt-ssh on 2016.3.0. We cannot run anything.
### Description of Issue/Question

Any call to salt-ssh fails with `AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'`
### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The gist here is that we use a SaltFile and relative paths in our master config. Do note none of our config or states seem relevant as far as I can tell. The code fails really early.
### Steps to Reproduce Issue

Run any salt-ssh invocation on any target.

```
$ salt-ssh -l debug myhost test.ping
Traceback (most recent call last):
  File "/home/user/venv/salt-dev/bin/salt-ssh", line 11, in <module>
    sys.exit(salt_ssh())
  File "/home/user/venv/salt-dev/lib/python2.7/site-packages/salt/scripts.py", line 385, in salt_ssh
    import salt.cli.ssh
  File "/home/user/venv/salt-dev/lib/python2.7/site-packages/salt/cli/ssh.py", line 5, in <module>
    import salt.client.ssh
  File "/home/user/venv/salt-dev/lib/python2.7/site-packages/salt/client/__init__.py", line 29, in <module>
    import salt.config
  File "/home/user/venv/salt-dev/lib/python2.7/site-packages/salt/config/__init__.py", line 37, in <module>
    import salt.syspaths
  File "/home/user/venv/salt-dev/lib/python2.7/site-packages/salt/syspaths.py", line 97, in <module>
    BASE_THORIUM_ROOTS_DIR = __generated_syspaths.BASE_THORIUM_ROOTS_DIR
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'
```
### Versions Report

Cannot get this due to the error, traceback same as above for `salt-ssh --versions-report`

salt-ssh = 2016.3.0
python = 2.7.10
Gentoo 

I am happy to provide any further information you may be interested in.

**Comment by Ch3LL** [comment]
@msummers42 I am not able to replicate this issue on 2016.3.0. Do you have any leftover pyc files by chance?  how did you install salt-ssh? Did you upgrade from a previous version?

**Comment by msummers42** [comment]
Hello @Ch3LL , thanks for your response. To answer your questions:
I deleted the PYC files.
I installed using pip in a virtualenv on python 2.7.10.
I upgraded from 2015.8.10.

I will try to repro with a fresh virtualenv, but I would expect this to work OK via a pip install -U.

**Comment by basepi** [comment]
Yes, I would expect it to work on upgrading as well. I'm guessing that setup.py doesn't generate that __generated_syspaths if it already exists, and so it breaks on upgrade since that BASE_THORIUM_ROOTS_DIR is new.

**Comment by basepi** [comment]
@Ch3LL I recommend installing 2015.8.10 from pip and then upgrading. I bet this is reproducible that way.

**Comment by cachedout** [comment]
I wonder if it would be worthwhile to add a `--clean` flag or something to salt-ssh that just logs in and deletes the thin tarball and exits. I'm guessing that `--wipe` wouldn't work in this instance since the remote end can't execute Salt.

**Comment by msummers42** [comment]
This is well prior the the thin tarball getting sent anywhere. It is immediately upon invocation, when the config settings are read (I believe).

**Comment by basepi** [comment]
Agreed -- I'm pretty certain these files are generated at setup.py install time, not tarball generation time.

**Comment by blaketmiller** [comment]
Just here to add another data point. I ran into the same issue with a similar upgrade process to @msummers42. Relevant snippet from the upgrade process:

```
...
Successfully built salt
Installing collected packages: salt
  Found existing installation: salt 2015.8.8.2
    Uninstalling salt-2015.8.8.2:
      Successfully uninstalled salt-2015.8.8.2
Successfully installed salt-2016.3.0
```
followed by:
```
myhost ~$ salt --versions
Traceback (most recent call last):
  File "/srv/users/gredapi/usr/bin/salt", line 11, in <module>
    sys.exit(salt_main())
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/scripts.py", line 462, in salt_main
    import salt.cli.salt
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 9, in <module>
    import salt.utils.job
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/utils/job.py", line 8, in <module>
    import salt.minion
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/minion.py", line 78, in <module>
    import salt.client
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 29, in <module>
    import salt.config
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 37, in <module>
    import salt.syspaths
  File "/srv/users/gredapi/usr/lib/python2.7/site-packages/salt/syspaths.py", line 97, in <module>
    BASE_THORIUM_ROOTS_DIR = __generated_syspaths.BASE_THORIUM_ROOTS_DIR
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'
```

**Comment by blaketmiller** [comment]
Looks like a quick fix would be to simply set the environment variable `GENERATE_SALT_SYSPATHS=1` before installing and setup.py should pick that up. 

Since Thorium is new in 2016.3, would it make the most since during install to simply append `BASE_THORIUM_ROOTS_DIR = None` to _syspaths.py?

**Comment by kevops** [comment]
Same issue after upgrading from 2015.5.3 to 2016.3.1.

c:\salt>salt-call state.highstate
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 221, in salt_call
    import salt.cli.call
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 6, in <module>
    from salt.utils import parsers
  File "c:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 28, in <modul
e>
    import salt.config as config
  File "c:\salt\bin\lib\site-packages\salt\config\__init__.py", line 866, in <mo
dule>
    'base': [salt.syspaths.BASE_THORIUM_ROOTS_DIR],
AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'

**Comment by mbarrien** [comment]
I ran into this myself. Even after completely uninstalling salt, there remained a lib/python2.7/site-packages/salt/_syspaths.py files that had a comment that it was autogenerated several months ago (in March, by an older version of Salt?), and contained lines like "CONFIG_DIR = None" (all the values being explicitly set to None. Blowing away the remaining file before reinstalling salt seemed to fix my problem, even though the file wasn't auto regenerated. (Note that this was .py file left behind, not .pyc.)
