### PR TITLE
Fixed ec2 cloud unit test.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
I've found these tests failures in PR #56565
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.8/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/tmp/kitchen/testing/tests/unit/cloud/clouds/test_ec2.py", line 90, in test_get_password_data
    ret = ec2.get_password_data(
  File "/tmp/kitchen/testing/salt/cloud/clouds/ec2.py", line 4970, in get_password_data
    key_obj = Crypto.PublicKey.RSA.importKey(rsa_key)
AttributeError: module 'Crypto' has no attribute 'PublicKey'
```
https://jenkinsci.saltstack.com/job/pr-ubuntu2004-py3/job/PR-56565/2/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data/
https://jenkinsci.saltstack.com/job/pr-fedora32-py3/job/PR-56565/2/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data/

I don't know why the test isn't failing in other builds but if I can easily reproduce it using python interpreter:
```
$ python
Python 3.7.7 (default, Apr 13 2020, 14:31:36) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
>>> Crypto.PublicKey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'Crypto' has no attribute 'PublicKey'
>>> Crypto.__version__
'3.9.7'
```

I've moved the crypto related logic to `salt.crypt` package. Also fixed the code to work with Cryptodome.

### What issues does this PR fix or reference?
Fixes test failures for #56565

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by xeacott — DISMISSED** [review]

**Review by cmcmarrow — DISMISSED** [review]

**Comment by cmcmarrow** [comment]
@DmitryKuzmenko Thanks for the PR.

**Review by Akm0d — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
Tests passed. @xeacott @cmcmarrow @Akm0d could you please re-review this?

**Review by Akm0d — APPROVED** [review]
