### ISSUE TITLE
Exception getting grains from non-script environment

### ISSUE THREAD

**Issue by jcsp** [saltstack/salt#11402]
In salt 2014.1, it is not possible to query local grains from a non-script execution environment, such as an interactive python interpreter, or a WSGI container.  This is because **main**.**file** is not set in these cases.  This used to work in salt 0.17.5.

```
>>> from salt.config import master_config
>>> c = master_config("/etc/salt/")
>>> from salt.loader import _create_loader
>>> l = _create_loader(c, 'grains', 'grain')
>>> funcs = l.gen_functions()
>>> for key in [k for k in funcs.keys() if k.startswith('core.')]:
...  ret = funcs[key]()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/pymodules/python2.7/salt/grains/core.py", line 784, in os_data
    elif salt.utils.is_linux():
  File "/usr/lib/pymodules/python2.7/salt/utils/decorators/__init__.py", line 192, in _memoize
    cache[args] = func(*args)
  File "/usr/lib/pymodules/python2.7/salt/utils/__init__.py", line 1174, in is_linux
    if 'salt-proxy-minion' in main.__file__:
AttributeError: 'module' object has no attribute '__file__'
```
