### ISSUE TITLE
[BUG] file.managed Resources Fail with Comment Unable to manage file: 'master_uri'

### ISSUE THREAD

**Issue by corey-hammerton** [saltstack/salt#60018]
**Description**
We are managing some files in a custom Formula but our Salt state.apply calls continuously fail with the following code output

```
Apr 13 17:17:33 <hostname> salt-minion[1195319]: [INFO    ] Running state [/our_script.sh] at time 17:17:33.614943
Apr 13 17:17:33 <hostname> salt-minion[1195319]: [INFO    ] Executing state file.managed for [/our_script.sh]
Apr 13 17:17:33 <hostname> salt-minion[1195319]: Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x7fc85c35ff70>
Apr 13 17:17:33 <hostname> salt-minion[1195319]: Traceback (most recent call last):
Apr 13 17:17:33 <hostname> salt-minion[1195319]:   File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 306, in __del__
Apr 13 17:17:33 <hostname> salt-minion[1195319]:     with self._refcount_lock:
Apr 13 17:17:33 <hostname> salt-minion[1195319]: AttributeError: 'AsyncZeroMQReqChannel' object has no attribute '_refcount_lock'
Apr 13 17:17:33 <hostname> salt-minion[1195319]: [ERROR   ] Unable to manage file: 'master_uri'
Apr 13 17:17:33 <hostname> salt-minion[1195319]: [INFO    ] Completed state [/our_script.sh] at time 17:17:33.634364 (duration_in_ms=19.421)
```

**Setup**
SLS in question
```
script.sh:
  file.managed:
    - name: /out_script.sh
    - source: salt://{{ tplroot }}/files/our_script.sh
    - mode: '0755'
    - makedirs: true
```

Salt Minion Config
```
"acceptance_wait_time": 10
"auth_safemode": true
"auth_timeout": 60
"grains":
  <redacted>
"id": "<hostname>"
"key_logfile": "/var/log/salt/key"
"log_file": "/var/log/salt/minion"
"log_level": "info"
"log_level_logfile": "info"
"master":
- "<saltmaster>"
"master_tries": -1
"minion_id_caching": false
"ping_interval": 2
"rejected_retry": true
"retry_dns": 5
"retry_dns_count": 3
```

Salt Master Config
```
"auto_accept": true
"ext_pillar":
- "git":
  - "<https://internal_git_repo>":
    - "root": "pillar"
"fileserver_backend":
- "gitfs"
"git_pillar_insecure_auth": true
"git_pillar_password": "<service_account_password>"
"git_pillar_provider": "pygit2"
"git_pillar_user": "<service_account>"
"gitfs_insecure_auth": true
"gitfs_password": "<service_account_password>"
"gitfs_provider": "pygit2"
"gitfs_remotes":
- "<https://internal_git_repo>"
- "<https://internal_formula_with_problem>"
- <redacted>
"gitfs_user": "<service_account>"
"log_level": "info"
```

**Steps to Reproduce the behavior**
Running `salt-call state.apply` reproduces the error

**Expected behavior**
All file.managed resources should complete successfully

**Screenshots**

**Versions Report**
Versions from Minion
```
# salt-call --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1040-gcp
        system: Linux
       version: Ubuntu 20.04 focal
```

Versions from Master
```
# salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1040-gcp
        system: Linux
       version: Ubuntu 20.04 focal
```

**Additional context**

**Comment by danielrobbins** [comment]
These are notes related to the issue, from a developer perspective.

From https://docs.python.org/3/library/weakref.html#comparing-finalizers-with-del-methods

"However, handling of __del__() methods is notoriously implementation specific, since it depends on internal details of the interpreter’s garbage collector implementation.

A more robust alternative can be to define a finalizer which only references the specific functions and objects that it needs, rather than having access to the full state of the object..."

The current salt code uses a ``__del__()`` method. It seems likely that the bug reported here is caused by the fragility of using ``__del__()`` for this purpose, so a good first step would be to follow best practices and replace the use of ``__del__()`` with a finalizer, and specifically call ``weakref.finalize(obj, remove_ref, _refcount_lock)`` -- in other words, pass the ``_refcount_lock`` to the finalizer, so the finalizer ALWAYS will get the ``_refcount_lock`` as an argument. If the refcount is decremented by the finalizer in this way, it should ALWAYS have a valid ``_refcount_lock`` and thus should NEVER fail as in the reported traceback where ``_refcount_lock`` was somehow not yet defined.

**Comment by corey-hammerton** [comment]
I managed to re-produce the situation with a better stacktrace. We are using [prometheus-formula](https://github.com/saltstack-formulas/prometheus-formula) with archive true. When the minion tried to process the archive.extracted function, the output below had appeared

```
[INFO    ] Running state [/opt/prometheus/node_exporter-v1.1.2] at time 17:54:06.157019
[INFO    ] Executing state archive.extracted for [/opt/prometheus/node_exporter-v1.1.2]
[ERROR   ] Failed to cache https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz: 'master_uri'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/states/archive.py", line 1046, in extracted
    result = __states__["file.cached"](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/file.py", line 8565, in cached
    local_copy = __salt__["cp.is_cached"](name, saltenv=saltenv)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/cp.py", line 725, in is_cached
    return _client().is_cached(path, saltenv)
  File "/usr/lib/python3/dist-packages/salt/modules/cp.py", line 166, in _client
    _mk_client()
  File "/usr/lib/python3/dist-packages/salt/modules/cp.py", line 159, in _mk_client
    ] = salt.fileclient.get_file_client(__opts__)
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 53, in get_file_client
    return {"remote": RemoteClient, "local": FSClient, "pillar": PillarClient}.get(
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 1067, in __init__
    self.channel = salt.transport.client.ReqChannel.factory(self.opts)
  File "/usr/lib/python3/dist-packages/salt/transport/client.py", line 23, in factory
    return SyncWrapper(
  File "/usr/lib/python3/dist-packages/salt/utils/asynchronous.py", line 70, in __init__
    self.obj = cls(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/transport/client.py", line 129, in factory
    return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 167, in __new__
    obj.__singleton_init__(opts, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 258, in __singleton_init__
    self.auth = salt.crypt.AsyncAuth(self.opts, io_loop=self._io_loop)
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 495, in __new__
    key = cls.__key(opts)
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 514, in __key
    opts["master_uri"],  # master ID
KeyError: 'master_uri'
Exception ignored in: <function AsyncZeroMQReqChannel.__del__ at 0x7f29f2753790>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/transport/zeromq.py", line 306, in __del__
    with self._refcount_lock:
AttributeError: 'AsyncZeroMQReqChannel' object has no attribute '_refcount_lock'
[ERROR   ] Failed to cache https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz: 'master_uri'
```

**Comment by corey-hammerton** [comment]
Is there an update to this issue? It's been more than 30 days since the last update

**Comment by corey-hammerton** [comment]
After upgrading our Salt Master and Minions to v3003.1, we seem to be no longer experiencing this issue. Were there any changes to the ZeroMQ mechanisms that could have addressed this?

**Comment by dwoz** [comment]
Not reproducible on supported branches. The singleton `AsyncZeroMQReqChannel` (with the `__del__`/`_refcount_lock` path and the `master_uri` `__singleton_init__` KeyError) was removed in 7af10f24d5d ("Remove singletons", first shipped in v3004). `salt/transport/zeromq.py` no longer defines `AsyncZeroMQReqChannel`, `_refcount_lock`, or `__del__` on 3006.x, 3007.x, 3008.x, or master. Reporter also confirmed upgrading to 3003.1 resolved it. Closing.
