### ISSUE TITLE
salt pkg.installed with sources doesn't work with remote packages

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#24872]
The following state fails, it looks like it is evaluating the fileproto incorrectly.

```
[root@salt salt]# cat pgsql/init.sls
postgresql repo:
  pkg.installed:
    - name: pgdg-centos94
    - sources:
      - pgdg-centos94: "salt://pgsql/files/pgdg-centos94-9.4-1.noarch.rpm"

postgresql package:
  pkg.latest:
    - name: postgresql94-server

  file.append:
    - name: /etc/profile.d/pgsql.sh
    - text: export PATH="/usr/pgsql-9.4/bin:$PATH"
```

```
[root@test salt]# salt-call state.sls pgsql
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://pgsql/init.sls'
[ERROR   ] IFTTT Secret Key Unavailable, not loading.
[INFO    ] Running state [pgdg-centos94] at time 20:11:40.421451
[INFO    ] Executing state pkg.installed for pgdg-centos94
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
[INFO    ] Executing command ['yum', '-q', 'clean', 'expire-cache'] in directory '/root'
[INFO    ] Executing command ['yum', '-q', 'check-update'] in directory '/root'
[ERROR   ] An error was encountered while installing package(s): Path 's' is not absolute
[INFO    ] Completed state [pgdg-centos94] at time 20:12:01.676805
local:
----------
          ID: postgresql repo
    Function: pkg.installed
        Name: pgdg-centos94
      Result: False
     Comment: An error was encountered while installing package(s): Path 's' is not absolute
     Started: 20:11:40.421451
    Duration: 21255.354 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
```
This appears to be only broken in develop, 2015.5 branch works fine.
```
[root@test salt]# salt-call --versions-report
Salt Version:
           Salt: 2015.5.2-6472-gb72b392

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
       pycrypto: 2.6.1

System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.4.2.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

**Comment by gtmanfred** [comment]
it works on the 2015.5 branch.

```
[root@test salt]# salt-call --versions-report
           Salt: 2015.5.2-319-g6c5b788
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: 4.1
[root@test salt]# salt-call state.sls pgsql
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://pgsql/init.sls'
[ERROR   ] IFTTT Secret Key Unavailable, not loading.
[ERROR   ] Exception raised when processing __virtual__ function for boto_ec2. Module will not be loaded global name '__utils__' is not defined
[WARNING ] salt.loaded.int.module.boto_ec2.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_ec2', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for nspawn. Module will not be loaded 'module' object has no attribute 'to_str'
[WARNING ] salt.loaded.int.module.nspawn.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nspawn', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_rds. Module will not be loaded global name '__utils__' is not defined
[WARNING ] salt.loaded.int.module.boto_rds.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_rds', please fix this.
[INFO    ] Running state [pgdg-centos94] at time 20:14:41.906635
[INFO    ] Executing state pkg.installed for pgdg-centos94
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
[INFO    ] Executing command ['yum', '-q', 'clean', 'expire-cache'] in directory '/root'
[INFO    ] Executing command ['yum', '-q', 'check-update'] in directory '/root'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://pgsql/files/pgdg-centos94-9.4-1.noarch.rpm'
[INFO    ] Executing command 'rpm -qp --queryformat "\'%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-none\'" /var/cache/salt/minion/files/base/pgsql/files/pgdg-centos94-9.4-1.noarch.rpm' in directory '/root'
[INFO    ] Executing command 'yum -y     install /var/cache/salt/minion/files/base/pgsql/files/pgdg-centos94-9.4-1.noarch.rpm' in directory '/root'
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
[INFO    ] Installed Packages:
pgdg-centos94 changed from absent to 9.4-1

[INFO    ] Loading fresh modules for state activity
[INFO    ] Completed state [pgdg-centos94] at time 20:14:50.946509
[INFO    ] Running state [postgresql94-server] at time 20:14:50.949821
[INFO    ] Executing state pkg.latest for postgresql94-server
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}'   --pkgnarrow=available postgresql94-server" in directory '/root'
[ERROR   ] IFTTT Secret Key Unavailable, not loading.
[ERROR   ] Exception raised when processing __virtual__ function for boto_ec2. Module will not be loaded global name '__utils__' is not defined
[WARNING ] salt.loaded.int.module.boto_ec2.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_ec2', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for nspawn. Module will not be loaded 'module' object has no attribute 'to_str'
[WARNING ] salt.loaded.int.module.nspawn.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'nspawn', please fix this.
[ERROR   ] Exception raised when processing __virtual__ function for boto_rds. Module will not be loaded global name '__utils__' is not defined
[WARNING ] salt.loaded.int.module.boto_rds.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_rds', please fix this.
[INFO    ] Package postgresql94-server is already up-to-date.
[INFO    ] Completed state [postgresql94-server] at time 20:14:51.569753
[INFO    ] Running state [/etc/profile.d/pgsql.sh] at time 20:14:51.572450
[INFO    ] Executing state file.append for /etc/profile.d/pgsql.sh
[INFO    ] File /etc/profile.d/pgsql.sh is in correct state
[INFO    ] Completed state [/etc/profile.d/pgsql.sh] at time 20:14:51.574100
local:
----------
          ID: postgresql repo
    Function: pkg.installed
        Name: pgdg-centos94
      Result: True
     Comment: The following packages were installed/updated: pgdg-centos94
     Started: 20:14:41.906635
    Duration: 9039.874 ms
     Changes:
              ----------
              pgdg-centos94:
                  ----------
                  new:
                      9.4-1
                  old:
----------
          ID: postgresql package
    Function: pkg.latest
        Name: postgresql94-server
      Result: True
     Comment: Package postgresql94-server is already up-to-date.
     Started: 20:14:50.949821
    Duration: 619.932 ms
     Changes:
----------
          ID: postgresql package
    Function: file.append
        Name: /etc/profile.d/pgsql.sh
      Result: True
     Comment: File /etc/profile.d/pgsql.sh is in correct state
     Started: 20:14:51.572450
    Duration: 1.65 ms
     Changes:

Summary
------------
Succeeded: 3 (changed=1)
Failed:    0
------------
Total states run:     3
```

**Comment by jfindlay** [comment]
@gtmanfred, thanks for the report.  I've traced this down to [this commit](59f56bcc81775656fc5e5c7168f0ecd19ca6836a), where on https://github.com/saltstack/salt/blob/develop/salt/modules/pkg_resource.py#L141 the intent seems to be to pack in the package file location and the version requested, but instead it is sending in the first character of the source string to `cp.cache_file` and the second character as the version.  I looked at how various package management modules (yum, apt, ebuild) handle this value, `pkg_params`.  They all seem to do something different with it, so I'm unsure what the intent of that (incomplete) commit was here.

**Comment by gtmanfred** [comment]
@rallytime this one also probably needs to be marked as holding up 2015.8, because it is a pretty big regression for if you are installing <repo>-release.rpm packages in salt.

**Comment by basepi** [comment]
[this is a test](59f56bcc81775656fc5e5c7168f0ecd19ca6836a)

Github's markup seems to be butchering the conversion on that SHA, want to report to Github.

**Comment by basepi** [comment]
@terminalmage ping

**Comment by terminalmage** [comment]
Yeah I likely caused this with some recent work I did making ``sources`` version-aware.

**Comment by terminalmage** [comment]
I'll take a look sometime in the next couple days.

**Comment by gtmanfred** [comment]
Probably, if you check a previous comment it looks like it has to do with how the string splitting happens.

**Comment by terminalmage** [comment]
Yeah, I think it's actually that it is trying to iterate through a list but the item through which it is iterating is instead a string. Should be easy to fix, I'll get to it before the end of the week.

**Comment by gtmanfred** [comment]
Cool, thanks!

**Comment by gtmanfred** [comment]
```
╘═😸 git diff                                                                                                                                                                                                                                                                                                                                                                 2 （╯°□°）╯︵ ┻━┻
diff --git a/salt/modules/pkg_resource.py b/salt/modules/pkg_resource.py
index 45e3fbf..97e7ccf 100644
--- a/salt/modules/pkg_resource.py
+++ b/salt/modules/pkg_resource.py
@@ -134,6 +134,8 @@ def parse_targets(name=None,
 
         srcinfo = []
         for pkg_name, pkg_src in six.iteritems(sources):
+            if len(pkg_src) > 2:
+                pkg_src = ''.join(pkg_src)
             if __salt__['config.valid_fileproto'](pkg_src):
                 # Cache package from remote source (salt master, HTTP, FTP) and
                 # append the cached path.
```

This is a quick fix that works for right now until you get a chance to look.

Thanks!

**Comment by terminalmage** [comment]
I haven't been able to reproduce on 2015.8 or develop, though I did find what turned out to be an unrelated issue with error reporting.

The exception appears to be happening in the fileclient, as the exception text matches code in ``salt.fileclient.Client.get_url()``, which is called when caching the file.

I think the preflight checks are working and the error might actually be in yumpkg.py's install function.

**Comment by terminalmage** [comment]
Well, ``pkg_resource.parse_targets`` is invoked by ``pkg.install``, and that's the only code in the pkg.install state that would be running ``cp.cache_file``.

**Comment by gtmanfred** [comment]
Seems to not be doing it on develop.

I am still testing to see if I can reproduce it again on 2015.5 or 2015.8

I think it might have just been a glitch for that day.

**Comment by gtmanfred** [comment]
Couldn't replicate it again.  Closing

**Comment by terminalmage** [comment]
No problem, thanks for taking another look at it. Well, thanks to this issue I found a problem with how we log errors for local binary packages, so it was still a productive bug report.

**Comment by terminalmage** [comment]
Looks like this was fixed several days after the opening of this issue here: https://github.com/saltstack/salt/pull/25048
