### ISSUE TITLE
ext_pillar no longer works in masterless minion setup

### ISSUE THREAD

**Issue by johannmiller** [saltstack/salt#26035]
## Desc: 

Setting ext_pillar in /etc/salt/minion does not work in masterless configuration. This was working in 2014.1.5 - the version I upgraded from. 
### Version & OS info:

Ubuntu 14.04

``` yaml
vagrant@vagrant-ubuntu-trusty-64:~$ sudo salt-call --versions-report
           Salt: 2015.5.2
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```
### /etc/salt/minion contents:

``` yaml
master: localhost
id: my_id
file_client: local

ext_pillar:
  - git: master git+ssh://git@github.com/my_org/my_repo.git
```
### The tail of highstate output. My pillar *.sls files can't be found.

```
> sudo salt-call state.highstate

local:
    Data failed to compile:
----------
    Rendering SLS 'base:celery' failed: Jinja variable 'dict object' has no attribute 'ssh_user'
----------
    Rendering SLS 'base:django' failed: Jinja variable 'dict object' has no attribute 'ssh_user'
```
### Curious about this. The ext_pillar is obviously registered. But why does pillar_roots come up? /srv/pillar does not exist. Is pillar_roots overriding ext_pillar?

``` yaml
>sudo salt-call pillar.items | grep --after-context=5 --before-context=5 pillar
        doc:
            False
        environment:
            None
        ext_job_cache:
        ext_pillar:
            |_
              ----------
              git:
                  master git+ssh://git@github.com/my_org/my_repo.git
        extension_modules:
--
        fileserver_limit_traversal:
            False
        force_color:
            False
        fun:
            pillar.items
        gitfs_base:
            master
        gitfs_env_blacklist:
        gitfs_env_whitelist:
        gitfs_insecure_auth:
--
            None
        permissive_pki_access:
            False
        pidfile:
            /var/run/salt-minion.pid
        pillar:
            ----------
            master:
                ----------
                __role:
                    minion
--
                doc:
                    False
                environment:
                    None
                ext_job_cache:
                ext_pillar:
                    |_
                      ----------
                      git:
                          master git+ssh://git@github.com/my_org/my_repo.git
                extension_modules:
--
                fileserver_limit_traversal:
                    False
                force_color:
                    False
                fun:
                    pillar.items
                gitfs_base:
                    master
                gitfs_env_blacklist:
                gitfs_env_whitelist:
                gitfs_insecure_auth:
--
                    None
                permissive_pki_access:
                    False
                pidfile:
                    /var/run/salt-minion.pid
                pillar_roots:
                    ----------
                    base:
                        - /srv/pillar
                ping_interval:
                    0
                pki_dir:
                    /etc/salt/pki/minion
                providers:
--
                    salt://win/repo/winrepo.p
                zmq_filtering:
                    False
                zmq_monitor:
                    False
        pillar_roots:
            ----------
            base:
                - /srv/pillar
        ping_interval:
            0
        pki_dir:
            /etc/salt/pki/minion
```

**Comment by jfindlay** [comment]
@johannmiller, this looks like a bug to me, thanks for the report.

**Comment by drawsmcgraw** [comment]
@johannmiller @jfindlay I'm getting the same thing. Masterless minion running locally, using `ext_pillar` with git, and Pillar is empty.

Possibly related (at least of interest), my Master is configured the same way (`ext_pillar` + git). If I run a `salt-call` on that master, Pillar gets populated. However, adding `--local` to the run returns nothing.

```
$ sudo salt-call --local pillar.get ntp
local:
$ sudo salt-call  pillar.get ntp
local:
    ----------
    servers:
        - 0.ntp.example.com
        - 1.ntp.example.com
```

Versions:

```
$ salt-run --versions-report
           Salt: 2015.5.3
         Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: 0.5.0
        Tornado: 4.2.1
```

**Comment by cachedout** [comment]
It appears this was introduced here: https://github.com/saltstack/salt/pull/15091/files

**Comment by cachedout** [comment]
OK, that should fix it. Works well in my testing.

**Comment by drawsmcgraw** [comment]
@cachedout Thanks! Unfortunately I haven't verified the fix in my environment but if it works in your testing, that's good enough for me.

**Comment by cachedout** [comment]
That fix didn't work as-designed. I'll have to take another swing at this.

**Comment by GeekyTex** [comment]
I'm running into this as well, albeit using s3 as my external pillar source. Salt version is 2015.5.8.

Any update/fix/workaround coming soon *crosses fingers*

Thanks.

**Comment by drawsmcgraw** [comment]
Just gave it another shot with `2015.8.4` and seeing the same behavior.  Here's a version report:

```
Salt Version:
           Salt: 2015.8.4
 
Dependency Versions:
         Jinja2: unknown
       M2Crypto: 0.20.2
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: 0.20.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: 0.20.3
   python-gnupg: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: CentOS 6.7 Final
```


And here's the output of running a `pillar.get` with `-l trace`. The only thing of possible notice is the two lines: 
```
[TRACE   ] Loaded git_pillar as virtual git
[DEBUG   ] LazyLoaded git.ext_pillar
```
Here's the full output.

```
[root@localhost yum.repos.d]# salt-call pillar.get openstack -l trace
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/standalone.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/standalone.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 192.168.122.107
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found the in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/standalone.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/standalone.conf
[TRACE   ] 'dmidecode' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] 'smbios' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] Loading core.hwaddr_interfaces grain
[TRACE   ] Loading core.hostname grain
[TRACE   ] Loading core.get_master grain
[TRACE   ] Loading core.pythonversion grain
[TRACE   ] Loading core.path grain
[TRACE   ] Loading core.get_server_id grain
[TRACE   ] Loading core.ip6 grain
[TRACE   ] Loading core.ip4 grain
[TRACE   ] Loading core.saltversion grain
[TRACE   ] Loading core.saltpath grain
[TRACE   ] Loading core.pythonexecutable grain
[TRACE   ] Loading core.fqdn_ip4 grain
[TRACE   ] Loading core.fqdn_ip6 grain
[TRACE   ] Loading core.ip6_interfaces grain
[TRACE   ] Loading core.ip4_interfaces grain
[TRACE   ] Loading core.append_domain grain
[TRACE   ] Loading core.os_data grain
[TRACE   ] 'dmidecode' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] 'smbios' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] 'virt-what' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[TRACE   ] 'systemd-detect-virt' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] 'virt-what' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] 'dmidecode' could not be found in the following search path: ['/usr/local/sbin', '/usr/local/bin', '/sbin', '/bin', '/usr/sbin', '/usr/bin', '/root/bin']
[TRACE   ] Loading core.zmqversion grain
[TRACE   ] Loading core.saltversioninfo grain
[TRACE   ] Loading core.pythonpath grain
[TRACE   ] Loading core.id_ grain
[TRACE   ] Loading core.locale_info grain
[TRACE   ] Loading core.get_machine_id grain
[TRACE   ] Loading core.ip_interfaces grain
[TRACE   ] Device ram0 does not report itself as an SSD
[TRACE   ] Device ram1 does not report itself as an SSD
[TRACE   ] Device ram2 does not report itself as an SSD
[TRACE   ] Device ram3 does not report itself as an SSD
[TRACE   ] Device ram4 does not report itself as an SSD
[TRACE   ] Device ram5 does not report itself as an SSD
[TRACE   ] Device ram6 does not report itself as an SSD
[TRACE   ] Device ram7 does not report itself as an SSD
[TRACE   ] Device ram8 does not report itself as an SSD
[TRACE   ] Device ram9 does not report itself as an SSD
[TRACE   ] Device ram10 does not report itself as an SSD
[TRACE   ] Device ram11 does not report itself as an SSD
[TRACE   ] Device ram12 does not report itself as an SSD
[TRACE   ] Device ram13 does not report itself as an SSD
[TRACE   ] Device ram14 does not report itself as an SSD
[TRACE   ] Device ram15 does not report itself as an SSD
[TRACE   ] Device loop0 does not report itself as an SSD
[TRACE   ] Device loop1 does not report itself as an SSD
[TRACE   ] Device loop2 does not report itself as an SSD
[TRACE   ] Device loop3 does not report itself as an SSD
[TRACE   ] Device loop4 does not report itself as an SSD
[TRACE   ] Device loop5 does not report itself as an SSD
[TRACE   ] Device loop6 does not report itself as an SSD
[TRACE   ] Device loop7 does not report itself as an SSD
[TRACE   ] Device vda does not report itself as an SSD
[TRACE   ] Device dm-0 does not report itself as an SSD
[TRACE   ] Device dm-1 does not report itself as an SSD
[TRACE   ] Device dm-2 does not report itself as an SSD
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[TRACE   ] Loaded git_pillar as virtual git
[DEBUG   ] LazyLoaded git.ext_pillar
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pillar.get
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': ''}
local:
```

I'll maintain a workaround with some scheduled git pulls in the meanwhile.

**Comment by fcayre** [comment]
Hi here,

still seeing this bug with versions below. Does that mean that masterless mode is a second-class citizen? I'd rather know :-/

Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: utf-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.0
