### PR TITLE
Fix stacktrace when `--summary` is used

### LINKED ISSUE #24111: cli option '--summary' got broken after upgrade to 2015.5.1
```python
(jail) [root#jail_salt][w:0][j:0][.../salt/states]> salt --version
salt 2015.5.1 (Lithium)
(jail) [root#jail_salt][w:0][j:0][.../salt/states]> salt 'dt-node03' grains.get saltversion
dt-node03:
    2015.5.0
(jail) [root#jail_salt][w:0][j:0][.../salt/states]> salt 'dt-node03' --summary grains.get saltversion
dt-node03:
    2015.5.0
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 208, in run
    self._print_returns_summary(ret)
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 240, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/salt", line 9, in <module>
    load_entry_point('salt==2015.5.1', 'console_scripts', 'salt')()
  File "/usr/local/lib/python2.7/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 208, in run
    self._print_returns_summary(ret)
  File "/usr/local/lib/python2.7/site-packages/salt/cli/salt.py", line 240, in _print_returns_summary
    minion_ret = ret[each_minion].get('ret')
AttributeError: 'str' object has no attribute 'get'
(jail) [root#jail_salt][w:0][j:0][.../salt/states]>
```

### PR DESCRIPTION
**Pull request by msteed**
Fix access of `ret[]` in `_print_returns_summary()`.

Fixes #24111.

### CODE REVIEW

**Comment by plastikos** [comment]
See #27099
