### ISSUE TITLE
Crypto.Cipher cannot import name PKCS1_OAEP

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#29268]
I've got several SuSE 11.3 servers that are generating the following error when trying to start the minion:
```ImportError: cannot import name PKCS1_OAEP```

The full log trace is at:
https://gist.github.com/racooper/751b5f1b232209917d30

The system has pycrypto 2.6.1-36 installed.  The same salt minion is working on other SuSE 11.3 servers with 2.6.1-35, 2.6.1-36, and 2.6.1-39, so I'm not sure what's causing the issue. Any suggestions? (asking here because Freenode is still under DDOS.)

**Comment by jfindlay** [comment]
@racooper, thanks for reporting.  How did you install salt, and what salt version are you using?

**Comment by jfindlay** [comment]
Possibly related to https://github.com/saltstack/salt-bootstrap/issues/639, https://github.com/saltstack/salt-bootstrap/issues/643, #25502.

@cachedout, @dmurphy18, do you have any ideas on this issue?

**Comment by racooper** [comment]
it's salt 2015.8.1, installed from http://download.opensuse.org/repositories/devel:/languages:/python/SLE_11_SP3/ which is the recommended repo in Salt documentation.

**Comment by racooper** [comment]
I figured out the problem.  for some reason salt-minion is trying to use an old version of pycrypto that one of the developers installed in /usr/local/lib64 instead of the system packaged (newer) version in /usr/lib64.  How do I force salt-minion to use the system package instead of the local one?

https://gist.github.com/racooper/ab4dae0b6d69b54c828a

The problem is that our developers have installed old versions of modules raven, Twisted and pycrypto.  how do I force salt-minion to use the system packages in /usr/lib64/python2.6/site-packages/ ?

**Comment by jfindlay** [comment]
@racooper, I think the solution here may be to update `$PYTHONPATH` in the salt-minion init script to override `/usr/local/lib64`.  Something like `PYTHONPATH='/usr/lib64'` should work.

**Comment by racooper** [comment]
Alright...I've tried PYTHONPATH=/usr/lib64, PYTHONPATH=/usr, export PYTHONPATH=/usr, export PYTHONPATH=/usr/lib64/python2.6, and various other combinations.  I've put them in the top of the init script where the $PYTHON variable is set, and inside the start() function as well.  Nowhere does it seem to make any difference at all.

**Comment by jfindlay** [comment]
@racooper, it's been a while since I've used initscripts, but you could investigate something like https://unix.stackexchange.com/questions/44370/how-to-make-unix-service-see-environment-variables#44378.

**Comment by racooper** [comment]
so I haven't totally figured it out. I have about a dozen machines that are still not working, and some of them don't have the /usr/local packages.  It's salt-minion 2015.8.3-221.1 from SuSE build.  the error messages are in https://gist.github.com/racooper/305e49eecbedbbb2491b
````
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.6
       M2Crypto: 0.21.1
           Mako: 1.0.1
         PyYAML: 3.10
          PyZMQ: 14.7.0
         Python: 2.6.9 (unknown, Apr  7 2015, 08:28:12)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: 1.2.1
       cherrypy: 3.2.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.2
      pycparser: 2.12
       pycrypto: 2.4.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: SuSE 11 x86_64
        machine: x86_64
        release: 3.0.101-0.47.71-default
         system: SUSE Linux Enterprise Server  11 x86_64
````

**Comment by racooper** [comment]
Finally got it resolved by the developers removing the older version of pycrypto and using the newer system version.

**Comment by jfindlay** [comment]
Nice, that's always a relief. :-)
