### ISSUE TITLE
Custom modules not sync'd to minions prior to highstate starting in Salt 2018.3

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack/salt#53036]
I have a custom module in the `_modules` directory inside my states directory. Calling the module from a jinja2 template in Salt 2017.7.8 works, but it doesn't work in 2018.3.4.

Here's what I see on 2018.3.4:  

```
          ID: /xxx/xxx
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2561, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4759, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4199, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 170, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'my_custom_module.my_custom_function'
```

**Comment by garethgreenaway** [comment]
@cmclaughlin Thanks for the report.  Are you able to run your custom module via either the `salt-call` or `salt` commands?  I was able to initially reproduce this but once I ran `saltutils.sync_all` then it works as expected.

**Comment by cmclaughlin** [comment]
I think I narrowed it down - my custom module in `_modules` isn't being automatically sync'd to the minion on highstate runs. After running `saltutil.sync_all` manually calling it from a jinja2 template or `salt-call` works.

**Comment by cmclaughlin** [comment]
In case this might help...

```
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: 3.7.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Dec  8 2015, 18:25:23)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.77-31.58.amzn1.x86_64
         system: Linux
        version: Not Installed
```

**Comment by cmclaughlin** [comment]
Perhaps I should mention we work off environments (i.e. `saltenv=xxx`)

**Comment by cmclaughlin** [comment]
I tested this some more... I'm able to reproduce this reliably:

* Restart minion
* Run saltutil.clear_cache
* Run state.apply or state.highstate

Custom modules are not sync'd and fail from jinja2 and salt-call. I can verify that they don't exist on the minion file system.

**Comment by cmclaughlin** [comment]
This does seem to be related to `saltenv` -- I'm not able to reproduce it with `saltenv=base` even though in my case `base` and my personal environment are the same git revision.

**Comment by cmclaughlin** [comment]
Tested some more... no longer think it's related to `saltenv`.

`state.apply xxx` does not sync modules, but `state.apply` with no args and `state.highstate` do.

Perhaps this is by design.

**Comment by garethgreenaway** [comment]
:+1: glad you got it figured out.

**Comment by cmclaughlin** [comment]
confirmed it's by design.
