### ISSUE TITLE
[BUG] Regression: TOML serializer broken after ba9a222f532c52b59038f809dbabf7ad63823f59

### ISSUE THREAD

**Issue by morsik** [saltstack/salt#58822]
**Description**
TOML serializer broken after ba9a222f532c52b59038f809dbabf7ad63823f59

This commit breaks code (as I mentioned in comment there specific to file).

`import toml` tries to load this file itself which later doesn't contain `dump()` or `dumps()` function. Also, `toml` is different Python library than `pytoml`, so… which one should be used anyway?
This is because Python import path firstly try to import local files and after that tries to load python modules.

Currently I'm having this problem:
```
          ID: telegraf-config
    Function: file.serialize
        Name: /etc/telegraf/telegraf.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/serializers/toml.py", line 57, in serialize
                  return toml.dumps(obj, **options)
              AttributeError: module 'toml' has no attribute 'dumps'
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 7863, in serialize
                  dataset, **serializer_options.get(serializer_name, {})
                File "/usr/lib/python3/dist-packages/salt/serializers/toml.py", line 59, in serialize
                  raise SerializationError(error)
              salt.serializers.SerializationError: module 'toml' has no attribute 'dumps'
     Started: 13:52:05.629876
    Duration: 11.287 ms
     Changes:   
```

Reverting to `import pytoml as toml` fixes issue.

**Setup**
SLS in formula (a little cutted-down version, just use `formatter` option in `file.serialize`):
```sls
telegraf-config:
  file.serialize:
  - name: /etc/telegraf/telegraf.conf
  - formatter: toml
  - dataset:
      {{ salt['pillar.get']('telegraf', default=defaults['telegraf'], merge=True)|yaml(False)|indent(6) }}
  - user: root
  - group: root
  - mode: 644
```

**Steps to Reproduce the behavior**
Run `state.apply` for such state.

**Expected behavior**
Runs cleanly and applies change.

**Versions Report**
<details><summary>salt --versions-report</summary>

(Master is also 3002)

```# salt-call --versions-report
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.5.3 (default, Jul  9 2020, 13:00:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9 stretch
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: Debian GNU/Linux 9 stretch
```
</details>

**Comment by s0undt3ch** [comment]
Fixed in https://github.com/saltstack/salt/pull/59120

**Comment by rnickle** [comment]
I just ran into this in 3003 too, works fine with yaml and json, just not toml:

```
WriteUserInfo:
  file.serialize:
    - name: /tmp/rnickle-dev.yaml
    - dataset: {{ mydata }}
    - formatter: toml
    - user: rnickle
    - mode: '640'
```
Run output:
```
          ID: WriteUserInfo
    Function: file.serialize
        Name: /tmp/rnickle-dev.yaml
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/serializers/toml.py", line 55, in serialize
                  return toml.dumps(obj, **options)
              AttributeError: module 'toml' has no attribute 'dumps'
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 7745, in serialize
                  dataset, **serializer_options.get(serializer_name, {})
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/serializers/toml.py", line 57, in serialize
                  raise SerializationError(error)
              salt.serializers.SerializationError: module 'toml' has no attribute 'dumps'
     Started: 00:38:59.849940
    Duration: 15.489 ms
     Changes:   
```
salt-versions:
```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 3.9.4
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-6-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

**Comment by jpmckinney** [comment]
#59120 fixed renderers/toml but not serializers/toml.

**Comment by lkubb** [comment]
It seems this bug is still relevant and should be reopened, I get the same error on 3004.1.

[salt/serializers/toml.py](https://github.com/saltstack/salt/blob/9de7a6f9e5be23f1310174163a23f0d4763ebc33/salt/serializers/toml.py#L13) contains ``import toml``, which is the current cause of this bug.
