### PR TITLE
fixed top function which was broken since commit 002aa88a97e

### PR DESCRIPTION
**Pull request by tamcore**
### What does this PR do?
fixed top function which was broken since commit 002aa88a97e

### What issues does this PR fix or reference?
```
2018-04-04 12:49:51,312 [salt.daemons.masterapi:540 ][ERROR   ][11108] Top function ext_nodes failed with error 'int' object has no attribute 'communicate' for minion random.system.local
```

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
Backported to 2018.3 in https://github.com/saltstack/salt/pull/46872 and unit test added.
