### ISSUE TITLE
[Bug]: salt-cloud 3008.0 fails to run at all

### ISSUE THREAD

**Issue by jpmsilva** [saltstack/salt#69281]
### What happened?

Trying to run salt-cloud in version 3008.0 yields the following error:

```
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 12, in <module>
    sys.exit(salt_cloud())
             ~~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/scripts.py", line 556, in salt_cloud
    client.run()
    ~~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/cli.py", line 73, in run
    mapper = salt.cloud.Map(self.config)
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/__init__.py", line 1622, in __init__
    self.rendered_map = self.read()
                        ~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/__init__.py", line 1741, in read
    self.minion = salt.minion.MasterMinion(local_minion_opts)
                  ^^^^^^^^^^^
AttributeError: module 'salt' has no attribute 'minion'
```

After some research, we found that an import is needed in the file `salt/cloud/__init__.py`:
```
import salt.minion
```

Once we added that import `salt-cloud` runs correctly again.

I checked the history of `salt/cloud/__init__.py` but found no recent changes that might explain this. I have no relevant python knowledge to understand why it was working in salt 3007.14 and no longer works in 3008.0 when the nothing relevant appears to have changed since. Perhaps it is something related to the python version (3.10 -> 3.14)?

### Type of salt install

Official deb

### Major version

3008.x

### What supported OS are you seeing the problem on? Can select multiple. (If bug appears on an unsupported OS, please open a GitHub Discussion instead)

ubuntu-24.04

### salt --versions-report output

```shell
Salt Version:
          Salt: 3008.0
 
Python Version:
        Python: 3.14.5 (main, May 12 2026, 03:56:57) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 2.0.0
      cherrypy: 18.10.0
  cryptography: 46.0.7
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: 4.0.12
     gitpython: 3.1.50
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 3.00
      pycrypto: Not Installed
  pycryptodome: 3.23.0
        pygit2: Not Installed
  python-gnupg: 0.5.6
        PyYAML: 6.0.3
         PyZMQ: 27.1.0
        relenv: 0.22.11
         smmap: 5.0.2
       timelib: 0.3.0
       Tornado: 6.5.5
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: ubuntu 24.04.4 noble
        locale: utf-8
       machine: x86_64
       release: 6.17.0-29-generic
        system: Linux
       version: Ubuntu 24.04.4 noble
```
