### PR TITLE
Fix infinte recursion in git pillar in masterless

### LINKED ISSUE #26035: ext_pillar no longer works in masterless minion setup
## Desc: 

Setting ext_pillar in /etc/salt/minion does not work in masterless configuration. This was working in 2014.1.5 - the version I upgraded from. 
### Version & OS info:

Ubuntu 14.04

``` yaml
vagrant@vagrant-ubuntu-trusty-64:~$ sudo salt-call --versions-report
           Salt: 2015.5.2
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```
### /etc/salt/minion contents:

``` yaml
master: localhost
id: my_id
file_client: local

ext_pillar:
  - git: master git+ssh://git@github.com/my_org/my_repo.git
```
### The tail of highstate output. My pillar *.sls files can't be found.

```
> sudo salt-call state.highstate

local:
    Data failed to compile:
----------
    Rendering SLS 'base:celery' failed: Jinja variable 'dict object' has no attribute 'ssh_user'
----------
    Rendering SLS 'base:django' failed: Jinja variable 'dict object' has no attribute 'ssh_user'
```
### Curious about this. The ext_pillar is obviously registered. But why does pillar_roots come up? /srv/pillar does not exist. Is pillar_roots overriding ext_pillar?

``` yaml
>sudo salt-call pillar.items | grep --after-context=5 --before-context=5 pillar
        doc:
            False
        environment:
            None
        ext_job_cache:
        ext_pillar:
            |_
              ----------
              git:
                  master git+ssh://git@github.com/my_org/my_repo.git
        extension_modules:
--
        fileserver_limit_traversal:
            False
        force_color:
            False
        fun:
            pillar.items
        gitfs_base:
            master
        gitfs_env_blacklist:
        gitfs_env_whitelist:
        gitfs_insecure_auth:
--
            None
        permissive_pki_access:
            False
        pidfile:
            /var/run/salt-minion.pid
        pillar:
            ----------
            master:
                ----------
                __role:
                    minion
--
                doc:
                    False
                environment:
                    None
                ext_job_cache:
                ext_pillar:
                    |_
                      ----------
                      git:
                          master git+ssh://git@github.com/my_org/my_repo.git
                extension_modules:
--
                fileserver_limit_traversal:
                    False
                force_color:
                    False
                fun:
                    pillar.items
                gitfs_base:
                    master
                gitfs_env_blacklist:
                gitfs_env_whitelist:
                gitfs_insecure_auth:
--
                    None
                permissive_pki_access:
                    False
                pidfile:
                    /var/run/salt-minion.pid
                pillar_roots:
                    ----------
                    base:
                        - /srv/pillar
                ping_interval:
                    0
                pki_dir:
                    /etc/salt/pki/minion
                providers:
--
                    salt://win/repo/winrepo.p
                zmq_filtering:
                    False
                zmq_monitor:
                    False
        pillar_roots:
            ----------
            base:
                - /srv/pillar
        ping_interval:
            0
        pki_dir:
            /etc/salt/pki/minion
```

### PR DESCRIPTION
**Pull request by cachedout**
Closes #26035

@basepi This may cause a merge conflict but it's small and should be easy to resolve.

### CODE REVIEW

**Comment by jfindlay** [comment]
@cachedout, it looks like there is a test that needs to be updated.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This doesn't look like the right fix. Closing.
