### ISSUE TITLE
salt-cloud: create from template via opennebula no longer works on 2016.3.1

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#34445]
### OpenNebula driver stopped working after upgrade from 2015.8 to 206.3.1

After upgrading to 2016.3.1 on CentOS6/CentOS7 OpenNebula stopped deploying VMs from templates.
Upon closer inspection this appears to be fixed in develop but not in current released version for 2016.3 for el6/el7: 
https://github.com/saltstack/salt/commit/c0c5113 ( https://github.com/saltstack/salt/pull/31232 )
### Setup

Profile configured:

```
centos_6_pfa_nebula:
  provider: opennebula
  image: infra-cen6-pfa-template
  private_key: '/opt/opennebula/pfa_id_rsa'
  script: bootstrap-salt
  script_args: -U -Z -P -I
```
### Steps to Reproduce Issue

`salt-cloud -p centos_6_pfa_nebula test`
Error:

```
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/opennebula.py", line 612, in get_image
    'The specified image, \'{0}\', could not be found.'.format(vm_image)
```
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: 0.6
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: 1.3.8
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.09.1
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.1.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

```

**Comment by mbochenk** [comment]
Documentation is also missing: for develop version to work you need to add "template" option in profile - for ex,. here: https://docs.saltstack.com/en/develop/topics/cloud/opennebula.html

**Comment by Ch3LL** [comment]
I am able to replicate this behavior in 2016.3.1 .

```
master_nebula:
  provider: nebula

nm-cent7:
  image: centos7-base-template-v2
  extends: master_nebula
```

The above configuration works in 2015.8.10 to create the VM but I do see this error: `AttributeError: 'NoneType' object has no attribute 'text'` but the VM is created. In 2016.3.1 with that same profile does not work and states the image could not be found.

I can get this to work in develop without error, although as you state in develop it requires the `template` option in the profile configuration.

**Comment by fracklen** [comment]
@mbochenk @Ch3LL The problem still persists in 2016.3.2. The problem is, that `image` doesn't quite cut it for OpenNebula, as they primarily deal with `template`s.

Also, the version in 2016.3.2 looks up the image id based on image name and uses this for the template id. 🙀 

The version in develop is much more sane. 

@Ch3LL Any chance we could merge the develop version into 2016.3.3?

**Comment by mbochenk** [comment]
@fracklen as a workaround I am using `opennebula.py` on `salt-master` from `develop` in 2016.3.2/3
@Ch3LL  Would be nice to know if and/or when this is going to be merged to release.

**Comment by Ch3LL** [comment]
@mbochenk thanks for bringing this to my attention. 

ping @gtmanfred do you think this change in develop could be backported to 2016.3 or do you think it would have conflicting issues with the current code set?

**Comment by mbochenk** [comment]
@Ch3LL this seems to be resolved in 2016.11 - and I suspect can be closed.

**Comment by rallytime** [comment]
Thanks for following up here @mbochenk. Let's close it. :)
