### PR TITLE
Fix gpg renderer breakage from bef5e66

### LINKED ISSUE #39334: unit.renderers.gpg_test.GPGTestCase.test__decrypt_object fails
### Setup
Checkout salt

### Steps to Reproduce Issue
```
$ tests/runtests.py -n unit.renderers.gpg_test
   -> unit.renderers.gpg_test.GPGTestCase.test__decrypt_object  ..........................................................................................................................................
       Traceback (most recent call last):
         File "/Users/beep/ibm/salt/tests/unit/renderers/gpg_test.py", line 80, in test__decrypt_object
           self.assertEqual(gpg._decrypt_object(secret), secret)
         File "/Users/beep/ibm/salt/salt/renderers/gpg.py", line 282, in _decrypt_object
           if isinstance(obj, cStringIO.InputType):
       AttributeError: 'builtin_function_or_method' object has no attribute 'InputType'
```

I believe this is caused by bef5e66c5b678bd0f46ce0d32a736b34e2aca001.

### Versions Report
$ git rev-parse HEAD
17521fb23c92122c0ac045b092bb46e1ff958080

### PR DESCRIPTION
**Pull request by terminalmage**
bef5e66 sought to make a PY3 compatibility change, but the attribute
from Python2's cStringIO module is not available via the "fake"
cStringIO which six exposes, as six's cStringIO is just the
cStringIO.StringIO function. The other cStringIO class attributes are
not available via six.

This commit adds a new module with a few functions to get information on
StringIO objects both in Python2 and 3, and modifies the files edited in
bef5e66 to use this new module to determine if the object is a readable
StringIO.

Fixes #39334.

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]
Sorry for the breakage.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Test failures seem unrelated.

@cachedout: I'm taking the liberty to merge this since it will help with my Py3 work.
