### PR TITLE
Allow highstate outputter to show all results

### LINKED ISSUE #35423: Stacktrace when running state.sls against an sls does not exist
### Setup
When attempting to run `state.sls` and the state does not exist I am seeing teh following in the debug logs:

```
[ch3ll@thecakeisalie ~]$ sudo salt '*02*' state.sls doesnotexist -ldebug

...
[DEBUG   ] LazyLoaded highstate.output
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'ch3ll-minion02': ["No matching sls found for 'doesnotexist' in env 'base'"]}
[DEBUG   ] Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
AttributeError: 'NoneType' object has no attribute 'rstrip'

[DEBUG   ] LazyLoaded nested.output
ch3ll-minion02:
    - No matching sls found for 'doesnotexist' in env 'base'
[DEBUG   ] jid 20160812160340754435 found all minions set(['ch3ll-minion02'])
ERROR: Minions returned with non-zero exit code
```

### Steps to Reproduce Issue
1. Run `salt '*' state.sls doesnotexist` Just make sure the sls file does not exist in your file_roots

The first bad commit is 82a70e015fbab5decc4ba1176bd066fac0ffa6c2 
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
[root@ch3ll-cent7 salt]# salt --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

### PR DESCRIPTION
**Pull request by cachedout**
This regressed here: 82a70e015fbab5decc4ba1176bd066fac0ffa6c2

The above incorrect assumed that all data flowing into the highstate outputter is expected to be a dictionary. However, looking at _format_host() shows that it does expect to receive multiple types and does handle them accordingly.

I believe that the issue reported in #33915 may be fixed by #35559 instead. This should allow the highstate outputter to display all results instead of stopping after the first one. I would like @terminalmage and @mattglv and possibly @Ch3ll to please confirm this before we get this in.

Resolves #35423

### CODE REVIEW

**Comment by terminalmage** [comment]
Whoops, accidentally closed instead of merged.
