### ISSUE TITLE
docker.installed not working (salt 2015.5.0, docker 1.6.2, dockerpy 0.5.3)

### ISSUE THREAD

**Issue by cmhe** [saltstack/salt#24698]
With this state:

    docker-container-testwebapp-installed:
      docker.installed:
        - name: test/webappcontainer
        - image: test/webapp

I get this error:

          ID: docker-container-testwebapp-installed
    Function: docker.installed
        Name: test/webappcontainer
      Result: False
     Comment: We did not get any expected answer from docker
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerio.py", line 640, in create_container
                  cpuset=cpuset
              TypeError: create_container() got an unexpected keyword argument 'cpuset'
     Started: 11:36:04.069033
    Duration: 2053.745 ms
     Changes:   Invalid Changes data: Container created

**Comment by mpaolini** [comment]
same issue here. Upgrading `dockerpy==0.6.0` solves it for me

**Comment by mpaolini** [comment]
this was introduced in commit 680da07e5fb50b520cd62baee545d60dc36907e0

we just need a documentation update. `dockerpy` version 0.6 and above is now required.

I tested version `1.2.2` also works here

**Comment by cmhe** [comment]
I am running debian 8.0 with the saltstack repositories, so it would be nice to package dockerpy 0.6 in those repositories too.

**Comment by mpaolini** [comment]
@cmhe you can install it using pip. just add a 

```
  pip.installed:
    - name: docker-py == 1.2.2
    - reload_modules: True
```

to your states

**Comment by tkent** [comment]
@cmhe, @mpaolini 

In case it's helpful @cmhe also posted about this issue in #23610. The answer I left there cover's what's going on. As @mpaolini pointed out here you need 0.6.0 or greater of docker-py. It's not really a salt issue, more of a docker-py / salt documentation mis-match.

**Comment by arroyoc** [comment]
@cmhe @tkent @mpaolini Thanks for your input and submitting this issue.

**Comment by jacobhammons** [comment]
@tkent I'm seeing a bit of mismatch between our state and module docs as I update this and I'm hoping you can clarify. 

- The state docs says remote API 1.6 is required and does not mention a specific docker-py version (only that one is required) - http://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerio.html#module-salt.states.dockerio
- The module doc says docker-py 0.5.0 and Docker Remote API 1.12. http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockerio.html#module-salt.modules.dockerio

My thought is to update both docs to state that docker-py 0.6.0 is required. Do you happen to know if 1.12 is the Docker Remote API version required?

Thanks!

**Comment by tkent** [comment]
@jacobhammons 

Unfortunately, I don't know which version of the docker remote API is required. I can only say for certain that 1.18 works since that what I'm using.

Sorry I couldn't be more helpful!
