### ISSUE TITLE
2016.11.0: saltutil.runner returns a different dict structure and breaks template rendering

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#38000]
### Description of Issue/Question
saltutil.runner is now returning a different dict structure to older Salt versions, which caused the majority of my reactors to break.

### Setup
On 2016.3.4 my reactors were working by calling the following function:
<pre>{% set my_variable = salt['saltutil.runner']('pillar.show_pillar', minion='minion')['pillar-key'] %}</pre>

After upgrade to 2016.11.0 I got the following error when reactors were being rendered:
<pre>SaltRenderError: Jinja variable 'dict object' has no attribute 'pillar-key'</pre>

To access the pillar data successfully I had to include the 'return' key for the dict:
<pre>{% set my_variable = salt['saltutil.runner']('pillar.show_pillar', minion='minion')['return']['pillar-key'] %}</pre>

I've had a look through the release notes and I don't think anything like this is documented.

### Steps to Reproduce Issue
Attempt to read pillar data from a Jinja2 based reactor with:
<pre>salt['saltutil.runner']('pillar.show_pillar', minion='minion')['pillar-key']</pre>

### Versions Report
<pre>Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6</pre>

**Comment by Ch3LL** [comment]
@morganwillcock okay I am able to replicate this. Here is the PR where it was added and git bisect shows as first bad commit: https://github.com/saltstack/salt/pull/34977

Particularly its this line:  `return rclient.cmd(_fun, kwarg=kwargs, full_return=True)` in salt/modules/saltutil.py If you change that to be full_return=False then it works.

@terminalmage it seems this was on purpose to add more data to this dictionary. So I'm just trying to figure out if this is a documentation bug where we need to document that the dictionary has been changed or if we want to change the dictionary back to what it was in 2016.3.4

HEre is a docker container to replicate the issue:

1. `docker run -it -v /home/ch3ll/git/salt/:/testing/ ch3ll/issues:38000` (where /home/ch3ll/git/salt is a local clone git salt repo)
2. `salt-master -d; salt-minion -d`
3. `salt '*' state.sls test`

And you will see the following on version 2016.11.0:

```
[root@cbcc5416a88f /]# salt '*' state.sls test
4ae5e8adf3b1:
    Data failed to compile:
----------
    Rendering SLS 'base:test' failed: Jinja variable 'dict object' has no attribute 'pillar-key'
ERROR: Minions returned with non-zero exit code
```

And on version 2016.3.4 it works:

```
[root@cbcc5416a88f testing]# salt '*' state.sls test
4ae5e8adf3b1:
----------
          ID: echo TEST
    Function: cmd.run
      Result: True
     Comment: Command "echo TEST" run
     Started: 17:43:40.167882
    Duration: 13.174 ms
     Changes:   
              ----------
              pid:
                  661
              retcode:
                  0
              stderr:
              stdout:
                  TEST

Summary for 4ae5e8adf3b1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  13.174 ms
```

**Comment by terminalmage** [comment]
Sorry, I was only considering orchestration usage here. I'll get this fixed.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/38028

**Comment by morganwillcock** [comment]
@Ch3LL, @terminalmage thanks for tracking this down so quickly. I'll test the fix soon as I can.

**Comment by morganwillcock** [comment]
It looks fixed to me. Thanks.

Before:
<pre>2016-12-02 16:05:32,481 [salt.template    ][DEBUG   ][8444] compile template: /srv/reactor/my_reactor.sls
2016-12-02 16:05:33,667 [salt.utils.reactor][ERROR   ][8444] Failed to render "/srv/reactor/my_reactor.sls":
</pre>
After:
<pre>2016-12-02 16:07:38,501 [salt.template    ][DEBUG   ][8444] compile template: /srv/reactor/my_reactor.sls
2016-12-02 16:07:39,733 [salt.template    ][PROFILE ][8444] Time (in seconds) to render '/srv/reactor/my_reactor.sls' using 'jinja' renderer: 1.23156118393</pre>

**Comment by terminalmage** [comment]
@morganwillcock thanks for confirming, and sorry again for the inconvenience. I was only thinking about that function being used in the scope of orchestration, that's totally my bad.

Going to close this since the fix is confirmed and merged.
