### ISSUE TITLE
gitfs pillars with pygit2 fails

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#36095]
### Description of Issue/Question
  I am trying to use gitfs, pygit2, pillars, and salt 2016.9. I get the error below. This works with 2016.3.2.

```
2016-09-06 15:03:26,728 [salt.utils.gitfs ][ERROR   ][725] Failed to checkout master from git_pillar remote 'master git@git:/salt-pillars': 'function' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1154, in checkout
    return self.check_root()
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 407, in check_root
    root_dir = salt.utils.path_join(self.cachedir, self.root).rstrip(os.sep)
  File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 889, in path_join
    parts = [os.path.normpath(p) for p in parts]
  File "/usr/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
```
### Setup
```
/etc/salt/master:
failhard: True
state_output: changes
log_level: trace

reactor:
  - 'minion_start':
    - /etc/salt/reactor/minion_start.sls

gitfs_provider: pygit2

fileserver_backend:
  - git

ext_pillar:
  - git:
    - master git@git:/salt-pillars:
      - pubkey: /root/.ssh/id_rsa.pub
      - privkey: /root/.ssh/id_rsa

gitfs_remotes:
  - git@github.com:acme/salt-formulas.git:
    - pubkey: /root/.ssh/id_rsa.pub
    - privkey: /root/.ssh/id_rsa
```

### Steps to Reproduce Issue
1. start master
2. start minion

### Versions Report
2016.9

**Comment by edgan** [comment]
Seems that the object type for self.root changed and the new type breaks the code.

**Comment by edgan** [comment]
I suspect that #35802 broke it.

**Comment by Ch3LL** [comment]
@edgan looks like i'm able to replicate this behavior when using git pillar. When I run `salt '*' pillar.items` i see the error in the debug logs. We will need to get this fixed up thanks.

**Comment by terminalmage** [comment]
That's not a valid versions report, as there is no version "2016.9". Please post the *actual output* of ``salt --versions-report``.

**Comment by terminalmage** [comment]
I've found the issue. #35802 has nothing to do with it, as you can see the reference to ``self.root`` remains unchanged in [the diff from that pull request](https://github.com/saltstack/salt/pull/35802/files#diff-2c34a66e40db8ce28e251f98de56ce31L315).

It does indeed have to do with the change to the ``root`` attribute, however. This was was correctly changed in ee620af as part of the feature implementation for #29954. However, it was broken during a recent merge-forward (see [here](https://github.com/saltstack/salt/commit/2b1ad9e#diff-2c34a66e40db8ce28e251f98de56ce31L406)).

#36215 has been opened to correct this. @rallytime, for future reference, the ``root``, ``mountpoint``, and ``ref`` attributes to any ``GitProvider`` subclass are now function calls as of the Carbon release. This was done to implement per-saltenv configuration per #29954.

**Comment by terminalmage** [comment]
Also, it looks like the ``2016.9`` version was in reference to the ``v2016.9`` tag added to note the carbon branch point. ``salt --versions-report`` does probably show a Salt version of ``2016.9`` for this (as the Salt version is derived from ``git describe`` when installing from a git revision, but we never use these tags to refer to an actual release (RC or otherwise). They're merely there to denote the point where a release branch was branched off of develop.

However, it's still a good idea to include all of the output from ``salt --versions-report`` when opening an issue, _especially_ in cases where gitfs/git_pillar are malfunctioning, as it provides us with the version of GitPython/Pygit2/etc. installed. This is useful information when we cannot initially reproduce the issue, as sometimes the problem only occurs with specific versions of those Python bindings, and installing the exact version you have installed is necessary to properly reproduce the error.
