### ISSUE TITLE
AttributeError: '_pygit2.Config' object has no attribute 'get_bool'

### ISSUE THREAD

**Issue by jmarinaro** [saltstack/salt#42520]
### Description of Issue/Question
I am unable to get gitfs to work in CentOS 6.9 using the recommended module versions.
### Setup
master.d/gitfs.conf:
```
fileserver_backend:
  - git

gitfs_remotes:
  - https://github.com/saltstack/salt.git
```

Dockerfile:
```
FROM centos:6.9

ARG VERSION=latest

RUN yum update -y
RUN yum install -y git
RUN yum install -y epel-release https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el6.noarch.rpm
RUN yum clean expire-cache
RUN yum install -y python27-devel gcc libgit2-devel
RUN yum install -y salt-master
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python2.7 get-pip.py
RUN pip2.7 install pygit2==0.20.3 cherrypy==5.6.0

EXPOSE 4505 4506
ENTRYPOINT ["/usr/bin/salt-master"]
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
# docker run --rm -it -v /srv/docker/salt/master.d:/etc/salt/master.d salt-master:centos -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/auto_accept.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/auto_accept.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/gitfs.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/gitfs.conf
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[INFO    ] Generating master keys: /etc/salt/pki/master
[PROFILE ] Beginning pwd.getpwall() call in masterarpi access_keys function
[PROFILE ] End pwd.getpwall() call in masterarpi access_keys function
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[INFO    ] Starting up the Salt Master
[DEBUG   ] pygit2 gitfs_provider enabled
[DEBUG   ] LazyLoaded git.envs
[CRITICAL] Exception caught while initializing gitfs remote 'https://github.com/saltstack/salt.git': '_pygit2.Config' object has no attribute 'get_bool'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 351, in __init__
    self.new = self.init_remote()
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 1458, in init_remote
    ssl_verify = self.repo.config.get_bool('http.sslVerify')
AttributeError: '_pygit2.Config' object has no attribute 'get_bool'
[CRITICAL] Failed to load gitfs
[CRITICAL] Master failed pre flight checks, exiting
```

### Versions Report
```
# docker run --rm -it -v /srv/docker/salt/master.d:/etc/salt/master.d salt-master:centos --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.20.3
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.10.0-26-generic
         system: Linux
        version: CentOS 6.9 Final
```
