### ISSUE TITLE
[BUG] [v3005.1] salt-ssh crashes when dependency importlib_metadata is at version >=5.0.0

### ISSUE THREAD

**Issue by hartwork** [saltstack/salt#62851]
**Description**
With Salt 3005 and importlib_metadata 5.0.0 I get this crash when running salt-ssh:
```
# time salt-ssh '*' state.apply setup
/usr/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[ERROR   ] 'EntryPoints' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/salt/utils/parsers.py", line 212, in parse_args
    mixin_after_parsed_func(self)
  File "/usr/lib/python3.8/site-packages/salt/utils/parsers.py", line 905, in __setup_logging
    salt._logging.setup_logging()
  File "/usr/lib/python3.8/site-packages/salt/_logging/impl.py", line 971, in setup_logging
    setup_extended_logging(opts)
  File "/usr/lib/python3.8/site-packages/salt/_logging/impl.py", line 878, in setup_extended_logging
    providers = salt.loader.log_handlers(opts)
  File "/usr/lib/python3.8/site-packages/salt/loader/__init__.py", line 857, in log_handlers
    _module_dirs(
  File "/usr/lib/python3.8/site-packages/salt/loader/__init__.py", line 153, in _module_dirs
    for entry_point in entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3.8/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/salt/utils/entrypoints.py", line 41, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
Usage: salt-ssh [options] '<target>' <function> [arguments]
```

After downgrading importlib_metadata to 4.13.0 things are working fine again. Please make Salt work with importlib_metadata >=5.0.0. Thank you!

Related: https://github.com/python/importlib_metadata/issues/409

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
See description

**Expected behavior**
No crash

**Screenshots**
none

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by Dr-Bone** [comment]
Hi
I've the same issue on Arch linux:
```
Oct 11 12:43:47 haproxy systemd[1]: Starting The Salt Minion...
Oct 11 12:43:47 haproxy salt-minion[834]: /usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
Oct 11 12:43:47 haproxy salt-minion[834]:   warnings.warn("Setuptools is replacing distutils.")
Oct 11 12:43:48 haproxy systemd[1]: Started The Salt Minion.
Oct 11 12:43:48 haproxy salt-minion[842]: [ERROR   ] 'EntryPoints' object has no attribute 'items'
Oct 11 12:43:48 haproxy salt-minion[842]: Traceback (most recent call last):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 212, in parse_args
Oct 11 12:43:48 haproxy salt-minion[842]:     mixin_after_parsed_func(self)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 905, in __setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     salt._logging.setup_logging()
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 971, in setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     setup_extended_logging(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 878, in setup_extended_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     providers = salt.loader.log_handlers(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 857, in log_handlers
Oct 11 12:43:48 haproxy salt-minion[842]:     _module_dirs(
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 153, in _module_dirs
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point in entrypoints.iter_entry_points("salt.loader"):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
Oct 11 12:43:48 haproxy salt-minion[842]:     return f(*args, **kwargs)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 41, in iter_entry_points
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point_group, entry_points_list in entry_points.items():
Oct 11 12:43:48 haproxy salt-minion[842]: AttributeError: 'EntryPoints' object has no attribute 'items'
Oct 11 12:43:48 haproxy salt-minion[842]: Usage: salt-minion [options]
Oct 11 12:43:48 haproxy salt-minion[842]: [ERROR   ] 'EntryPoints' object has no attribute 'items'
Oct 11 12:43:48 haproxy salt-minion[842]: Traceback (most recent call last):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 212, in parse_args
Oct 11 12:43:48 haproxy salt-minion[842]:     mixin_after_parsed_func(self)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 905, in __setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     salt._logging.setup_logging()
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 971, in setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     setup_extended_logging(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 878, in setup_extended_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     providers = salt.loader.log_handlers(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 857, in log_handlers
Oct 11 12:43:48 haproxy salt-minion[842]:     _module_dirs(
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 153, in _module_dirs
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point in entrypoints.iter_entry_points("salt.loader"):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
Oct 11 12:43:48 haproxy salt-minion[842]:     return f(*args, **kwargs)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 41, in iter_entry_points
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point_group, entry_points_list in entry_points.items():
Oct 11 12:43:48 haproxy salt-minion[842]: AttributeError: 'EntryPoints' object has no attribute 'items'
Oct 11 12:43:48 haproxy salt-minion[842]: salt-minion: error: Error while processing <function LogLevelMixIn.__setup_logging at 0x7f6173ccfac0>: Traceback (most recent call last):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 212, in parse_args
Oct 11 12:43:48 haproxy salt-minion[842]:     mixin_after_parsed_func(self)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/parsers.py", line 905, in __setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     salt._logging.setup_logging()
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 971, in setup_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     setup_extended_logging(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/_logging/impl.py", line 878, in setup_extended_logging
Oct 11 12:43:48 haproxy salt-minion[842]:     providers = salt.loader.log_handlers(opts)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 857, in log_handlers
Oct 11 12:43:48 haproxy salt-minion[842]:     _module_dirs(
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/loader/__init__.py", line 153, in _module_dirs
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point in entrypoints.iter_entry_points("salt.loader"):
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 29, in _wrapped
Oct 11 12:43:48 haproxy salt-minion[842]:     return f(*args, **kwargs)
Oct 11 12:43:48 haproxy salt-minion[842]:   File "/usr/lib/python3.10/site-packages/salt/utils/entrypoints.py", line 41, in iter_entry_points
Oct 11 12:43:48 haproxy salt-minion[842]:     for entry_point_group, entry_points_list in entry_points.items():
Oct 11 12:43:48 haproxy salt-minion[842]: AttributeError: 'EntryPoints' object has no attribute 'items'
Oct 11 12:43:53 haproxy systemd[1]: salt-minion.service: Main process exited, code=exited, status=64/USAGE
Oct 11 12:43:53 haproxy systemd[1]: salt-minion.service: Failed with result 'exit-code'.
```

Downgrade works (if you have the old package still in the pacman cache, otherwise you need to re-download it again first):
```
sudo pacman -U /var/cache/pacman/pkg/python-importlib-metadata-4.9.0-1-any.pkg.tar.zst
sudo systemctl restart salt-minion
```

**Comment by lsh-0** [comment]
Seeing this on Salt 3003.5 + Ubuntu 20.04 too:

```
root@ip-10-0-2-153:/home/ubuntu# salt-call --versions
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003.5', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 22, in run
    self.parse_args()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 177, in parse_args
    self.print_versions_report()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 246, in print_versions_report
    print("\n".join(version.versions_report()), file=file, flush=True)
  File "/usr/lib/python3/dist-packages/salt/version.py", line 801, in versions_report
    ver_info = versions_information(
  File "/usr/lib/python3/dist-packages/salt/version.py", line 791, in versions_information
    extensions_info = extensions_information()
  File "/usr/lib/python3/dist-packages/salt/version.py", line 767, in extensions_information
    for entry_point in salt.utils.entrypoints.iter_entry_points("salt.loader"):
  File "/usr/lib/python3/dist-packages/salt/utils/entrypoints.py", line 62, in iter_entry_points
    for entry_point_group, entry_points_list in entry_points.items():
AttributeError: 'EntryPoints' object has no attribute 'items'
```
Downgrading `importlib_metadata`:
```
root@ip-10-0-2-153:/home/ubuntu# pip3 install 'importlib_metadata==4.13.0'
Collecting importlib_metadata==4.13.0
  Downloading importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib_metadata==4.13.0) (3.9.0)
Installing collected packages: importlib_metadata
  Attempting uninstall: importlib_metadata
    Found existing installation: importlib-metadata 5.0.0
    Uninstalling importlib-metadata-5.0.0:
      Successfully uninstalled importlib-metadata-5.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed importlib_metadata-4.13.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package

(I know, I know)

After downgrade:
```

root@ip-10-0-2-153:/home/ubuntu# salt-call --versions
Salt Version:
          Salt: 3003.5
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: 4.1.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Mar 15 2022, 12:22:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.11.0-1028-aws
        system: Linux
       version: Ubuntu 20.04 focal
```

**Comment by vdloo** [comment]
I can confirm this issue on Debian Buster as well

**Comment by j5k** [comment]
Since salt is broken and a fix is already merged, can you release a new hotfix/minor version?

**Comment by hartwork** [comment]
For the record, the post-3005.1 fix used in Arch and Gentoo is commit b676e6338a7c094cb3335d11f851ac0e12222017 .

**Comment by hartwork** [comment]
…but patch b676e6338a7c094cb3335d11f851ac0e12222017 seems broken @MKLeb @Ch3LL:

```console
# salt-ssh '*' state.apply setup
/usr/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
host123:
    ----------
    _error:
        Failed to return clean data
    retcode:
        64
    stderr:
        Usage: salt-call [options] <function> [arguments]
        
        salt-call: error: Error while processing <function LogLevelMixIn.__setup_logging at 0x7f0cf7669cf0>: Traceback (most recent call last):
          File "/var/tmp/.root_590ab3_salt/pyall/salt/utils/parsers.py", line 212, in parse_args
            mixin_after_parsed_func(self)
          File "/var/tmp/.root_590ab3_salt/pyall/salt/utils/parsers.py", line 905, in __setup_logging
            salt._logging.setup_logging()
          File "/var/tmp/.root_590ab3_salt/pyall/salt/_logging/impl.py", line 971, in setup_logging
            setup_extended_logging(opts)
          File "/var/tmp/.root_590ab3_salt/pyall/salt/_logging/impl.py", line 878, in setup_extended_logging
            providers = salt.loader.log_handlers(opts)
          File "/var/tmp/.root_590ab3_salt/pyall/salt/loader/__init__.py", line 857, in log_handlers
            _module_dirs(
          File "/var/tmp/.root_590ab3_salt/pyall/salt/loader/__init__.py", line 153, in _module_dirs
            for entry_point in entrypoints.iter_entry_points("salt.loader"):
          File "/var/tmp/.root_590ab3_salt/pyall/salt/utils/entrypoints.py", line 29, in _wrapped
            return f(*args, **kwargs)
          File "/var/tmp/.root_590ab3_salt/pyall/salt/utils/entrypoints.py", line 51, in iter_entry_points
            for entry_point in entry_points.select(group=group):
        AttributeError: 'dict' object has no attribute 'select'
    stdout:
```

This is with importlib_metadata 5.0.0

**Comment by MKLeb** [comment]
Hi @hartwork, the `importlib_metadata>=5.0.0` fix was pushed in this PR: https://github.com/saltstack/salt/pull/62854.  The commit you reference is part of that PR, but there was at least one iteration beyond that that pushed the fix over the line.

**Comment by hartwork** [comment]
> Hi @hartwork, the `importlib_metadata>=5.0.0` fix was pushed in this PR: #62854. The commit you reference is part of that PR, but there was at least one iteration beyond that that pushed the fix over the line.

Hi @MKLeb, thanks for bringing this^^ to light.  I'm not sure why both Arch and Gentoo chose to only cherry pick an insufficient subset of #62854 but maybe that is an indicator that a new upstream Salt release 3005.2 would help to get a consistent fix to packaging downstreams.  After all, the ideal downstream patch count is zero.

CC @Foxboron (for Arch) and @chutz (for Gentoo)

**Comment by j5k** [comment]
I would welcome 3005.2

**Comment by categulario** [comment]
I hit this problem trying to apply a state on a minion with ubuntu 20.04 that ships with python3-importlib-metadata version `1.5.0-1`. I'm using salt `3005.1-1` on a host with manjaro and using `salt-ssh`. Manually upgrading the server to importlib_metadata 4.6.4 worked, but definitely not a good solution.

**Comment by mikafouenski** [comment]
Hello :wave:,

Quick workaround. On Archlinux the last working version is `3004.1`.
Downgrading to this version fixed the problems for me.
`sudo pacman -U /var/cache/pacman/pkg/salt-3004.1-3-any.pkg.tar.zst` (I still had it in my cache folder)

**Comment by einsiedlerkrebs** [comment]
... For using salt on Archlinux I can recommend the [downgrade](https://aur.archlinux.org/packages/downgrade) script. In case someone cleans the package cache regularly.

**Comment by edlitmus** [comment]
This issue exists on Ubuntu 20.04 as well.

**Comment by Foxboron** [comment]
@hartwork Sorry, I'll backport the patches like suse did when I find the time :) Forgot this issue.

**Comment by hartwork** [comment]
@Foxboron any news?

**Comment by hartwork** [comment]
@Foxboron PS: Here's the replacement patch I just applied for Gentoo:
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/salt/files/salt-3005.1-importlib-metadata-5-r1.patch

**Comment by Foxboron** [comment]
Been a busy few weeks :) Patched now.
https://github.com/Foxboron/archlinux-pkgbuilds/commit/045bd1404c9383d4b37ec4ac5c7da2b168b87c35

**Comment by hartwork** [comment]
@Foxboron excellent! :+1:

**Comment by N0K0** [comment]
Same issue found with my Ubuntu 22.04 box. Running salt 3005.1, and _somehow_ I've ended up with importlib_metadata 6.0. Downgrade worked just fine (knock on wood).

Makes me wonder how I ended up with such a new version, as the Ubuntu manifest lists 4.6.4, and the only tool I have directly installed as an OS dependency is poetry that also targets `>=4.4`..

**Comment by MKLeb** [comment]
Salt 3006.0rc1 is out and should fix this issue.  We welcome your feedback from testing this RC, and you can report back here if you are still seeing this problem come up.  To install the RC, refer to this guide: https://docs.saltproject.io/salt/install-guide/en/latest/topics/release-candidate.html
