### ISSUE TITLE
x509.certificate_managed - AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#55018]
### Description of Issue
x509.certificate_managed  does not work anymore on upstream, with 2018.3.4 I was able to patch the x509.py to made it works, but with 2019.2.0 and upstream version it does not work

```
          ID: /etc/pki/prometheus.ssllab.com.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/x509.py", line 502, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/modules/x509.py", line 1399, in create_certificate
                  timeout=30
                File "/usr/lib/python3.6/site-packages/salt/modules/publish.py", line 263, in publish
                  via_master=via_master)
                File "/usr/lib/python3.6/site-packages/salt/modules/publish.py", line 143, in _publish
                  returned_minions = set(ret.keys())
              AttributeError: 'str' object has no attribute 'keys'
```

### Versions Report
 
- Salt Minion
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.1.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

**Comment by Poil** [comment]
I just see that my master rollback on Python 2.7 when installing the 2019.2.0, I switch it back to python 3 ...

**Comment by Poil** [comment]
It was that, x509.py not working with Python 2.7 on Master side
