### ISSUE TITLE
When upgrading from 2015.8.10 to 2016.3.0 on centos7/redhat7 I have to restart the salt-minion twice 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#33516]
### Description of Issue/Question
When upgrading the salt-minion from 2015.8.10 to 2016.3.0 I have to restart the salt-minion twice in order for it to communicate back with the master.

### Setup
1. 2015.8.10 minion connected to a master

### Steps to Reproduce Issue
1. Install 2015.8.10
2. point the local minion to the master
3. veryify you can communicate with minion:

```
[root@ip-10-181-53-46 ~]# salt '*' test.version
ip-10-89-12-242.eu-west-1.compute.internal:
    2015.8.10
```

4.. upgrade to 2016.3.0
yum update salt-minion
7. restart processes;
[root@ip-10-181-53-46 ~]# service salt-minion restart

8. the minion shuts down

```
2016-05-25 21:04:52,364 [salt.cli.daemons ][INFO    ][11430] Setting up the Salt Minion "ch3ll-redhat7"
2016-05-25 21:04:52,364 [salt.cli.daemons ][ERROR   ][11430] Salt minion is already running. Exiting.
None
2016-05-25 21:04:52,365 [salt.cli.daemons ][INFO    ][11430] The salt minion is shutting down..
2016-05-25 21:04:52,365 [salt.cli.daemons ][INFO    ][11430] The Salt Minion is shut down
2016-05-25 21:04:56,116 [salt.scripts     ][ERROR   ][10488] Minion process encountered exception: [Errno 3] No such process
```

cannot communicate with the master due to the minion shutting down. 
I have to restart the minion process twice

### Versions Report

```
[root@ch3ll-redhat7 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.18.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by deuscapturus** [comment]
I'm in a terrible place after updating my 2015.8.10 minions to 2016.3.  The first restart didn't work, and I was unable to perform a second restart remotely from the master.

Upon looking I couldn't find an official minion upgrade procedure.  So I did what has worked in the past `pkg.install salt-minion` then `service.restart salt-minion`.  What should we be doing?  

I now need to manually recover all of these minions.  :sob: 
```
[root@salt-master]# salt 'DOCKER1' service.restart salt-minion
DOCKER1:
    Passed invalid arguments to service.restart: __init__() got an unexpected keyword argument 'timeout'
    
        Restart the specified service with systemd
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' service.restart <service name>
```

```
[root@salt-master]# salt 'DOCKER1' cmd.run 'systemctl restart salt-minion'
DOCKER1:
    Passed invalid arguments to cmd.run: __init__() got an unexpected keyword argument 'bg'
    
        Execute the passed command and return the output as a string
    
        Note that ``env`` represents the environment variables for the command, and
        should be formatted as a dict, or a YAML string which resolves to a dict.
    
        :param str cmd: The command to run. ex: ``ls -lart /home``
    
        :param str cwd: The current working directory to execute the command in,
          defaults to ``/root`` (``C:\`` in windows)
```

**Comment by babilen** [comment]
https://docs.saltstack.com/en/latest/ref/roster/all/salt.roster.cache.html#module-salt.roster.cache might come in handy to restart minions with salt-ssh from the master.

**Comment by Ch3LL** [comment]
@deuscapturus as @babilen stated you can use salt-ssh to restart the minion. 

Also there is some docs on how to handle an upgrade [here](https://docs.saltstack.com/en/latest/faq.html#linux-unix) as well.

**Comment by c4t3l** [comment]
In my case, a workaround is to utilize the 'at' command similarly to what is described [here](https://docs.saltstack.com/en/latest/faq.html#linux-unix)

cmd.run:
  - name: |
      echo systemctl restart salt-minion | at now + 1 minute
      echo systemctl restart salt-minion | at now + 2 minutes

pkg.latest:
  - name: salt-minion
  - order: last

**Comment by sjmh** [comment]
Does this happen on RHEL5/RHEL6?  We plan on upgrading to 2016.3, but this would be a big blocker for us doing that.

**Comment by c4t3l** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I've seen this behavior in rhel6.  My workaround was to issue two restarts at 2 and 3 minutes from state call using the at command via cmd state.  I lost connection with the rhel6 hosts but they successfully updated after 3 minutes.

On July 5, 2016 6:17:04 PM CDT, sjmh <notifications@github.com> wrote:
>Does this happen on RHEL5/RHEL6?  We plan on upgrading to 2016.3, but
>this would be a big blocker for us doing that.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/issues/33516#issuecomment-230630582

- --
Robert
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJcBAEBCgBGBQJXfEaSPxxSb2JlcnQgQ2FsbGljb3R0ZSAoQ29tbXVuaWNhdGlv
bnMgS2V5KSA8cm9iZXJ0QGNhbGxpY290dGUub3JnPgAKCRAbiovJuj4EHCqsD/9t
/fyL7VS5KiSzPHN9txMQ2E4qtcoTDqWXb7JeojBe54kUQfAo0bQ+cFyl5QOo2ojU
xE0Dr0xlPA0JIwBf9JJnAnwXtV6tvNX3j6mT0YwEO9B/0VVCnpMyE/GLjJUvvFEG
dILYnRAqMpcySx/XxLSBPFhpyoiD04gNJNXT5DDgYO2bEklgpzu3PGLe3jkaQ34n
W+DlI60J/xpq5dc+IemUaLRlqrfvcwkWCPYNtw1BKRhmDOHsuXsXVvOFzS4/FAg3
2MXT945qcFjzvkuKWSt/cUA2JxCSiUdWUA3g2SEXQUi7nHaiu+Ze+qjp6YG+Z8jG
abjkL+19X1x92vrUyuOUPRf15gAhxW+oUEsT5H06r5Pqtr6tNkFTtrMM185ZEcli
7ef8BAX3um+8ji8H28imcV6jgrDYmhcg0IyA0x5Ju3q4qzwSXAPEdpkoWUEApIUT
kUwz21CnMvXW4OEZfaB1QAXW6h7V+w40Ksm1ohcJIAKVv7n6GjlPdgQrnhmbw7wr
C5KXF7cJTfZufQCdDaZBvjwhainzQ0OixVCXUKOjF9BD4hZ1ekwAWlhOSwRN0z5L
2bA7ibN2gnzjgG4AfD7LsNUe4atGHfcLbumMSmJKNkci4GlF+ZzBJdDC+jX+XOqm
eCtJm8rAJR46ChXJ/CPqYbIRuenVo+ogpM/tlxsSFQ==
=Xz7g
-----END PGP SIGNATURE-----

**Comment by meggiebot** [comment]
ZD-849

**Comment by plastikos** [comment]
Have any of you tried `minion.kill` or `minion.restart`?

**Comment by meggiebot** [comment]
ZD-828

**Comment by meggiebot** [comment]
We believe this is caused by: https://github.com/saltstack/salt/issues/33803

Let's chat early next week about how we want to resolve this

**Comment by meggiebot** [comment]
Possibly related to: https://github.com/saltstack/salt/issues/22973

**Comment by deuscapturus** [comment]
Another workaround for those running a newer version of systemd.
```
salt-minion:
  pkg.latest:
    - name: salt-minion
    - order: last
  cmd.run:
    - name: systemd-run --on-active=30 /usr/bin/systemctl restart salt-minion ; systemd-run --on-active=40 /usr/bin/systemctl restart salt-minion
    - prereq:
      - pkg: salt-minion
```

**Comment by terminalmage** [comment]
Resolved by #35510, also depends on https://github.com/saltstack/salt-pack/issues/131 on the packaging end.
