### PR TITLE
Fix AttributeError on closed IPCClient (#68993)

### LINKED ISSUE #68993: [Bug]: 3006.24 regression: AttributeError: 'NoneType' object has no attribute 'set_result' in transport/ipc.py
### What happened?

Possibly related to 68992

Description of Bug:
After upgrading from 3006.23 to 3006.24 (Sulfur), salt-call consistently throws an AttributeError during the IPC handshake, even though the command itself (e.g., test.ping) returns the correct value.

Traceback:
[ERROR ] Future <salt.ext.tornado.concurrent.Future object at 0x7f35c5fde830> exception was never retrieved: Traceback (most recent call last):
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/ipc.py", line 333, in _connect
self._connecting_future.set_result(True)
AttributeError: 'NoneType' object has no attribute 'set_result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/gen.py", line 1070, in run
yielded = self.gen.send(value)
File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/ipc.py", line 343, in _connect
self._connecting_future.set_exception(e)
AttributeError: 'NoneType' object has no attribute 'set_exception'

Environment:

Salt Version: 3006.24

Python Version: 3.10.x

OS: Debian (Standard Saltstack Repo)

Notes: This appears to be a race condition in the IPC transport layer. Using salt-call --local bypasses the issue, confirming it is isolated to the Minion-to-CLI communication.

Steps to Reproduce:

Upgrade to 3006.24.

Run salt-call test.ping.

Observe the traceback before the True response.

Rolling back to 3006.23 resolved the issue for our entire fleet. This confirms it’s a regression and not a local environment failure.

### Type of salt install

Official deb

### Major version

3006.x

### What supported OS are you seeing the problem on? Can select multiple. (If bug appears on an unsupported OS, please open a GitHub Discussion instead)

debian-12

### salt --versions-report output

```shell
Salt Version:
          Salt: 3006.24
 
Python Version:
        Python: 3.10.19 (main, Feb 17 2026, 23:32:03) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 2.0.0
      cherrypy: 18.10.0
  cryptography: 46.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.22.4
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-44-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```

### PR DESCRIPTION
**Pull request by SAY-5**
Fixes #68993.

When `IPCClient.close()` runs while `_connect()` is still pending, the coroutine reaches `set_result`/`set_exception` after `_connecting_future` has been cleared to `None`, raising `AttributeError`. Guard both call sites with a None-check.

### CODE REVIEW

**Comment by SAY-5** [comment]
Retargeted to 3006.x per @dwoz — the fix still applies (ipc.py exists; closed-state branch unchanged). Verified locally.

**Review by dwoz — APPROVED** [review]
