### ISSUE TITLE
random salt-call authentication error

### ISSUE THREAD

**Issue by soodr** [saltstack/salt#26600]
Getting the following stack trace with a salt-call or salt * on master with an authenticated minion. The error is random.
The Salt master needs to be restarted to fix it.

Minion :
```yaml
           Salt: 2015.5.1
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.6.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
Stack Trace :
```python-traceback
C:\Users\Administrator>c:\salt\salt-call.bat state.sls newrelic
[ERROR   ] Got a bad pillar from master, type NoneType, expecting dict: None
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
AuthenticationError: message authentication failed
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 645, in sls
    st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 3028, in __init__
    BaseHighState.__init__(self, opts)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2206, in __init__
    self.opts = self.__gen_opts(opts)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2233, in __gen_opts
    mopts = self.client.master_opts()
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 1193, in master_
opts
    return self.channel.send(load)
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 314, in
send
    return self._crypted_transfer(load, tries, timeout)
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 305, in
_crypted_transfer
    return _do_transfer()
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 299, in
_do_transfer
    data = self.auth.crypticle.loads(data)
  File "c:\salt\bin\lib\site-packages\salt\crypt.py", line 841, in loads
    data = self.decrypt(data)
  File "c:\salt\bin\lib\site-packages\salt\crypt.py", line 818, in decrypt
    raise AuthenticationError('message authentication failed')
AuthenticationError: message authentication failed
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\state.py", line 645, in sls
    st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 3028, in __init__
    BaseHighState.__init__(self, opts)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2206, in __init__
    self.opts = self.__gen_opts(opts)
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 2233, in __gen_opts
    mopts = self.client.master_opts()
  File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 1193, in master_
opts
    return self.channel.send(load)
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 314, in
send
    return self._crypted_transfer(load, tries, timeout)
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 305, in
_crypted_transfer
    return _do_transfer()
  File "c:\salt\bin\lib\site-packages\salt\transport\__init__.py", line 299, in
_do_transfer
    data = self.auth.crypticle.loads(data)
  File "c:\salt\bin\lib\site-packages\salt\crypt.py", line 841, in loads
    data = self.decrypt(data)
  File "c:\salt\bin\lib\site-packages\salt\crypt.py", line 818, in decrypt
    raise AuthenticationError('message authentication failed')
salt.exceptions.AuthenticationError: message authentication failed
```
Master :
```yaml
           Salt: 2015.2.0rc1
         Python: 2.7.8 (default, Sep 24 2014, 11:50:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: 1.4.2
         PyYAML: 3.11
          ioflo: 1.2.1
          PyZMQ: 14.5.0
           RAET: 0.6.3
            ZMQ: 4.0.5
           Mako: 1.0.0
```

**Comment by jfindlay** [comment]
@soodr, thanks for the report.  Is it possible to reproduce this situation with a master that is running 2015.5.2 or 2015.5.3?

**Comment by soodr** [comment]
@jfindlay : chanced to update the instance to 2015.5.3. Will monitor and revert in a couple of weeks.

**Comment by soodr** [comment]
Noticed a master log entry when invoking a remote salt-run through the wheel client\:

208.185.155.58 - - [28/Aug/2015:14:04:39] "POST / HTTP/1.1" 200 16 "" "Python-urllib/2.6"
[INFO    ] 208.185.155.58 - - [28/Aug/2015:14:04:39] "POST / HTTP/1.1" 200 16 "" "Python-urllib/2.6"
[ERROR   ] Exception need more than 1 value to unpack occurred in file server update

**Comment by jfindlay** [comment]
@soodr, thanks for the extra info.  Is there more context to the log statements you posted, like a python traceback?

**Comment by soodr** [comment]
Looks like its related to s3 updates from AWS \:
```
[DEBUG   ] "HEAD /TIB_sfire_server_1.0.0_win.zip%2B HTTP/1.1" 200 0
[DEBUG   ] S3 Response Status Code: 200
[ERROR   ] Exception need more than 1 value to unpack occurred in file server up
date
Traceback (most recent call last):
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/daemons/masterapi.py", lin
e 238, in fileserver_update
    fileserver.update()
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/fileserver/__init__.py", l
ine 407, in update
    self.servers[fstr]()
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line
115, in update
    _get_file_from_s3(metadata, saltenv, bucket, file_path, cached_file_path)
  File "/pyvenv/salt/lib/python2.7/site-packages/salt/fileserver/s3fs.py", line
625, in _get_file_from_s3
    name, value = header.split(':', 1)
ValueError: need more than 1 value to unpack
```

**Comment by jfindlay** [comment]
You may be running into an issue fixed by #25420.  Reply here though if you are able to reproduce the original error.

**Comment by jfindlay** [comment]
Of course only now do I see `Got a bad pillar from master, type NoneType, expecting dict: None`.  This is very likely a duplicate of #25579.  I'm going to close this in favor of that.  Regarding the s3 error, that should be fixed in 2015.5.6.

**Comment by soodr** [comment]
The error persists after upgrading the Salt version on master to 2015.5.5

**Comment by jfindlay** [comment]
@soodr, thanks for verifying.  Will you open a new issue for that?

**Comment by jfindlay** [comment]
@soodr, thanks for verifying.  Are you still seeing the s3 error?

**Comment by soodr** [comment]
The s3 error got fixed. Thanks.

**Comment by wt** [comment]
This seems to still be occurring on 2015.5.5. Here's a backtrace collected on an Amazon Linux machine:

```
AttributeError: 'module' object has no attribute 'exceptions'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 309, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 538, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2977, in call_highstate
    self.serial.dump(high, fp_)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 174, in dump
    fn_.write(self.dumps(msg))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps
    except (OverflowError, msgpack.exceptions.PackValueError):
AttributeError: 'module' object has no attribute 'exceptions'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 227, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 69, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 236, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 309, in apply_
    return highstate(**kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 538, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2977, in call_highstate
    self.serial.dump(high, fp_)
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 174, in dump
    fn_.write(self.dumps(msg))
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 122, in dumps
    except (OverflowError, msgpack.exceptions.PackValueError):
AttributeError: 'module' object has no attribute 'exceptions'
```

**Comment by wt** [comment]
Is there a workaround for this issue? I have a number of machines just crashing due to this.

**Comment by wt** [comment]
I updated python-msgpack manually on my system to fix this. I think you need a versioned dep in the rpm in epel6 for python-msgpack 0.4.6-1.el6.
