### ISSUE TITLE
Exception when using cp.push

### ISSUE THREAD

**Issue by giany** [saltstack/salt#35984]
I try to copy a file from minion to master using:

```salt -l debug 'minion' cp.push /etc/issue```

And I get the following error: 
```    
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/usr/lib/python2.7/posixpath.py", line 92, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'
```

Problem seems to be with the latest release 2016.3.3 , if I revert to 2016.3.2 it works properly.

Version used on minion:
```
dpkg -l | grep salt

ii  salt-common                    2016.3.3+ds-1             all          shared libraries that salt requires for all packages
ii  salt-minion                    2016.3.3+ds-1             all          client package for salt, the distributed remote execution system
```

**Comment by Ch3LL** [comment]
@giany i am able to replicate this. git bisect shows 81c4d136c5e3ac7b8cc208e0a9079c7ebb018b0c as the first bad commit. We will need to get this fixed up thanks

**Comment by scavara** [comment]
Not sure is the following useful for you, or not but I have the same problem on the bit older version installed from Debian Jessie backports:
 ```
# dpkg -l | grep salt-master && salt-call --versions-report | grep -i salt
ii  salt-master                        2016.3.0+ds-1~bpo8+1         <snip>
Salt Version:
           Salt: 2016.3.0
```

```
 # salt 'minion' cp.push /etc/hosts
minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/opt/salt/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/opt/salt/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/opt/salt/lib/python2.7/site-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/opt/salt/lib/python2.7/posixpath.py", line 83, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'
```

**Comment by cachedout** [comment]
Fixed here: https://github.com/saltstack/salt/pull/36136

**Comment by vchav73** [comment]
Can anyone comment on when the fix will be in the yum repo? #36287 mentions that the fix will be in the 2016.3.4 release. Just wondering if it'll be days, weeks, months? We're effected by this and may downgrade to 2016.3.2 if it's going to be a while.

Thanks.

**Comment by Ch3LL** [comment]
@vchav73 october is the current goal to get 2016.3.4 out by October, although I am not certain of the exact date. In the meantime you can downgrade to 2016.3.2 or possibly push the fix as a custom module by putting it in /srv/salt/_modules/ and then running `salt '*' saltutil.refresh_modules`

**Comment by vchav73** [comment]
Thanks for the info. One more question: Do all the minions as well as the master need to be downgraded or just the master?

**Comment by Ch3LL** [comment]
I believe this is a minion side module and it looks like the fix is related to how the file path on the minion you want to copy up to the master is handled so minions need to updated.
