### PR TITLE
Fix salt-cloud AttributeError by importing salt.minion (#69281)

### LINKED ISSUE #69281: [Bug]: salt-cloud 3008.0 fails to run at all
### What happened?

Trying to run salt-cloud in version 3008.0 yields the following error:

```
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 12, in <module>
    sys.exit(salt_cloud())
             ~~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/scripts.py", line 556, in salt_cloud
    client.run()
    ~~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/cli.py", line 73, in run
    mapper = salt.cloud.Map(self.config)
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/__init__.py", line 1622, in __init__
    self.rendered_map = self.read()
                        ~~~~~~~~~^^
  File "/opt/saltstack/salt/lib/python3.14/site-packages/salt/cloud/__init__.py", line 1741, in read
    self.minion = salt.minion.MasterMinion(local_minion_opts)
                  ^^^^^^^^^^^
AttributeError: module 'salt' has no attribute 'minion'
```

After some research, we found that an import is needed in the file `salt/cloud/__init__.py`:
```
import salt.minion
```

Once we added that import `salt-cloud` runs correctly again.

I checked the history of `salt/cloud/__init__.py` but found no recent changes that might explain this. I have no relevant python knowledge to understand why it was working in salt 3007.14 and no longer works in 3008.0 when the nothing relevant appears to have changed since. Perhaps it is something related to the python version (3.10 -> 3.14)?

### Type of salt install

Official deb

### Major version

3008.x

### What supported OS are you seeing the problem on? Can select multiple. (If bug appears on an unsupported OS, please open a GitHub Discussion instead)

ubuntu-24.04

### salt --versions-report output

```shell
Salt Version:
          Salt: 3008.0
 
Python Version:
        Python: 3.14.5 (main, May 12 2026, 03:56:57) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 2.0.0
      cherrypy: 18.10.0
  cryptography: 46.0.7
      dateutil: 2.9.0.post0
     docker-py: Not Installed
         gitdb: 4.0.12
     gitpython: 3.1.50
        Jinja2: 3.1.6
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.1.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.0
     pycparser: 3.00
      pycrypto: Not Installed
  pycryptodome: 3.23.0
        pygit2: Not Installed
  python-gnupg: 0.5.6
        PyYAML: 6.0.3
         PyZMQ: 27.1.0
        relenv: 0.22.11
         smmap: 5.0.2
       timelib: 0.3.0
       Tornado: 6.5.5
           ZMQ: 4.3.5
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: ubuntu 24.04.4 noble
        locale: utf-8
       machine: x86_64
       release: 6.17.0-29-generic
        system: Linux
       version: Ubuntu 24.04.4 noble
```

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Adds an explicit `import salt.minion` to `salt/cloud/__init__.py` so salt-cloud doesn't crash at startup.

### What issues does this PR fix or reference?

Fixes #69281

### Previous Behavior

`salt.cloud.Map.__init__` references `salt.minion.MasterMinion` but the module is never imported. On 3007.x the symbol was incidentally populated by other startup-time imports; on 3008.0 the load order changed and salt-cloud crashes immediately on any command that constructs a Map.

### New Behavior

`salt.minion` is imported explicitly. salt-cloud starts normally.

### Merge requirements satisfied?

- [ ] Docs
- [x] Changelog
- [x] Tests written/updated

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by dwoz — COMMENTED** [review]
Please add a test that actually invokes the salt-cloud command.

**Comment by dwoz** [comment]
Added functional test `test_map_file_runs_without_attribute_error` in `tests/pytests/functional/cli/test_salt_cloud.py` that invokes `salt-cloud -m <empty mapfile>` via the `salt_cloud_cli` fixture. Verified locally: fails with `AttributeError: module 'salt' has no attribute 'minion'` when the import is removed, passes with the fix.
