### ISSUE TITLE
ssl verification fails on Windows

### ISSUE THREAD

**Issue by highlyunavailable** [saltstack/salt#19969]
The s3.get module fails on Windows with an SSL error that seems to be related to a trust issue and/or certs not being available.

Command: `salt-call s3.get mybucket mykey/myfile.zip`
Versions report:
```
           Salt: 2014.7.1
         Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.1.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

Log output:
```
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 24
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/my-role HTTP/1.1" 200 930
[DEBUG   ] CanonicalizedResource: /mybucket/mykey/myfile.zip
[DEBUG   ] x-amz-security-token
[DEBUG   ] CanonicalizedAmzHeaders: x-amz-security-token:SNIP
[DEBUG   ] String To Sign::
GET

text/plain
Thu, 22 Jan 2015 21:10:24 GMT
x-amz-security-token:SNIP
/mybucket/mykey/myfile.zip
[DEBUG   ] S3 Request: https://mybucket.s3.amazonaws.com/mykey/myfile.zip
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: AWS SNIP
[INFO    ] Starting new HTTPS connection (1): mybucket.s3.amazonaws.com
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 123, in salt_call
  File "salt/cli/__init__.py", line 420, in run
  File "salt/cli/caller.py", line 225, in run
  File "salt/cli/caller.py", line 129, in call
  File "salt/modules/s3.py", line 154, in get
  File "salt/utils/s3.py", line 155, in query
  File "requests/api.py", line 44, in request
  File "requests/sessions.py", line 456, in request
  File "requests/sessions.py", line 559, in send
  File "requests/adapters.py", line 382, in send
SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 726, in <module>
  File "__main__.py", line 332, in bootstrap
  File "__main__.py", line 359, in chainload
  File "__main__.py", line 715, in _chainload
  File "__main__.py", line 128, in <module>
  File "__main__salt-call__.py", line 14, in <module>
  File "salt/scripts.py", line 123, in salt_call
  File "salt/cli/__init__.py", line 420, in run
  File "salt/cli/caller.py", line 225, in run
  File "salt/cli/caller.py", line 129, in call
  File "salt/modules/s3.py", line 154, in get
  File "salt/utils/s3.py", line 155, in query
  File "requests/api.py", line 44, in request
  File "requests/sessions.py", line 456, in request
  File "requests/sessions.py", line 559, in send
  File "requests/adapters.py", line 382, in send
requests.exceptions.SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509certificate routines:X509_load_cert_crl_file:system lib
```

**Comment by rallytime** [comment]
Good catch, as usual @highlyunavailable! Thanks for the report.

**Comment by andrejohansson** [comment]
This is true for me too, I have win_repo packages with installers located on Azure storage (https). They worked fine previously but on the latest version of the minion (2014.7.0) on Windows 8.1 I get the same error.

```
----------
          ID: 7zip
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "salt/state.py", line 1533, in call
                File "salt/states/pkg.py", line 831, in installed
                File "salt/modules/win_pkg.py", line 558, in install
                File "salt/modules/cp.py", line 328, in cache_file
                File "salt/fileclient.py", line 149, in cache_file
                File "salt/fileclient.py", line 591, in get_url
                File "requests/api.py", line 55, in get
                File "requests/api.py", line 44, in request
                File "requests/sessions.py", line 456, in request
                File "requests/sessions.py", line 559, in send
                File "requests/adapters.py", line 382, in send
              SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
     Started: 14:06:44.730000
    Duration: 2744.0 ms
     Changes:
```

**Comment by techhat** [comment]
@highlyunavailable or @andrejohansson, would one of you please check the `certs.py` file belonging to requests in Windows, and see what path (if any) the `where()` function returns?

It's important to check this in Windows itself, as this file gets patched individually on different distributions.

**Comment by highlyunavailable** [comment]
@techhat It returns only the string `C:\salt\salt-2014.7.1.win-amd64\library.zip\requests\cacert.pem` which doesn't appear to exist in the zip file.

**Comment by techhat** [comment]
Thanks @highlyunavailable. There's a couple of downloads for that file at http://curl.haxx.se/docs/caextract.html . Would you please drop the cacert.pem in there and see if it works? If so, we'll have to figure out how we're going to handle distributing that file.

Ping @UtahDave.

**Comment by highlyunavailable** [comment]
That doesn't work - I would guess the C API portion can't hit the pem that lives inside the zip file.

If I extract the requests directory from the zip file and drop it in `C:\salt\salt-2014.7.1.win-amd64\requests`, then put the cacert.pem file in there, the error changes: `requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

It's at least finding the file then, but it has to be on the filesystem, not wrapped in the library.zip file.

**Comment by techhat** [comment]
Thanks @highlyunavailable. I'll see what else I can find.

**Comment by andrejohansson** [comment]
May I suggest two changes to this issue? For one, the title shouldnt be limited to "s3", this bug affects everything that needs ssl verification as far as I can tell. 

Second, since this basically is a blocker for using security (https) at all,,,shouldn't this be a high priority issue?

As a side note, I've tried the same thing as @highlyunavailable with similar results.

**Comment by andrejohansson** [comment]
I fixed this by monkey patching in this way:
1. Delete requests folder in C:\salt\salt-2014.7.1.win-amd64\library.zip
2. Checkout https://github.com/kennethreitz/requests
3. Copy requests folder to C:\salt\salt-2014.7.1.win-amd64\requests
4. Restart salt-minion

Run commands that need ssl!

**Comment by techhat** [comment]
Agreed on both, @andrejohansson, and both are updated. Thank you as well for posting your resolution.

Which branch of the requests repo are you using? Just `master`, I assume? It looks like the git checkout of requests has its own cacert.pem bundle, which is not something that is standard in most distributions of it, so that explains that.

@UtahDave, how is requests currently packaged for Windows?

**Comment by highlyunavailable** [comment]
Huh, that's weird that it did work because I tried installing the requests egg Pypi (https://pypi.python.org/pypi/requests/) and ran into another error, though now that I think about, that one was probably due to the differences in the XML library packaging too. The process was very similar to @andrejohansson 's method though - remove requests from the salt folder and library.zip, then drop the .egg in the Salt libs folder. I didn't have to unzip it though - anything from `requests 2.4.0` onward seems to not have this problem even in .egg format.

**Comment by UtahDave** [comment]
I just tested on our Windows build server and upgrading the requests package seemed to do the trick. Our QA team is now going to test the packages. I'll report here when they're done.

**Comment by techhat** [comment]
You're the man, @UtahDave!

**Comment by andrejohansson** [comment]
super @UtahDave ! Have you thought of making nightly builds of the windows installer public?

**Comment by ciriarte** [comment]
This is great @UtahDave ! Any idea if this fix is included in [v2015.2.0rc1](v2015.2.0rc1)? I was looking at the commit log but couldn't find anything to confirm it.

**Comment by andrejohansson** [comment]
As far as I can tell at least it's not fixed in 2014.7.2 and no windows build i s out for 2015.2.0rc1 right?

**Comment by ssgward** [comment]
@andrejohansson - correct. It's not fixed in 2014.7.2 and there are no Windows packages for 2015.2.0rc1, yet. The fix is something we want to get fixed soon.

**Comment by deuscapturus** [comment]
@UtahDave Any new windows package to fix this?  I'll take it even if it's not fully tested!  Thanks :)

**Comment by UtahDave** [comment]
I'm testing a whole new build system that avoids the problems we've been having with the freezing process. We might have a 64bit rpm you could test tomorrow, maybe.

**Comment by ciriarte** [comment]
Thanks for your hard work, @UtahDave!

**Comment by deuscapturus** [comment]
@UtahDave Thanks!

**Comment by cachedout** [comment]
@twangboy Could you update this issue with the current status please? Thanks.

**Comment by twangboy** [comment]
This seems to be working in the latest 2014.7. It is still a problem in 2015.2.

**Comment by UtahDave** [comment]
This has been fixed by #21960  !!  Yay!

**Comment by mblixter** [comment]
Hi,

I do not see this as being fixed in Salt-Minion-2015.2.0rc2-AMD64-Setup.exe?

I still get a "SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed" error?

Do I need to do something special to make this work using the RC2 installer?

**Comment by ssgward** [comment]
@mblixter are the minion installs upgrades from previous versions or clean installs of the Windows minion?

**Comment by mblixter** [comment]
Hi,

Thanks for the reply.

I figured out what the problem was and I feel a bit stupid:-) 

The certificate for https://docs.saltstack.com/ expired 2015/04/18 so no wonder the error shows.

Tried another site and it worked:-)

**Comment by ssgward** [comment]
Good news. We had that same discussion about the cert expiring and that being the potential problem. Thanks for the update.
