### ISSUE TITLE
x509.certificate_managed does not work with m2crypto >=0.25

### ISSUE THREAD

**Issue by AaronM-Cloudtek** [saltstack/salt#37084]
### Description of Issue/Question

x509.certificate_managed does not work with m2crypto >=0.25 due to missing x509v3_lhash function
### Steps to Reproduce Issue
1. Install m2crypto >=0.25 on minion
2. Invoke x509.certificate_managed state

Result:

```
    ID: /etc/pki/ca.crt
    Function: x509.certificate_managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1652, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 432, in certificate_managed
                  new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1185, in create_certificate
                  ext = _new_extension(name=extname, value=extval, critical=critical, issuer=issuer)
                File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 118, in _new_extension
                  lhash = M2Crypto.m2.x509v3_lhash()                      # pylint: disable=no-member
              AttributeError: 'module' object has no attribute 'x509v3_lhash'
```
### Versions Report

Minion:

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.4.19-1-pve
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

Master:

```
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.4.19-1-pve
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by Ch3LL** [comment]
@AaronM-Cloudtek thanks for the heads up. Looks like we need to add this to the docs and add a check to ensure the user is using the correct version of m2crypto. Thanks

**Comment by rallytime** [comment]
@clinta You might be interested in taking a look at this issue.

**Comment by clinta** [comment]
Interesting. Looks like I need to change the _new_extension function to more closely model the changes here:

https://gitlab.com/m2crypto/m2crypto/merge_requests/66/diffs

I'll have to figure out the best way to make this work with multiple versions of m2crypto.

**Comment by clinta** [comment]
I have a possible fix prepared in https://github.com/clinta/salt/tree/m2crypto-25, just need to test it.

**Comment by clinta** [comment]
@AaronM-Cloudtek would you mind testing by dropping this [file[(https://raw.githubusercontent.com/clinta/salt/m2crypto-25/salt/modules/x509.py) into your external mods directory? I've tested that it doesn't break existing versions of m2crypto, but until a patched version of m2crypto 0.25 is made available for Ubuntu without sslv2 support, I have nowhere in my environment to test 0.25.

**Comment by clinta** [comment]
Okay I've gotten around to doing some testing, fixed a few bugs and certificate generation works on M2Crypto 0.24 and 0.25.1 on fedora. I'll open a PR.

**Comment by rallytime** [comment]
Thanks for filing this @AaronM-Cloudtek. Please give #37578 a try.

**Comment by AaronM-Cloudtek** [comment]
Yes that works great, thanks!
