### ISSUE TITLE
[BUG] Recent regression in `aptpkg`: Failed to configure repo ...': 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by myii** [saltstack/salt#62175]
**Description**

CC: @Ch3LL.

This is the first of two regressions encountered during the Formulas' weekly testing this week (`2022-W24`).

Using git bisect, I've traced it down to this commit: 409072c4314ec8f45c3c7323308b7a57b20d1f6a (#61760).

A specific example of a failure:

```sls
node-package-repo-pkgrepo-managed:
  pkgrepo.managed:
    - comps: main
    - dist: buster
    - file: /etc/apt/sources.list.d/nodesource.list
    - humanname: NodeSource Node.js Repository
    - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - keyserver: keyserver.ubuntu.com
    - name: deb https://deb.nodesource.com/node_16.x buster
    - url: https://deb.nodesource.com/
    - onlyif: True

...


      ID: node-package-repo-pkgrepo-managed
Function: pkgrepo.managed
    Name: deb https://deb.nodesource.com/node_16.x buster
  Result: False
 Comment: Failed to configure repo 'deb https://deb.nodesource.com/node_16.x buster': 'str' object has no attribute 'name'
```

Detailed logs can be checked from the following:

* https://gitlab.com/myii/apt-formula/-/jobs/2592332938#L1052
* https://gitlab.com/myii/carbon-relay-ng-formula/-/jobs/2592312962#L3117
* https://gitlab.com/myii/grafana-formula/-/jobs/2592324572#L1517
* https://gitlab.com/myii/lynis-formula/-/jobs/2592327062#L2685
* https://gitlab.com/myii/node-formula/-/jobs/2592330826#L1365
* https://gitlab.com/myii/openvpn-formula/-/jobs/2592333965#L4415
* https://gitlab.com/myii/php-formula/-/jobs/2592338375#L3219
* https://gitlab.com/myii/rabbitmq-formula/-/jobs/2592335615#L10220
* https://gitlab.com/myii/rspamd-formula/-/jobs/2592337850#L1916
* https://gitlab.com/myii/varnish-formula/-/jobs/2592349324#L1354

**Setup**
Kitchen CI for each of the formula repos above.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run Kitchen testing for any of the formulas mentioned above.

**Expected behavior**
The `pkgrepo.managed` state shouldn't fail.

**Versions Report**
A current `master` branch installation of Salt (8253b6cef00aaa97db0dac1d46b212c1bf220df9).

**Additional context**
I have a fix that I will propose here shortly.  I've rebuilt our `master` images with it and all jobs are passing again:

* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/myii-ci.2F2022-W24b
