### ISSUE TITLE
cp.push_dir and cp.push fail

### ISSUE THREAD

**Issue by Atvo** [saltstack/salt#36060]
### Description of Issue/Question
I'm trying to use function push_dir from the module cp to push a directory from a minion to the master it returns true but still fails.

This is the message I get when running command
 `salt <minion> cp.push_dir <path>` 

> The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
>         return_data = executor.execute()
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
>         return self.func(*self.args, **self.kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 876, in push_dir
>         ret = push(tmpfile, upload_path=tmpupload_path)
>       File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 799, in push
>         load_path_list = os.path.split(load_path_split_drive)
>       File "/usr/lib64/python2.7/posixpath.py", line 92, in split
>         i = p.rfind('/') + 1
>     AttributeError: 'tuple' object has no attribute 'rfind'

- Specifying upload_path won't help, error message remains the same
- file_recv is set to true on master

Pushing a single file (cp.push) also fails and returns this message:

> The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1332, in _thread_return
>         return_data = executor.execute()
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
>         return self.func(*self.args, **self.kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 799, in push
>         load_path_list = os.path.split(load_path_split_drive)
>       File "/usr/lib64/python2.7/posixpath.py", line 92, in split
>         i = p.rfind('/') + 1
>     AttributeError: 'tuple' object has no attribute 'rfind'

Salt Master version: 2016.3.1
Salt Minion version: 2016.3.3

**Comment by russellballestrini** [comment]
Bump same issue just trying to push a single file.

**Comment by russellballestrini** [comment]
related: Exception when using cp.push #35984

**Comment by jtand** [comment]
@Atvo Thank you for this. It looks like a duplicate that @russellballestrini mentioned. Can you post your results in #35984?

Unless you feel your situation is different, I'd like to keep the discussion for this bug in one place. Thanks!

**Comment by mschiff** [comment]
I can confirm cp.pish ist not working in 2016.3.3. We downgraded to 2016.3.2 as a workaround

**Comment by russellballestrini** [comment]
Did you downgrade the minion, the master, or both?

**Comment by mschiff** [comment]
I had to downgrade both. minion with .3 throws that exception, while .2  minion with .3 master just returns False and also debug output did not tell anything usefull.

**Comment by russellballestrini** [comment]
Thanks I'm going to reproduce tonight.

**Comment by russellballestrini** [comment]
Work around worked for me. Thank you @mschiff

**Comment by cachedout** [comment]
This has been resolved by #36136
