### ISSUE TITLE
ImportError from a custom module

### ISSUE THREAD

**Issue by matdrapeau** [saltstack/salt#16556]
I created 2 custom modules and when trying to import parts from one of them, I get ImportError

```
2014-10-10 16:29:38,652 [salt.loader      ][DEBUG   ] Failed to import module collection, this is most likely NOT a problem:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 911, in load_modules
    ), fn_, path, desc
  File "/var/cache/salt/extmods/modules/collection.py", line 1, in <module>
    from salt.modules.patterns import *
ImportError: No module named patterns
```
Module functions are not accessible.

This bug recently appeared with a pull from git (salt 2014.7.0-792-g91f3326), it used to work with a previous commit (salt 2014.7.0-291-gfbc61d2). Custom modules didn't changed after the pull.

**Comment by matdrapeau** [comment]
It appears I am still not able to import another module from a custom module directly.

With such example:
```
# cat > ping.py
from ling import *

# cat > ling.py
def ping():
    return True
```

this command ```salt-call ping.ping``` is returning this import error:
```
[DEBUG] Failed to import module ping:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 918, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/ping.py", line 1, in <module>
    from ling import *
ImportError: No module named ling

Function ping.ping is not available.
```

How to make the import work as expected?


version: salt 2015.2.0-491-g3ba763c (Lithium)

**Comment by basepi** [comment]
@matdrapeau Did your pull request fix this?

**Comment by matdrapeau** [comment]
@baseapi yes it does!
Should I close the ticket myself?

**Comment by basepi** [comment]
Either way. I grabbed it. =)

**Comment by matdrapeau** [comment]
Finally, this seems resolved only on the minion side and not when call the function FROM master:
```
%> salt 'machine1' ping.ping
machine1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1133, in _thread_return
        sys.modules[func.__module__].__context__['retcode'] = 0
    AttributeError: 'module' object has no attribute '__context__'
```
