### ISSUE TITLE
Unable to import salt utils in custom modules

### ISSUE THREAD

**Issue by openstackAnalyst** [saltstack/salt#34863]
### Description of Issue/Question

I have copied the test.py module from /usr/lib/python2.7/dist-packages/salt/modules and pasted it in /srv/salt/_modules with a different name. when i run salt '*' saltutil.sync_all, the output lists the module to be copied from salt master to salt minion but when i run the command it fails with unable to load module which can be seen in the minion log file.
```
root@vmSaltStackMaster:/srv/salt/_modules# 
root@vmSaltStackMaster:/srv/salt/_modules# salt '*' migrationConnect.ping
vmSaltStackAgent:
    Module 'migrationConnect' is not available.
root@vmSaltStackMaster:/srv/salt/_modules#
```
How can i import all the dependencies from the actual location to /srv/salt/_modules ?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

on the salt master:

```
root@vmSaltStackMaster:/srv/salt/_modules# pwd
/srv/salt/_modules
root@vmSaltStackMaster:/srv/salt/_modules# ls -l
total 160
-rw-r--r-- 1 root root    121 Jul 11 12:28 customuser.py
-rw-r--r-- 1 root root  12462 Jul 21 15:12 migrationConnect.py
-rw-r--r-- 1 root root 136376 Jul 19 11:04 migrationFile.py
-rw-r--r-- 1 root root     52 Jul 21 13:58 migrationTest.py
root@vmSaltStackMaster:/srv/salt/_modules#
```
The module file is copied to minion when i run the sync_all command.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

on the minion, the log file shows the below error:

```
root@vmSaltStackAgent:~# tail -f /var/log/salt/minion
  File "/var/cache/salt/minion/extmods/modules/migrationPing.py", line 193, in <module>
    versions = salt.utils.alias_function(versions_report, 'versions')
AttributeError: 'module' object has no attribute 'alias_function'
2016-07-21 15:11:59,067 [salt.loader      ][ERROR   ][45283] Failed to import module migrationConnect, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 958, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/migrationConnect.py", line 193, in <module>
    versions = salt.utils.alias_function(versions_report, 'versions')
AttributeError: 'module' object has no attribute 'alias_function'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```root@vmSaltStackMaster:/srv/salt/_modules# salt --versions-report
           Salt: 2015.5.3
         Python: 2.7.11 (default, Dec 15 2015, 16:46:19)
         Jinja2: 2.8
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
        Tornado: 4.2.1
root@vmSaltStackMaster:/srv/salt/_modules#```

**Comment by Ch3LL** [comment]
@openstackAnalyst i am able to see this behavior in 2015 branch. But it looks like its working in 2015.8 and 2016.3 branches. Would you mind updating to 2015.8.10 and seeing if it works?

**Comment by openstackAnalyst** [comment]
Many Thanks for the update, i will certainly upgrade my version and will try running the module.
I will update with the status.

**Comment by openstackAnalyst** [comment]
Hi Ch3LL

I have upgraded my salt version to the latest 2016.3 and tried to run salt modules and functions from /srv/salt/_modules directory and everything works fine.

I had to modify few modules/functions in my older version 2015.5.3 because salt was not working in my custom modules directory and for some functionality i had to write my own python code and sync them to minions.

good thing is that, at least __salt__ works in my custom module directory to run commands in 2015.5.3. 

Many Thanks for giving me the hint to upgrade my version.

root@vmSaltMasterSSL:/srv/salt/_modules# salt '*' saltutil.sync_all
vmSaltMinionSSL:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.migrateConnect
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
    utils:
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# salt '*' test.ping
vmSaltMinionSSL:
    True
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# salt '*' migrateConnect.ping
vmSaltMinionSSL:
    True
root@vmSaltMasterSSL:/srv/salt/_modules# 

root@vmSaltMasterSSL:/srv/salt/_modules# 
root@vmSaltMasterSSL:/srv/salt/_modules# salt '*' --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.0
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.2.0-27-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
root@vmSaltMasterSSL:/srv/salt/_modules#
