### ISSUE TITLE
Copy file from minion to master  ERRORS!!!

### ISSUE THREAD

**Issue by yujianglei** [saltstack/salt#36287]
Version Information:
[@localhost ]# salt-master --version
salt-master 2014.1.10 (Hydrogen)
salt-minion 2014.1.10 (Hydrogen)

Follow Logs:
[@zw_21_80 /data/saltstack_deploy_code/recomB]# salt   'zw_127_93'  cp.push /etc/fstab
zw_127_93:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1332, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.6/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 799, in push
        load_path_list = os.path.split(load_path_split_drive)
      File "/usr/lib64/python2.6/posixpath.py", line 82, in split
        i = p.rfind('/') + 1
    AttributeError: 'tuple' object has no attribute 'rfind'

**Comment by Ch3LL** [comment]
@yujianglei looks like you are on a pretty old salt version. I was going to say this is a duplicate of #35984 but you are not on that version of salt. This error on the 2016.3 branch will be fixed when 2016.3.4 comes out or I believe its suppose to be working on 2016.3.2 if you want to give that a try?

**Comment by yujianglei** [comment]
ok,  thank you.

**Comment by terminalmage** [comment]
@yujianglei Yeah that version has been end-of-life for over a year. One thing you might want to check is whether or not you have ``file_recv: True`` set on the master. This is required for ``cp.push`` to work.
