### ISSUE TITLE
lstrip_blocks error even with latest Jinja2

### ISSUE THREAD

**Issue by alex-solidfire** [saltstack/salt#24352]
Hello,

We are using the following in our minion config:
```jinja_lstrip_blocks: True```

When upgrading minions to 2015.5.0, we get this error:
```
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering Primary Top file failed, render error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 121, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 284, in render_jinja_tmpl
    **env_args)
TypeError: __init__() got an unexpected keyword argument 'lstrip_blocks'
```

We were able to resolve this on most of our minions by simply pip uninstalling salt and then reinstalling it with pip again.  However we have a stubborn minion now that I can't seem to fix with any amount of purging.  Any tips are appreciated.

**Comment by tbaker57** [comment]
Usually when we upgrade minions, we always:

+ stop the minion service
+ rm /var/cache/salt/minion/*
+ upgrade salt
+ start the minion service

which usually results in a clean upgrade.

cheers,
Tim

**Comment by alex-solidfire** [comment]
Thanks, we do take all these steps when upgrading.

When I look at line 284 of the file in question, I don't see anything about lstrip_blocks:
https://github.com/saltstack/salt/blob/v2015.5.0/salt/utils/templates.py#L284

So it seems like pip thinks 2015.5.0 is installed, but the files on disk don't match.

**Comment by alex-solidfire** [comment]
Jinja is at a new version:

```
$ python -c "import jinja2; print(jinja2.__version__)"
2.7.3
```

**Comment by tbaker57** [comment]
The error does seem to indicate it's picking up a crusty pre-2.7 version of jinja2 from somewhere. Is it installed via your os package manager as well as pip maybe ? (clutching at straws here)

**Comment by alex-solidfire** [comment]
Turns out it was the master running an old version of Jinja2, although the error seems like it could be the minion.  Upgraded and everything is working now, thank you!
