### ISSUE TITLE
The State System is Broken for Windows on the Develop Branch

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#39905]
### Description of Issue/Question
Running anything that applies a state in Windows (`state.sls`, `state.apply`) returns as a failure and raises a stacktrace on the Minion.
```
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\minion.py", line 1485, in _thread_return
    return_data = executor.execute()
  File "c:\salt-dev\salt\salt\executors\direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "c:\salt-dev\salt\salt\modules\state.py", line 546, in apply_
    return sls(mods, **kwargs)
  File "c:\salt-dev\salt\salt\modules\state.py", line 1050, in sls
    high_, errors = st_.render_highstate({saltenv: mods})
  File "c:\salt-dev\salt\salt\state.py", line 3493, in render_highstate
    sls, saltenv, mods, matches)
  File "c:\salt-dev\salt\salt\state.py", line 3147, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "c:\salt-dev\salt\salt\fileclient.py", line 396, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "c:\salt-dev\salt\salt\fileclient.py", line 178, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "c:\salt-dev\salt\salt\fileclient.py", line 487, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "c:\salt-dev\salt\salt\fileclient.py", line 1034, in get_file
    hash_server = self.hash_file(path, saltenv)
  File "c:\salt-dev\salt\salt\fileclient.py", line 1319, in hash_file
    return self.__hash_and_stat_file(path, saltenv)[0]
TypeError: 'bool' object has no attribute '__getitem__'
```
Doing a `git bisect` on the problem narrows it down to this PR: #39351

### Steps to Reproduce Issue
Apply any state file

### Versions Report
Salt: Head of Develop
OS: Windows Server 2016

**Comment by ninja-** [comment]
Woops...I'll have a look

**Comment by ninja-** [comment]
Are you sure that your master is on develop branch ?

**Comment by twangboy** [comment]
@ninja- It is not.

**Comment by ninja-** [comment]
That's the problem. It needs to be

**Comment by ninja-** [comment]
😅

**Comment by twangboy** [comment]
@ninja- OK, I'll test.

**Comment by twangboy** [comment]
@ninja- I'm still seeing this issue with master and minion both on head of Develop

**Comment by ninja-** [comment]
That's very unlikely. Could you try wiping your salt binaries from /usr/lib/python*/{site-modules,dist-packages}/salt before doing setup.py install? It often bugs out

**Comment by twangboy** [comment]
I'm working in develop mode (no salt directory in `dist-packages`). I did a `git reset --hard HEAD` and `git clean -fxd` before doing `pip install -e . --force`

**Comment by ninja-** [comment]
Could you attach master logs in debug mode. There should be a mention of master command _find_file_and_hash being run

**Comment by ninja-** [comment]
And attach salt --version

**Comment by ninja-** [comment]
...On both master and minion

**Comment by twangboy** [comment]
OK, when you asked me to attach versions for both, my master upstream was set to `twangboy/develop` instead of`saltstack/develop`. Changed my upstream, pulled the HEAD, and everything's good.

Sorry....

**Comment by twangboy** [comment]
I will close the issue

**Comment by twangboy** [comment]
@ninja- Thanks for your help.

**Comment by ninja-** [comment]
:+1:
