### ISSUE TITLE
Failure executing some formulas using salt-ssh on rc build

### ISSUE THREAD

**Issue by waynegemmell** [saltstack/salt#51516]
### Description of Issue/Question
When running salt-ssh using 2019.2.0.rc1 on some formulas it fails as follows. 

    - Rendering SLS 'base:zabbix.agent' failed: found unexpected ':'
    - Rendering SLS 'base:redis.common' failed: Jinja variable 'dict object' has no attribute 'pkg_name'
    - Rendering SLS 'base:monit.config' failed: found unexpected ':'

this worked on 2018.3 but now doesn't work on 2019.2.0.rc1.

### Setup
I've posted my pillar for the zabbix formula below. The error happens with defaults though. 

```
zabbix:
  lookup:
    version_repo: '4.0'
    agent:
      version: '4.0'

zabbix-agent:
  server: '10.3.0.214'
  serveractive: '10.3.0.214'
{% if grains['virtual'] == 'LXC' or grains['virtual'] == 'lxc' %}
  hostmetadata: lxc
{% endif %}
  pidfile: /var/run/zabbix/zabbix_agentd.pid
  logfile: /var/log/zabbix/zabbix_agentd.log
  logfilesize: 0
```
### Steps to Reproduce Issue
salt-ssh -i plugin-dev-master-1 -l info --hard-crash state.apply
[INFO    ] Loading Saltfile from '/home/wayne/NetBeansProjects/salt-project/Saltfile'
[CRITICAL] Rendering SLS 'base:zabbix.agent' failed: found unexpected ':'
[ERROR   ] Rendering exception occurred
[INFO    ] Fetching file from saltenv 'base', ** done ** 'git/plugin.sls'
[CRITICAL] Rendering SLS 'base:monit.config' failed: found unexpected ':'
plugin-dev-master-1:
    - Rendering SLS 'base:zabbix.agent' failed: found unexpected ':'
    - Rendering SLS 'base:redis.common' failed: Jinja variable 'dict object' has no attribute 'pkg_name'
    - Rendering SLS 'base:monit.config' failed: found unexpected ':'
    - Cannot extend ID 'zabbix-agent-restart' in 'base:zabbix.agent.conf'. It is not part of the high state.
      This is likely due to a missing include statement or an incorrectly typed ID.
      Ensure that a state with an ID of 'zabbix-agent-restart' is available
      in environment 'base' and to SLS 'zabbix.agent.conf'
    - Cannot extend ID 'zabbix-agent' in 'base:zabbix.agent.repo'. It is not part of the high state.
      This is likely due to a missing include statement or an incorrectly typed ID.
      Ensure that a state with an ID of 'zabbix-agent' is available
      in environment 'base' and to SLS 'zabbix.agent.repo'

### Versions Report
Salt Version:
           Salt: 2019.2.0rc2-8-gaee1cad
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this. Using your exact version I did the following:

1. `cd /srv/salt/; git clone https://github.com/saltstack-formulas/zabbix-formula.git .`
2. Add your pillar to /srv/pillar/test.sls and point to it in /srv/pillar/top.sls
3. `salt-ssh '*' state.apply zabbix.agent` renders correctly. I also tried `state.show_sls` and `state.apply zabbix.agent test=True`

Am i do anything different from your use case that you can see?

Also since it seems you probably upgraded. If you use `-w` with your salt-ssh call does it work? This will wipe away anything else you might have had cached.

**Comment by waynegemmell** [comment]
Zabbix came right when I removed a key conflict in known_hosts. I'm looking further at the munin fail.

**Comment by waynegemmell** [comment]
The issue with monit.config happens when I have a line with a colon in below. If I remove "--chuid php:developers" then it is processed properly. Switching to 2018.3.2 it processes successfully. 

```
monit:
  modules:
    submission_listener:
        process:
          with:
            pidfile: /var/run/submission_listener.pid
          config:
            group: php
            start: "/sbin/start-stop-daemon --start --background --make-pidfile --chuid php:developers --pidfile /var/run/submission_listener.pid --exec /usr/bin/php /var/local/connect/MMS/daemon/submissionListener.php debug test"
            stop: "/sbin/start-stop-daemon --stop --pidfile /var/run/submission_listener.pid"

```

**Comment by Ch3LL** [comment]
thanks for the additional information. I am now able to replicate this issue with just using salt-call.

to help replicate this issue here is a docker container:

1. ` docker run -it -v ~/git/salt/:/testing/ ch3ll/issues:51516` (where ~/git/salt/ is a local cloned git repo of salt)
2. `salt-call --local state.show_sls monit.config`

At first glance I thought this was related to the warning added in 2018.3.0 release notes here: https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html about needing to use salt's json or yaml filters, but that would mean this behavior should exhibit itself in 2018.3.0 and it does not. In 2018.3 branch it renders correctly so there might be something else going on here.

As a workaround you can use those filters on the file.managed state and it works correctly.

**Comment by Ch3LL** [comment]
this is the state that is causing the issues:

```
{{ monit.config_includes }}/modules:
  file.managed:
    - source: salt://monit/files/modules
    - template: jinja
    - context:
      modules: {{ monit.modules }}
```

with `monit.modules` being:

```
monit:
  modules:
    submission_listener:
        process:
          with:
            pidfile: /var/run/submission_listener.pid
          config:
            group: php
            start: "/sbin/start-stop-daemon --start --background --make-pidfile --chuid php:developers --pidfile /var/run/submission_listener.pid --exec /usr/bin/php /var/local/connect/MMS/daemon/submissionListener.php debug test"
            stop: "/sbin/start-stop-daemon --stop --pidfile /var/run/submission_listener.pid"
```

As @waynegemmell stated the issue is when it tries to render `php:developers`

**Comment by Ch3LL** [comment]
@waynegemmell my co-worker pointed out to me that this is expected behavior in the new 2019.2.0 release as documented here: https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer

this breaking change was added for a couple of reasons:

1. Allowing yaml to handle the "u" prefix  (which is not valid yaml) in the previous release was more of a hack, and this resulted in other problems that kept occurring. This became too cumbersome to handle each use case that exhibited an issue. 

2. Removing this hack around handling the "u" prefix allows us to use the C-based PyYaml loader which increases the speed of yaml loading and therefore salt.

**Comment by terminalmage** [comment]
Yeah, we don't yet have those release notes published on docs.saltstack.com anywhere else but the develop docs, so they wouldn't be visible unless one clicked specifically on the `develop` link. Sorry for the confusion.

**Comment by waynegemmell** [comment]
Ok, but what is the workaround? I need to have the colon in the value.

**Comment by Ch3LL** [comment]
going forward you will need to do the following on the file.managed state as described in those docs i posted:

```
/etc/foo.conf:
  file.managed:
    - source: salt://foo.conf.jinja
    - template: jinja
    - context:
        data: {{ data|tojson }}
```

note the tojson filter. i also tested the json and yaml filters and they worked as well.

**Comment by waynegemmell** [comment]
Thank you
