### ISSUE TITLE
[BUG] REST API (CherryPy) authentication problem since 3003.2

### ISSUE THREAD

**Issue by daks** [saltstack/salt#60841]
**Description**

After upgrading from Salt 3003 to 3003.3, access to Salt-API using CherryPy does not work anymore. Login seems to never work.
*(in previous attempts, login was working but queries not... I can't reproduce this now)*

**Setup**

- server runs on Debian 9
- Salt version was 3003 before upgrading to 3003.3. I tested all versions between those and it breaks since 3003.2
- API uses file backend for external auth

**Steps to Reproduce the behavior**

- salt-master in version 3003.2 or 3003.3
- configuration of the master
```
rest_cherrypy:
  disable_ssl: False
  host: 0.0.0.0
  ssl_crt: /etc/ssl/certs/<your_cert>.pem
  ssl_key: /etc/ssl/private/<your_key>.key
  port: <port_number>

external_auth:
  file:
    ^filename: '/etc/salt/eauth_users.txt'
```

Using `httpie` to query salt-api

```
$ http POST https://salt-dev.fraudbuster.mobi:15847/login username=<username> password='<password>' eauth=file -j
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Content-Type: text/plain
```
logs on server side
```
2021-09-06 13:42:14,074 [cherrypy.error   :216 ][ERROR   ][7066] [06/Sep/2021:13:42:14] ENGINE AttributeError("module 'six.moves.urllib_parse
' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1269, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 720, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 936, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 936, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
```

**Expected behavior**

I expect the login process to complete and return me a Token usable in another query on salt-api.

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.3.7
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Nov 18 2020, 21:09:16)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1
 
System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.14.0-0.bpo.3-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch
```
</details>

**Comment by OrangeDog** [comment]
There doesn't seem to be any Salt code involved in the error, though I'm not familiar with using the API.
Did you upgrade `cheroot` at the same time? Is this a .deb installation of Salt or a pip one?

**Comment by daks** [comment]
No salt code involved in fact, just access to the API. 

Salt is installed using saltstack apt repository `https://repo.saltproject.io/py3/debian/9/amd64/archive/3003.3 stretch main`. I just upgraded salt-* packages without doing anything else.

I'm don't know about `cheroot` which is not installed (with apt or dpkg) on my servers. It may be bundled with salt.

**Comment by OrangeDog** [comment]
> /usr/local/lib/python3.5/dist-packages/cheroot

You have cheroot installed in your system python, and that is what is erroring.
It should be from the package `python3-cheroot`.

What version have you got? According to [requirements.txt](https://github.com/saltstack/salt/blob/a46aa3a55c9ee43ded6ba2eed27270e89c1b4fa6/requirements/static/pkg/py3.5/linux.txt) it should be 6.5.4, which is also what the latest Debian 9 package says.
You are certain that only up/down-grading Salt is what changes whether this error occurs?

Your versions report doesn't even list cherrypy as installed, so I'm not sure what's going on there.
Can you remove cheroot and install cherrypy (`python3-cherrypy3`) instead?

> cherrypy: unknown

**Comment by daks** [comment]
I confirm that `cheroot` is installed with `pip` and not the Debian package.
```
$ dpkg -l|grep cheroot
$ sudo pip freeze|grep cheroot
cheroot==6.3.2
```
cherrypy is in fact installed with Debian system
```
$ dpkg -l|grep cherrypy
ii  python3-cherrypy3                 3.5.0-2                           all          Python 3 web development framework - version 3
```
I confirm that only changes done were applying our state to configure salt-master, which manages apt repositories, certificates, generate the eauth file, and enforce specific version of salt-master and salt-api.

What I have done next is:

- `pip uninstall cheroot`
- remove a remaining cheroot directory `rm -fr ./usr/local/lib/python3.5/dist-packages/cheroot`
- remove and reinstall python3-cherrypy3
- restart salt-master and salt-api

Now logs are unhappy about missing `cheroot`
```
2021-09-07 09:09:51,568 [rest_cherrypy    :55  ][ERROR   ][21432] Not loading 'salt.loaded.int.netapi.rest_cherrypy'. Error loading CherryPy:
 No module named 'cheroot'
```

```
salt --versions-report
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.3.7
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Nov 18 2020, 21:09:16)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1
 
System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.14.0-0.bpo.3-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch
```

**Comment by daks** [comment]
As I still got errors, I tried to return to a stable installation based on Debian packages, so I just `apt-get remove salt-*` then reinstall them `apt-get install salt-master salt-minion salt-api`.

Now the salt-api does not start, no listening port and no visible process (master is running OK) but no visible information in logs.

**Comment by OrangeDog** [comment]
It sounds like installing the Debian `python3-cheroot` would've fixed it, but with random local packages in your system python anything could happen.

I cannot see how changing salt could have caused the original issue, unless it also updated other packages (i.e. `six`).

**Comment by daks** [comment]
Debian 9 doesn't have any `cheroot` named package in its repository, so except if it comes from salt ones, I can't install it.

I don't think we have installed any specific local packages on this server (dedicated to salt-master). The only possibility would have been when we evaluated the use of Alcali https://github.com/latenighttales/alcali (a salt management UI).

**Comment by daks** [comment]
I had another Debian 9 with salt-master installed for dev purposes. I did the same: upgrade to 3003.3 and salt-api is working fine on this server.

It looks like my problem comes from non-standard things on my server. I'm not sure which and neither how to solve it.

For now we only upgraded our staging salt-master and I blocked the operation on the production one. I think we will planify this upgrade with enough time to downgrade again to 3003 if this problem appears. I hope it will not.

If it's not a problem, I will let this issue open for now and come back to close it later once this operation succeeds, or come back with more details.

**Comment by daks** [comment]
if useful salt --versions-report on this server
```
salt --versions-report
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: 3.5.0
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Apr  5 2021, 09:00:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1

System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch
```

**Comment by OrangeDog** [comment]
> Debian 9 doesn't have any cheroot named package

Sorry, I was looking at buster instead of stretch. Updating the pip package perhaps was the answer, but it's better to work on a server where you know the python environment is clean.

> salt-api didn't break

That one appears to have correctly detected cherrypy 3.5.0

**Comment by daks** [comment]
I upgraded our production salt-master and got no problem. The staging one must have been modified. Closing this issue.
