### ISSUE TITLE
'Minion' object5 has to attribute 'schedule'. Failed to add job to schedule.

### ISSUE THREAD

**Issue by mwtzzz** [saltstack/salt#42749]
### After upgrading salt-master and salt-minion to 2017.7.0-1, seeing the following error appear sporadically:

```
AttributeError: 'Minion' object has no attribute 'schedule'
2017-08-04 14:55:47,274 [tornado.application                                                                                                                                                                                                                                                                                          ][ERROR   ][6521] Exception in callback <functools.partial object at 0x7fb4fbacb940>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 591, in _run_callback
    ret = callback()
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 597, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 815, in handle_event
    yield [minion.handle_event(package) for minion in self.minions]
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 656, in callback
    result_list.append(f.result())
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1973, in handle_event
    self.manage_schedule(tag, data)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1845, in manage_schedule
    self.schedule.add_job(schedule, persist)
AttributeError: 'Minion' object has no attribute 'schedule'
2017-08-04 14:56:17,302 [salt.state       ][ERROR   ][23639] Failed to add job git-pull-master to schedule.

```
git-pull-master looks like this:
```
git-pull-master:
  schedule.present:
    - function: state.sls
    - job_args:
       - cluster.salt-master.sre-salt-git-repo
    - seconds: 20
    - maxrunning: 1
    - persist: true
    - return_job: true
    - enabled: true
```
cluster.salt-master.sre-salt-git-repo looks like this:
```
include:
  - packages.git

git-sre-salt:
  git.latest:
    - name: git@github.com:xxx/xxx.git
    - branch: master
    - force_reset: True
    - target: /media/ephemeral0/git/sre-salt
    - identity: /root/.ssh/deploy-key.rsa
    - require:
      - pkg: git

```
Version info:
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 20 2016, 20:53:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.4.16-27.56.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by garethgreenaway** [comment]
@mwtzzz Can you give an estimate how often you're seeing this error and any circumstances that might be happening when you see it?  Is it during state runs when schedule items are being added or attempted to be added to a minion?  Does the job get successfully added to the minion(s) where you see this error?

**Comment by mwtzzz** [comment]
It happens about once or twice a day on each of our salt masters. The git-pull is one of the salt-master's own states, so this is for the highstate of the master itself. 

But, following a suggestion I found elsewhere online, I deleted all the .pyc files under /usr/lib/python2.7/site-packages/salt/ (first stopping the salt-minion and salt-master services)  with the theory that there were stale.pyc files left around from before the upgrade. I did this yesterday afternoon and have not seen a recurrence of the error.

I'll keep an eye on it over the next few days.

**Comment by garethgreenaway** [comment]
Old .pyc files from a previous release is a possible cause.  Hopefully, this fixes it, please keep us posted on the status.  Thanks! :)

**Comment by mwtzzz** [comment]
I'll post an update here. If error does not recur in the next few days, I'll consider it fixed.

**Comment by mwtzzz** [comment]
The error still appears on one of my hosts (every highstate):
```
2017-08-07 12:57:39,171 [salt.state       ][ERROR   ][10463] Failed to add job git-pull-master to schedule.
2017-08-07 13:03:16,751 [salt.state       ][ERROR   ][11537] Failed to add job git-pull-master to schedule.
2017-08-07 13:14:58,062 [salt.state       ][ERROR   ][13298] Failed to add job git-pull-master to schedule.
2017-08-07 13:25:25,679 [salt.state       ][ERROR   ][15116] Failed to add job git-pull-master to schedule.
2017-08-07 13:38:34,656 [salt.state       ][ERROR   ][17455] Failed to add job git-pull-master to schedule.
2017-08-07 13:44:45,102 [salt.state       ][ERROR   ][18342] Failed to add job git-pull-master to schedule.
2017-08-07 14:08:22,149 [salt.state       ][ERROR   ][22310] Failed to add job git-pull-master to schedule.
2017-08-07 14:16:49,043 [salt.state       ][ERROR   ][23908] Failed to add job git-pull-master to schedule.
2017-08-07 14:46:35,435 [salt.state       ][ERROR   ][28988] Failed to add job git-pull-master to schedule.
2017-08-07 14:55:02,755 [salt.state       ][ERROR   ][30193] Failed to add job git-pull-master to schedule.
2017-08-07 15:03:29,279 [salt.state       ][ERROR   ][31460] Failed to add job git-pull-master to schedule.
2017-08-07 15:15:02,013 [salt.state       ][ERROR   ][1075] Failed to add job git-pull-master to schedule.
```
But on my other hosts it has not recurred. I'm not sure what the difference is between them; they're all running the same version of salt.

**Comment by mwtzzz** [comment]
I'm trying one more thing; I've shut down service and instead of deleting just the `pyc` files I'm also deleting the `pyo` files... Restarting service, keeping an eye on it let's see what happens.

**Comment by mwtzzz** [comment]
no errors so far... need to give it a couple more days .. .

**Comment by mwtzzz** [comment]
This has not happened any more since deleting the `pyc` and `pyo` files. So, I'm going to say this issue is fixed.
