### ISSUE TITLE
salt-ssh stacktraces on first run

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#28881]
```
root@li1314-235:~# salt-ssh -i '*' test.ping
Permission denied for host basepi, do you want to deploy the salt-ssh key? (password required):
[Y/n]
Password for root@basepi:
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 548, in run
    if ret[host].get('stderr', '').startswith('ssh:'):
AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 377, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 548, in run
    if ret[host].get('stderr', '').startswith('ssh:'):
AttributeError: 'str' object has no attribute 'get'
```

Subsequently works.

Seems to be caused by https://github.com/saltstack/salt/pull/28638, just need to check the type of the return to make sure it's actually a dict.
