### PR TITLE
Fix setup salt paths

### PR DESCRIPTION
**Pull request by s0undt3ch**
- Evaluate paths one by one since some depend on others
- Salt path options are now global and default to None. Since we now evaluate each `salt.syspath` entry one by one, we only set the passed settings in the generated `_syspaths` module. The default values will mandate unless explicitly overridden in the setup stage.

### CODE REVIEW

**Comment by thatch45** [comment]
@cachedout @s0undt3ch are these test failures all due to the tests not being updated to the deprecations?

**Comment by s0undt3ch** [comment]
Most if not all, due to the fact that we should start showing errors for unexpected keyword arguments.

**Comment by s0undt3ch** [comment]
I believe the test failures are not related to this change.

**Comment by cachedout** [comment]
Git bisect leads me to believe this is the cause of failures in ``integration.shell.call.CallTest.test_local_sls_call``

**Comment by s0undt3ch** [comment]
It is. @rallytime pointed that to me this morning. I'll try to see what I broke in a few...

**Comment by cachedout** [comment]
Thanks, @s0undt3ch. I will try and look too.

**Comment by s0undt3ch** [comment]
So far this has been hard to track down. Either `--local` or `--file-root` is setting the base file roots to `None`. Still haven't pinpointed where exactly.

**Comment by aboe76** [comment]
@s0undt3ch I have found the can't render pillar #19702 if I explicitly set pillar_roots in salt master and minion config...it starts working again.

**Comment by s0undt3ch** [comment]
I think that my findings with our finding nails the bug.

Still need to find out why this PR started triggering this.
