### ISSUE TITLE
zenoss.add_device fails on windows minion

### ISSUE THREAD

**Issue by prog-dale** [saltstack/salt#50034]
### Description of Issue/Question
salt -C '*' zenoss.add_device device_class=Server/Microsoft/Windows
  The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\zenoss.py", line 181, in add_device
        response = _router_request('DeviceRouter', 'addDevice', data=[data])
      File "c:\salt\bin\lib\site-packages\salt\modules\zenoss.py", line 96, in _router_request
        url = '{0}/zport/dmd/{1}_router'.format(config.get('hostname'), ROUTERS[router])
    AttributeError: 'str' object has no attribute 'get'

### Setup
salt -C '*' zenoss.add_device device_class=Server/Microsoft/Windows

### Steps to Reproduce Issue
salt -C '*' zenoss.add_device device_class=Server/Microsoft/Windows
... against a windows minion

### Versions Report
    Salt Version:
               Salt: 2018.3.2

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free

**Comment by Ch3LL** [comment]
if you run `config.get zenoss` against your minion what is returned (sanitize the output before pasting)? i'm guessing your configuration is returning a string and not a dictionary like its expecting.

**Comment by prog-dale** [comment]
salt '*' config.get zenoss
cloud-xxx.cloudstack.dk:
    ----------
    hostname:
        https://zen.cloudstack.dk
    password:
        xxxxxxxxxx
    username:
        admin

**Comment by prog-dale** [comment]
salt 'cloud-xxx.cloudstack.dk' zenoss.device_exists
cloud-xxx.cloudstack.dk:
    Passed invalid arguments to zenoss.device_exists: cannot use a string pattern on a bytes-like object

        Check to see if a device already exists in Zenoss.

        Parameters:
            device:         (Optional) Will use the grain 'fqdn' by default

        CLI Example:
            salt '*' zenoss.device_exists

**Comment by prog-dale** [comment]
On the same server against a linux machine i get ...
 'zenoss' __virtual__ returned False: The 'zenoss' module could not be loaded: 'requests' is not installed.

**Comment by Ch3LL** [comment]
sorry i didn't clarify. I'm referring to this error: `'zenoss' virtual returned False: The 'zenoss' module could not be loaded: 'requests' is not installed.` that you stated you see on the linux VM. This means the zenoss module will never load there because it requires the python module requests. You should be able to install it via a `pip` install or in your package repository

**Comment by prog-dale** [comment]
If i install requests ...
`salt 'test-rda01.cloudstack.dk' zenoss.device_exists
test-rda01.cloudstack.dk:
    Passed invalid arguments to zenoss.device_exists: can't use a string pattern on a bytes-like object

        Check to see if a device already exists in Zenoss.

        Parameters:
            device:         (Optional) Will use the grain 'fqdn' by default

        CLI Example:
            salt '*' zenoss.device_exists

`

**Comment by prog-dale** [comment]
This works in 2017.7.2 python 2 but not with 2018.3.2 Python 3

**Comment by Ch3LL** [comment]
thanks for clarifying on the linux side of things. so it seems its not only related to the OS.

We did a ton of unicode work in the 2018.3 release so I'm guessing this is related to that. Can you do me  another favor and add a couple log lines in the following:


```
diff --git a/salt/modules/zenoss.py b/salt/modules/zenoss.py
index bca710faea..f6e515efa5 100644
--- a/salt/modules/zenoss.py
+++ b/salt/modules/zenoss.py
@@ -92,6 +92,8 @@ def _router_request(router, method, data=None):
         tid=1)])
 
     config = __salt__['config.option']('zenoss')
+    log.error('config is {0}'.format(config))
+    log.error('config type is {0}'.format(type(config))
     log.debug('Making request to router %s with method %s', router, method)
     url = '{0}/zport/dmd/{1}_router'.format(config.get('hostname'), ROUTERS[router])
     response = _session().post(url, data=req_data)
```

**Comment by prog-dale** [comment]
Yes of course, and then run it again with debug or ?

**Comment by Ch3LL** [comment]
they should show up without debug as ti will spit out an error but go ahead and run with debug so we can get more context around the output :)

**Comment by prog-dale** [comment]
'zenoss' __virtual__ returned False: invalid syntax (zenoss.py, line 97)
ERROR: Minions returned with non-zero exit code

**Comment by Ch3LL** [comment]
sorry i missed a `)`

```
+    log.error('config is {0}'.format(config))
+    log.error('config type is {0}'.format(type(config)))
```

**Comment by prog-dale** [comment]
The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\zenoss.py", line 157, in device_exists
        if find_device(device):
      File "c:\salt\bin\lib\site-packages\salt\modules\zenoss.py", line 131, in find_device
        all_devices = _router_request('DeviceRouter', 'getDevices', data=data)
      File "c:\salt\bin\lib\site-packages\salt\modules\zenoss.py", line 98, in _router_request
        url = '{0}/zport/dmd/{1}_router'.format(config.get('hostname'), ROUTERS[router])
    AttributeError: 'str' object has no attribute 'get'

**Comment by prog-dale** [comment]
this is 2018.3.3

**Comment by Ch3LL** [comment]
im not seeing the errors only the stack trace? Did you check the logs on the minion? Thats where they would show up

**Comment by prog-dale** [comment]
Ok now im super confused its working with 2018.3.3 the minion i tested it on had lost its config after a wipe and reinstall. But this minion has the config and seems to work.

> cloud-sql04.cloudstack.dk:
>     ----------
>     new_jobs:
>         |_
>           ----------
>           description:
>               Create cloud-sql04.cloudstack.dk under /Server/Microsoft/Windows/CLOUDSTACK
>           uid:
>               /zport/dmd/JobManager
>           uuid:
>               20d32d0e-e06a-4466-a25e-d2f9bdfebf1d
>         |_
>           ----------
>           description:
>               Discover and model device cloud-sql04.cloudstack.dk as /Server/Microsoft/Windows/CLOUDSTACK
>           uid:
>               /zport/dmd/JobManager
>           uuid:
>               ff41adf6-8833-47f3-ad10-35a36bfc3256
>     success:
>         True
> [root@cloud-salt03 ~]# salt -C 'cloud-sql04.cloudstack.dk' cmd.run 'salt-call --version'
> cloud-sql04.cloudstack.dk:
>     salt-call 2018.3.3 (Oxygen)
