### ISSUE TITLE
[BUG] Unable to refresh pillar on Windows minion with M2Crypto installed

### ISSUE THREAD

**Issue by plinkable** [saltstack/salt#57266]
**Description**
We first noticed this problem after upgrading to 2019.2.4 from 2018.3.4, but highstate would fail every time with an error. Quick diagnostics and it was traced to pillar, as test.ping would work fine. It would also work if we removed M2Crypto, as the affected line wasn't being called.

**Setup**
Install 2019.2.4 from saltstack repo. Manually pip install the wheel package for M2Crypto 0.35.2 from:

- https://ci.appveyor.com/project/m2crypto/m2crypto/builds/32180192/job/mo7q8abwqh1fowuu/artifacts

**Steps to Reproduce the behavior**
<details><summary>salt-call saltutil.refresh_pillar<br/>
AttributeError: 'RsaKey' object has no attribute 'private_decrypt'</summary>

```
PS C:\salt> salt-call saltutil.refresh_pillar
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'RsaKey' object has no attribute 'private_decrypt'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 47, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 80, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 332, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 106, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 846, in __init__
    self.gen_modules(initial_load=True)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 442, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "C:\salt\bin\lib\site-packages\salt\pillar\__init__.py", line 247, in compile_pillar
    dictkey='pillar',
  File "C:\salt\bin\lib\site-packages\salt\utils\asynchronous.py", line 64, in wrap
    ret = self._block_future(ret)
  File "C:\salt\bin\lib\site-packages\salt\utils\asynchronous.py", line 74, in _block_future
    return future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 303, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'],
AttributeError: 'RsaKey' object has no attribute 'private_decrypt'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 431, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 47, in run
    caller = salt.cli.caller.Caller.factory(self.config)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 80, in factory
    return ZeroMQCaller(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 332, in __init__
    super(ZeroMQCaller, self).__init__(opts)
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 106, in __init__
    self.minion = salt.minion.SMinion(opts)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 846, in __init__
    self.gen_modules(initial_load=True)
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 442, in gen_modules
    pillarenv=self.opts.get('pillarenv'),
  File "C:\salt\bin\lib\site-packages\salt\pillar\__init__.py", line 247, in compile_pillar
    dictkey='pillar',
  File "C:\salt\bin\lib\site-packages\salt\utils\asynchronous.py", line 64, in wrap
    ret = self._block_future(ret)
  File "C:\salt\bin\lib\site-packages\salt\utils\asynchronous.py", line 74, in _block_future
    return future.result()
  File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 303, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'],
AttributeError: 'RsaKey' object has no attribute 'private_decrypt'
```
</details>

**Expected behavior**
Pillar refreshes without error, allowing highstate to run without error

**Screenshots**
Log as above

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
C:\salt> salt-call --versions-report
Salt Version:
           Salt: 2019.2.4
Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019Server
         system: Windows
        version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

**Additional context**
We've been using a manually built version of M2Crypto for a while now (v0.30.1) but both that version and version 0.35.2 from the link above exhibit the above error on the servers that are failing. However, other Windows minions don't have this problem, with either version of M2Crypto installed and 2019.2.4.

**Comment by plinkable** [comment]
Ping @dwoz as requested (originally)

**Comment by cmcmarrow** [comment]
This is an ugly bug. I have no been able to reproduce this but I can tell you what I have ruled out. 

I installed 2018.3 and M2Crypto “from the url” then upgraded to v2019.2.4 and got no error.
I verified that line 303, `aes = key.private_decrypt(ret[‘key;])` runs

When I run pillar `key` is an `RSA` object. But the error reports key as an `RsaKey` Object.

One big hint I found was M2Crypto.RSA does not has an `RsaKey` Class. Which makes me think another crpyto modules is being called. 

So my current consultation is some of your minions has a setting that causes multiple crpyto modules to be used.

**Comment by plinkable** [comment]
Quick search reveals this exists in pycryptodome. eg https://github.com/Legrandin/pycryptodome/blob/v3.8.1/lib/Crypto/PublicKey/RSA.py#L51

**Comment by plinkable** [comment]
For reference, these should be otherwise virgin Windows installs, using only content provided by that installer, plus M2Crypto, which is a hard dependency for the x509 state/module.

I can check again to make sure there's nothing left over from a previous version that shouldn't be there, eg in pycache, but I agree it shouldn't be happening in any case.

**Comment by cmcmarrow** [comment]
@plinkable that would be great! Can you give me more information on the minions that are working and not working? Can I get your top.sls and your minion.conf file? Sensitive information censored of course.

**Comment by plinkable** [comment]
I've gone several steps further than that already, with help from @waynew. These are Server2016 and 2019 running under kvm, and they don't have the VC2013 runtime installed. The very one that's in the salt installation folder. Putting that in the path in any way makes everything work the same way it always used to with 2018.3.

So the sequence of events now seems to be:
1) salt/crypt.py checks for M2Crypto and it fails to load due to the runtime not resolving
2) crypt falls back to cryptodome and _get_key_with_evict runs and the result is cached
3) something causes the runtime to be loaded from C:\salt\bin into the python process address space
4) zeromq loads, succeeds in loading M2Crypto, and tries to use it, causing the mismatch

So my issue now becomes 3 questions:
- why isn't this loading in the first place
- what's causing it to load now
- how can we stop this mismatch from happening, or detect it and handle it gracefully?

**Comment by plinkable** [comment]
My suspicion is that this used to "just work" in 2018.3 because one (or more) of the core dependencies shipped with the Windows install loaded the runtime earlier, and a newer version in 2019.2 uses a newer runtime instead.

Not that this explains why the above sequence appears to be happening. It feels like a race condition that's happening rather reliably on our servers.

**Comment by plinkable** [comment]
Some further information I've just uncovered. This issue only affects `salt-call`, and only under specific scenarios. The running minion is fine.

Specifically, `salt-call --versions-report` succeeds in loading M2Crypto and returns the version found. In a not-altogether-unrelated note, a quick check on an old 2018.3.2 minion I had in a VM behaved differently and wasn't even able to load M2Crypto for the versions report, which may be why we thought it was working in that version, when in reality it simply wasn't triggering the mismatch we're now seeing.

To summarise:
- the runtime should load when M2Crypto requests it, but doesn't
- crypt.py is failing to load M2Crypto when it first tries, resulting in a (correct) fallback, in this case to cryptodome
- zeromq.py succeeds importing M2Crypto and tries to use it rather than detecting the fallback

This doesn't happen on any machine where MSVCR120.dll is already in the path, as the first point above succeeds and uses M2Crypto throughout. As a result, reproducing this problem will require ensuring the runtime is not already present on the machine being tested. It also only happens with salt-call, so testing via a master will also not trigger this scenario.

A quick check of the test suite indicates that there aren't any passing tests for x509 under Windows - they're seemingly all skipped because M2Crypto isn't available! I did find tests for Linux, eg Centos.

Please let me know if there's anything further you need from me.

**Comment by plinkable** [comment]
Just tried 3000.3, same problem

**Comment by plinkable** [comment]
The x509 integration test isn't even listed for this suite, but the results I found were:

https://jenkinsci.saltstack.com/job/pr-windows2016-py3-slow/job/master/38/testReport/unit.modules.test_x509/X509TestCase/
