### ISSUE TITLE
[develop] TestSuite stacktraces at the end of an integration test run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#34967]
### Description of Issue/Question
When running any integration test at the current [HEAD of develop](55bb3d09ab374da89419ab697320ee559c1e9d0a), the tests run successfully, but there is a stacktrace at the end while waiting for the processes to clean up:
```
# python runtests.py -n integration.modules.aliases

 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /root/SaltStack/salt
 * Test suite is running under PID 2773
 * Logging tests on /tmp/salt-runtests.log

 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096

 * Setting up Salt daemons to execute tests

 * Starting salt-master ... STARTED!
 * Starting salt-minion ... STARTED!
 * Starting sub salt-minion ... STARTED!
 * Starting syndic salt-master ... STARTED!
 * Starting salt-syndic ... STARTED!

Starting integration.modules.aliases Tests

....
----------------------------------------------------------------------
Ran 4 tests in 3.576s

OK
Traceback (most recent call last):
  File "runtests.py", line 603, in <module>
    main()
  File "runtests.py", line 588, in main
    status = parser.run_integration_tests()
  File "runtests.py", line 533, in run_integration_tests
    status.append(self.run_integration_suite(**TEST_SUITES[suite]))
  File "/root/SaltStack/salt/tests/integration/__init__.py", line 1234, in __exit__
    self.sub_minion_process.terminate()
  File "/root/SaltStack/salt/tests/integration/__init__.py", line 500, in terminate
    children = parent.children(recursive=True)
AttributeError: 'Process' object has no attribute 'children'
```

The test suite then hangs there until doing a control-c. After that point, various stacktraces are printed:
```
^CError in atexit._run_exitfuncs:The Salt Syndic is shutdown. Syndic received a SIGINT. Exited.

Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
The salt master is shutdown. Master received a SIGINT. Exited.
The salt master is shutdown. Master received a SIGINT. Exited.
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
----------------------------------------
 ----------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever
    r, w, e = _eintr_retry(select.select, [self], [], [],
AttributeError: 'NoneType' object has no attribute 'select'

 ----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35818)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35756)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35784)
Exception happened during processing of request from ('127.0.0.1', 35858)
Exception happened during processing of request from ('127.0.0.1', 35722)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/root/SaltStack/salt/tests/integration/__init__.py", line 300, in handle
    log.exception(exc)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/SaltStack/salt/salt/log/setup.py", line 309, in _log
    LOGGING_LOGGER_CLASS._log(
AttributeError: 'NoneType' object has no attribute '_log'
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 594, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/root/SaltStack/salt/tests/integration/__init__.py", line 300, in handle
    log.exception(exc)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/SaltStack/salt/salt/log/setup.py", line 309, in _log
    LOGGING_LOGGER_CLASS._log(
AttributeError: 'NoneType' object has no attribute '_log'
Traceback (most recent call last):
Traceback (most recent call last):
 ----------------------------------------
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
----------------------------------------
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/root/SaltStack/salt/tests/integration/__init__.py", line 300, in handle
    log.exception(exc)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/SaltStack/salt/salt/log/setup.py", line 309, in _log
    LOGGING_LOGGER_CLASS._log(
AttributeError: 'NoneType' object has no attribute '_log'
----------------------------------------
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 597, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 597, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'

  File "/root/SaltStack/salt/tests/integration/__init__.py", line 300, in handle
    log.exception(exc)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/root/SaltStack/salt/salt/log/setup.py", line 309, in _log
    LOGGING_LOGGER_CLASS._log(
AttributeError: 'NoneType' object has no attribute '_log'
----------------------------------------
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 597, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 597, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 597, in process_request_thread
    self.shutdown_request(request)
  File "/usr/lib/python2.7/SocketServer.py", line 471, in shutdown_request
    except socket.error:
AttributeError: 'NoneType' object has no attribute 'error'

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 321, in _exit_function
    p._popen.terminate()
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 321, in _exit_function
    p._popen.terminate()
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/SaltStack/salt/tests/integration/files/log_handlers/runtests_log_handler.py", line 70, in process_queue
    except socket.error as exc:
AttributeError: 'NoneType' object has no attribute 'error'
```

Git bisect points to the change in #33108 as to wear this problem first surfaced. This is also related to #33920.

### Setup
Just run any integration tests against the develop branch. I have the most recent version of salttesting installed as well.

### Versions Report
```
# salt --versions
Salt Version:
           Salt: 2016.3.0-961-g55bb3d

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 5.0.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.5.5
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
Update: the original stack trace posted at the top of my issue is caused by the version of psutil installed via apt: `1.2.1-1ubuntu2`. Once handling for the missing `children` attribute, the original stack trace is gone. There are other issues after that point, but I believe they're more related to #33920.
