### ISSUE TITLE
Traceback from test.not_loaded (develop and 2015.2)

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#21402]
Using test.not_loaded with a pull from both develop and 2015.2 this morning causes the following traceback:

develop
---
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1143, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/test.py", line 377, in not_loaded
        loader = salt.loader._create_loader(__opts__, 'modules', 'module')
    AttributeError: 'module' object has no attribute '_create_loader'
```
2015.2
---
```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1116, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/test.py", line 371, in not_loaded
        loader = salt.loader._create_loader(__opts__, 'modules', 'module')
    AttributeError: 'module' object has no attribute '_create_loader'
```

**Comment by rallytime** [comment]
I can reproduce this as well. It is working on the HEAD of 2014.7, however.

I wonder if some of the changes @jacksontj has been making in regards to the loader could be causing this error.

**Comment by jacksontj** [comment]
Bit surprising that this was missed, guess no test calls this :/

I can fix it to the way it was before (#21457) but we should probably re-think these tests all together. This is testing for module we haven't loaded, but it doesn't take __virtual__ into account at all.

**Comment by rallytime** [comment]
@jacksontj I actually hadn't even used this function before trying to verify this. A re-think of what we're doing with that function makes sense to me.

**Comment by techhat** [comment]
Thanks @jacksontj. This was a case of, I saw the function, thought I'd try it, and it didn't work. If it's not meant to be used from the CLI, I'd be happy with documentation saying so. When I saw it, I wondered too why `test.loaded` wasn't there.

**Comment by rallytime** [comment]
@techhat and @jacksontj Should we close this issue since the initial failure is fixed? Or should we keep it around to remind us to fix the other things that were mentioned? I am happy either way...we can always revisit things or open a new issue that more accurately reflects the `test.loaded` vs. `test.not_loaded` conversation.

**Comment by jacksontj** [comment]
Probably close this and make a separate issue?

**Comment by rallytime** [comment]
Done.
