### ISSUE TITLE
unit.renderers.gpg_test.GPGTestCase.test__decrypt_object fails

### ISSUE THREAD

**Issue by mephi42** [saltstack/salt#39334]
### Setup
Checkout salt

### Steps to Reproduce Issue
```
$ tests/runtests.py -n unit.renderers.gpg_test
   -> unit.renderers.gpg_test.GPGTestCase.test__decrypt_object  ..........................................................................................................................................
       Traceback (most recent call last):
         File "/Users/beep/ibm/salt/tests/unit/renderers/gpg_test.py", line 80, in test__decrypt_object
           self.assertEqual(gpg._decrypt_object(secret), secret)
         File "/Users/beep/ibm/salt/salt/renderers/gpg.py", line 282, in _decrypt_object
           if isinstance(obj, cStringIO.InputType):
       AttributeError: 'builtin_function_or_method' object has no attribute 'InputType'
```

I believe this is caused by bef5e66c5b678bd0f46ce0d32a736b34e2aca001.

### Versions Report
$ git rev-parse HEAD
17521fb23c92122c0ac045b092bb46e1ff958080

**Comment by terminalmage** [comment]
Fixed in #39340.
