### ISSUE TITLE
salt.wheel.WheelClient doesn't work follow the python api(AttributeError: 'NoneType' object has no attribute 'get')

### ISSUE THREAD

**Issue by CaesarC** [saltstack/salt#26415]
```python
Python 2.7.9 (default, Dec 23 2014, 16:44:59) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.config
>>> import salt.wheel
opts = salt.config.master_config('/etc/salt/master')
wheel = salt.wheel.WheelClient(opts)>>> opts = salt.config.master_config('/etc/salt/master')

>>> wheel = salt.wheel.WheelClient(opts)
>>> wheel.cmd('key.finger', ['jerry'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/htdocs/python_env/lib/python2.7/site-packages/salt/wheel/__init__.py", line 124, in cmd
    return self.low(fun, kwarg)
  File "/home/htdocs/python_env/lib/python2.7/site-packages/salt/client/mixins.py", line 233, in low
    jid = low.get('__jid__', salt.utils.jid.gen_jid())
AttributeError: 'NoneType' object has no attribute 'get'
>>> 
```
```
http://docs.saltstack.com/en/latest/ref/clients/#wheelclient
```

**Comment by CaesarC** [comment]
```
Package salt-master-2015.5.3-3.el6.noarch already installed and latest version
```

**Comment by CaesarC** [comment]
Either the key.list_all
```
>>> wheel.cmd('key.list_all')         
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/htdocs/python_env/lib/python2.7/site-packages/salt/wheel/__init__.py", line 124, in cmd
    return self.low(fun, kwarg)
  File "/home/htdocs/python_env/lib/python2.7/site-packages/salt/client/mixins.py", line 233, in low
    jid = low.get('__jid__', salt.utils.jid.gen_jid())
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by cachedout** [comment]
That's definetely a bug. We'll take a look! Thanks.

**Comment by wt** [comment]
I can confirm that this is broken.

**Comment by wt** [comment]
I found that if I add the following arg to the wheel.cmd call, everything works:

    kwarg={}

Either wheel.cmd should have the **kwargs parameter (and pass that in the call to self.low instead of kwarg), or the following should be at the top of the function:

    if kwarg is None:
        kwarg = {}

**Comment by rickh563** [comment]
ZD-471

**Comment by DmitryKuzmenko** [comment]
Interesting, actually v2015.5.3 doesn't contain this bug. It's included in the following releases only:
```
v2015.5.4
v2015.5.5
v2015.5.6
v2015.8.0
v2015.8.0rc4
v2015.8.0rc5
v2015.8.1
```

The issue was introduced in 5664de66 where the ```WheelClient.cmd()``` was updated with wrong implementation. Before the ```cmd()``` method was inherited from parent ```SyncClientMixins```

**Comment by DmitryKuzmenko** [comment]
The fix #28087 fixes the issue but in 2015.8 the described workflow will not work even with the fix applied getting the same as in #27130. So 2015.8 also needs the fix #28020 to fully fix this.
