### ISSUE TITLE
Salt Rest Api call

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#41733]
### Description of Issue/Question
I was running following salt api calls from powershell which were running fine with 2016.11.2.
$createdata = @{"client"="runner";"fun"="state.sls";"username"="%SaltUser%";"password"="%SaltPassword%";"eauth"="%SaltEauth%";"output"="json";"arg"="create_profiles";"kwarg"=$kwarg} | convertto-json -depth 5

After i upgraded salt to 2016.11.5, i have started getting following error,

 "return": "Exception occurred in runner state.sls: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/dist-packages/salt/client/mixins.py\", line 395, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: orchestrate() got an unexpected keyword argument 'output'\n", 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.5

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.16.0-30-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by whiteinge** [comment]
@sumeetisp it looks like the `output` kwarg that it's complaining about was being silently ignored in previous versions. Since JSON is the default return format for salt-api I expect you can just remove that kwarg and things will be back to working as they were. Please let me know if that isn't the case.

**Comment by sumeetisp** [comment]
Yes i had removed it and it worked perfectly fine. But my point was it should have ignored it like it did  previously and not raised a error.

**Comment by whiteinge** [comment]
Glad to hear it's working. Silently ignoring kwargs can lead to unexpected behavior and errors so we've been incrementally adding better checks throughout Salt.

**Comment by whiteinge** [comment]
Ah, apologies. I overlooked your point. Yes, I agree this should not change over a point-release. I'm not sure why that did change offhand but we will look into it.

**Comment by whiteinge** [comment]
The PR above should restore ignoring invalid kwargs. Sorry for the trouble and thanks for bringing this to our attention!
