### ISSUE TITLE
Stacktrace when running state.sls against an sls does not exist

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#35423]
### Setup
When attempting to run `state.sls` and the state does not exist I am seeing teh following in the debug logs:

```
[ch3ll@thecakeisalie ~]$ sudo salt '*02*' state.sls doesnotexist -ldebug

...
[DEBUG   ] LazyLoaded highstate.output
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'ch3ll-minion02': ["No matching sls found for 'doesnotexist' in env 'base'"]}
[DEBUG   ] Traceback (most recent call last):
  File "/home/ch3ll/git/salt/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
AttributeError: 'NoneType' object has no attribute 'rstrip'

[DEBUG   ] LazyLoaded nested.output
ch3ll-minion02:
    - No matching sls found for 'doesnotexist' in env 'base'
[DEBUG   ] jid 20160812160340754435 found all minions set(['ch3ll-minion02'])
ERROR: Minions returned with non-zero exit code
```

### Steps to Reproduce Issue
1. Run `salt '*' state.sls doesnotexist` Just make sure the sls file does not exist in your file_roots

The first bad commit is 82a70e015fbab5decc4ba1176bd066fac0ffa6c2 
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
[root@ch3ll-cent7 salt]# salt --versions-report
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.1
            ZMQ: 4.1.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by DaveQB** [comment]
I think I am getting something like this.
I have this in my init.sls

{% include "rsyslog-loggly/init.sls" %}

Which does not exist. Then running a state.apply on the server this init.sls will apply to I get:

`
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["ID 'rsyslog-loggly-certificate' in SLS 'b2c.www-torrens-edu-au' contains multiple state declarations of the same type"]}
local:
    - ID 'rsyslog-loggly-certificate' in SLS 'b2c.www-torrens-edu-au' contains multiple state declarations of the same type
`

When I remove that include line, we are right. I'll look into the patch but I thought I should report it as it is a different message than the original report.



Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: 0.1.6
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 12.04 precise
        machine: x86_64
        release: 3.2.0-80-virtual
         system: Linux
        version: Ubuntu 12.04 precise

**Comment by DaveQB** [comment]
I applied this patch
https://github.com/saltstack/salt/pull/35428/files

But no improvement.

More information (DEBUG)

```
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/ply/nginx-php5/init.sls' using 'yaml' renderer: 0.035101890564
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'ply-www-torrens-edu-au-ap-southeast-2a.think.vpc', 'tcp://10.150.31.129:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'ply-www-torrens-edu-au-ap-southeast-2a.think.vpc', 'tcp://10.150.31.129:4506')
[DEBUG   ] LazyLoaded highstate.output
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["ID 'rsyslog-loggly-certificate' in SLS 'b2c.www-torrens-edu-au' contains multiple state declarations of the same type"]}
[DEBUG   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/output/__init__.py", line 39, in try_printout
    return get_printout(out, opts)(data).rstrip()
AttributeError: 'NoneType' object has no attribute 'rstrip'

[DEBUG   ] LazyLoaded nested.output
```

**Comment by Ch3LL** [comment]
I am still seeing this error in carbon so I am re-opening this issue. I do not see the stack trace in the debug output anymore but I'm still seeing `Data passed to highstate outputer...`


```
[root@localhost ~]# salt '*' state.sls doesnotexist -ldebug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 10.0.2.15
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 10.0.2.15
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', '10.0.2.15_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/50/4f50bccffe4259a25bbcffffb9aefb41119950f697ce412be556fca442fd75/.minions.p
[DEBUG   ] get_iter_returns for jid 20160906204515643528 sent to set(['10.0.2.15']) will timeout at 20:45:20.649634
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] jid 20160906204515643528 return from 10.0.2.15
[DEBUG   ] LazyLoaded highstate.output
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'10.0.2.15': ["No matching sls found for 'doesnotexist' in env 'base'"]}
[DEBUG   ] jid 20160906204515643528 found all minions set(['10.0.2.15'])
ERROR: Minions returned with non-zero exit code
```

```
[root@localhost ~]# salt --versions-report
Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.8.1.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final
```

**Comment by Ch3LL** [comment]
Also see this error when JINJA variable is undefined:

```
[root@localhost ~]# salt-call --local state.sls uptodate
[WARNING ] Key 'whitelist_modules' with value None has an invalid type of NoneType, a list is required for this value
[ERROR   ] Rendering exception occurred: Jinja variable 'websrvr' is undefined
[CRITICAL] Rendering SLS 'base:uptodate' failed: Jinja variable 'websrvr' is undefined
[ERROR   ] Data passed to highstate outputter is not a valid highstate return: {'local': ["Rendering SLS 'base:uptodate' failed: Jinja variable 'websrvr' is undefined"]}
```

**Comment by meggiebot** [comment]
We need to add a test for this since it seems to have regressed again.

**Comment by cachedout** [comment]
Please follow #36137 for a resolution to this issue.
