### ISSUE TITLE
grains.append not working in 2014.1.13

### ISSUE THREAD

**Issue by WillPlatnick** [saltstack/salt#16819]
When I use the grains.append state in 2014.1.13 I get the error below. If I roll my package back to 2014.1.7, it works just fine.

```
          ID: sensu-consul-agent-grain
    Function: module.run
        Name: grains.append
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1382, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/module.py", line 203, in run
                  if ret['changes'].get('ret', {}).get('retcode', 0) != 0:
              AttributeError: 'str' object has no attribute 'get'
     Changes:
```

```
           Salt: 2014.1.13
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```
