### ISSUE TITLE
salt.returners.highstate_return errors out

### ISSUE THREAD

**Issue by soostdijck** [saltstack/salt#46730]
### salt.returners.highstate_return errors out
I'm trying to get the salt.returners.highstate_return to send me emails with run output, I've set thing up correctly afaik but I'm getting the following error when I run `salt 'lamb*' state.highstate --return highstate` on my master as per [the example in here](https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.highstate_return.html)
```
==> /var/log/salt/minion <==
2018-03-27 16:39:04,481 [salt.state       :2836][WARNING ][27157] top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order.
2018-03-27 16:39:09,068 [salt.minion      :1613][ERROR   ][27307] The return failed for job 20180327163909030048 'str' object has no attribute 'get'
2018-03-27 16:39:09,068 [salt.minion      :1616][ERROR   ][27307] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1604, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 478, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 335, in _generate_report
    key=lambda s: s[1].get('__run_num__', 0)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 335, in <lambda>
    key=lambda s: s[1].get('__run_num__', 0)
AttributeError: 'str' object has no attribute 'get'
```

I'm not sure if I'm hitting a bug or if I've got something misconfigured somewhere. Any help would be appreciated! 

### Setup
On my minion I've got:
```
0:root@lamb $ cat /etc/salt/minion.d/return_highstate_mail|grep -v #
highstate:
  report_failures: True
  report_changes: True
  failure_function: pillar.items
  success_function: state.show_top
  report_format: html
  report_delivery: smtp
  smtp_success_subject: 'success on {host}'
  smtp_failure_subject: 'failure on {host}'
  smtp_server: smtp.xxx.net
  smtp_recipients: salt-alerts@xxx.net
  smtp_sender: oper@salt.xxx.net
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by gtmanfred** [comment]
Can you provide me with a simplified state run that can replicate this?

Because I am unable to replicate this with just a simple test.succeed_without_changes state.

Thanks,
Daniel

**Comment by soostdijck** [comment]
Just to update that this issue is still around after upgrading to 2018.3.0, slightly changed:
```2018-04-19 14:17:18,300 [salt.minion      :1723][ERROR   ][2353] The return failed for job 20180419141718253780: 'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1714, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 480, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 337, in _generate_report
    key=lambda s: s[1].get('__run_num__', 0)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 337, in <lambda>
    key=lambda s: s[1].get('__run_num__', 0)
AttributeError: 'unicode' object has no attribute 'get'```
