### ISSUE TITLE
Kubernetes module won't work with Kubernetes Python client > 1.0.2

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#42843]
### Description of Issue/Question

The stable [Kubernetes Python client](https://github.com/kubernetes-incubator/client-python) is version 2.0.0 at the moment. Version 3.0.0 will be release in the near future. The Saltstack Kubernetes module is based on version 1.0.2.

Kubernetes broke some of the API used by the Saltstack Kubernetes module, so that version 2.0.0 can't be used at the moment.

### Setup
You can use Falvio's [salt-kubernetes-demo](https://github.com/flavio/salt-kubernetes-demo) to setup a Kubernetes test scenario.

### Steps to Reproduce Issue
1. Setup your Kubernets cluster.
2. Follow the instructions [here](https://github.com/flavio/salt-kubernetes-demo/blob/master/README.md), but specifically install the Kubernetes Python client version 2.0.0 like this: `pip install kubernetes==2.0.0`
3. Try the Nginx test deployment.

You should get an error message like this: `AttributeError: 'module' object has no attribute 'V1beta1Deployment'`

### Versions Report
You'll at least want to use Salt 2017.7, since this is the version where the Kubernetes module was introduced.

**Comment by Ch3LL** [comment]
@brejoc thanks for the PR. As you do have a PR in we will close this issue and keep the discussion in the PR but please let us know if this needs to be re-opened if PR does not get accepted. Thanks
