### ISSUE TITLE
2015.8.2 import pagerduty error 

### ISSUE THREAD

**Issue by mimianddaniel** [saltstack/salt#28981]
Since upgrading to 2015.8.2, seeing the following error in the master.log

2015-11-17 23:33:59,283 [salt.loader                                  ][ERROR   ][31030] Failed to import runners pagerduty, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/loader.py", line 959, in _load_module
    suffix_order.append(suffix)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/runners/pagerduty.py", line 123, in <module>
    list_maintenance_windows = salt.utils.alias_function(list_windows, 'list_maintenance_windows')

**Comment by jfindlay** [comment]
@mimianddaniel, thanks for the report.  Your stack trace looks incomplete.  Is it possible to post the whole output?

**Comment by mimianddaniel** [comment]
sorry bad cut and paste..
2015-11-17 23:33:59,283 [salt.loader                                  ][ERROR   ][31030] Failed to import runners pagerduty, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/loader.py", line 959, in _load_module
    suffix_order.append(suffix)
  File "/opt/blue-python/2.7/lib/python2.7/site-packages/salt/runners/pagerduty.py", line 123, in <module>
    list_maintenance_windows = salt.utils.alias_function(list_windows, 'list_maintenance_windows')
AttributeError: 'module' object has no attribute 'alias_function'

**Comment by jfindlay** [comment]
@mimianddaniel, thanks for the extra info.  The fix will be in the next release.  As a workaround, you should be able to update the runner module according to the referenced pull request.
