### ISSUE TITLE
[modules/nova] AttributeError: 'module' object has no attribute 'discover_extensions' when using nova.image_list

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#29557]
The nova execution module should try to check if discover_extensions exists before using it. It is neither available in python-novaclient 2:2.23.0-1~bpo8+1 (from jessie-backports) nor in python-novaclient 2:2.18.1-1 (from jessie). 

``` 
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2355, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2232, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1451, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3720, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3419, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 180, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 415, in render_jinja_tmpl
                  trace=tracestr)
              SaltRenderError: Jinja error: 'module' object has no attribute 'discover_extensions'
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 4, in top-level template code
                File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 504, in image_list
                  conn = _auth(profile)
                File "/usr/lib/python2.7/dist-packages/salt/modules/nova.py", line 99, in _auth
                  return suon.SaltNova(**kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 145, in __init__
                  self.extensions = client.discover_extensions('1.1')
              AttributeError: 'module' object has no attribute 'discover_extensions'
```

Versions information 

```
# dpkg -l python-novaclient
ii  python-novaclient                 2:2.18.1-1            all                   client library for OpenStack Compute API

# salt-call --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: Not Installed
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.2 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.2 
 
```

A quick look at the python-novaclient project seems to show that this has been introduced in version 2.24.0 … 

It seems that this was introduced in pull request https://github.com/saltstack/salt/pull/28041 ping @gtmanfred @techhat @rallytime 

I think this is a bug, or a missing catch or at least a documentation missing (but I would rather these modules depended on versions that are packaged and shipped for distributions).

**Comment by rallytime** [comment]
Good catch @arthurlogilab and thanks for this very helpful report. I think this should be documented, but we should also be catching that use-case and avoiding the stack trace.

**Comment by gtmanfred** [comment]
That is my bad, i thought the discover_extensions went back farther than it did.

**Comment by rallytime** [comment]
Thanks @gtmanfred!
