### ISSUE TITLE
AWS EBS Volume creating/attachment fails

### ISSUE THREAD

**Issue by marek-obuchowicz** [saltstack/salt#19813]
After creating instance with two EBS volumes configured, salt-cloud crashes. Volume vol-b51535f1 was created, but not attached to the instance.
AttachVolume gets response {'Message': "vol-b51535f1 is not 'available'.", 'Code': 'IncorrectState'}, but salt-cloud continues and crashes. Below the output:
```
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'_stamp': '2015-01-17T14:02:03.290434', 'event': 'attaching volumes', 'volumes': [{'device': '/dev/sdf', 'type': 'gp2', 'size': 500}, {'device': '/dev/sdg', 'type': 'gp2', 'size': 200}]}
[INFO    ] Create and attach volumes to node couchbase-htc-production-test04
[DEBUG   ] {'Action': 'CreateVolume', 'AvailabilityZone': 'us-east-1a', 'VolumeType': 'gp2', 'Size': 500}
[DEBUG   ] Using EC2 endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] "GET /?SignatureVersion=2&AvailabilityZone=us-east-1a&Version=2013-10-01&Timestamp=2015-01-17T14%3A02%3A03Z&VolumeType=gp2&SignatureMethod=xxx&Action=CreateVolume&Size=500 HTTP/1.1" 200 None
[DEBUG   ] EC2 Response Status Code: 200
[DEBUG   ] {'Action': 'AttachVolume', 'InstanceId': 'i-e53a3609', 'VolumeId': 'vol-b51535f1', 'Device': '/dev/sdf'}
[DEBUG   ] Using EC2 endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] "GET /?SignatureVersion=xxx&Timestamp=2015-01-17T14%3A02%3A03Z&VolumeId=vol-b51535f1&Device=%2Fdev%2Fsdf&SignatureMethod=HmacSHA256&Version=2013-10-01&Signature=xxx&Action=AttachVolume HTTP/1.1" 400 None
[DEBUG   ] EC2 Response Status Code: 400
[ERROR   ] EC2 Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': "vol-b51535f1 is not 'available'.", 'Code': 'IncorrectState'}}, 'RequestID': '5b943259-1d80-4d21-ab38-6bbe745de270'}
[DEBUG   ] Using EC2 endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] "GET /?SignatureVersion=xxx&InstanceId.1=i-e53a3609&Timestamp=2015-01-17T14%3A02%3A03Z&SignatureMethod=HmacSHA256&Version=2013-10-01&Signature=xxx&Action=DescribeInstances HTTP/1.1" 200 None
[DEBUG   ] EC2 Response Status Code: 200
[DEBUG   ] Using EC2 endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[INFO    ] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[DEBUG   ] "GET /?SignatureVersion=2&AWSAccessKeyId=xxx&InstanceId=i-e53a3609&Timestamp=2015-01-17T14%3A02%3A04Z&SignatureMethod=HmacSHA256&Version=2013-10-01&Signature=xxx&Action=ModifyInstanceAttribute HTTP/1.1" 400 None
[DEBUG   ] EC2 Response Status Code: 400
[ERROR   ] EC2 Response Status Code and Error: [400 400 Client Error: Bad Request] {'Errors': {'Error': {'Message': 'No attributes specified.', 'Code': 'InvalidParameterCombination'}}, 'RequestID': 'ceab9ff5-41bf-4ddb-b525-7da5678ea28b'}
[ERROR   ] There was a profile error: 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 231, in run
    self.config.get('names')
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1320, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1190, in create
    output = self.clouds[func](vm_)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 41, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1190, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 2059, in create
    call='action'
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 2156, in create_attach_volumes
    value=delvols_on_destroy)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 3018, in _toggle_delvol
    return query(requesturl=requesturl)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 280, in query
    params_with_headers = params.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by rallytime** [comment]
Thanks for the report @marek-obuchowicz. Can you tell us what version of salt you are running by posting the output of `salt-cloud --versions-report`?

**Comment by marek-obuchowicz** [comment]
I just have downgraded to 2014.1.3, so that we can work again. The problem was happening with salt-cloud installed via rpm from EPEL package salt-cloud-2014.7.0-3.el6.noarch

**Comment by rallytime** [comment]
Ok, so this was working for you in 2014.1.13, but is not longer working in 2014.7.0. We'll take a look!

**Comment by rallytime** [comment]
@marek-obuchowicz Do you know if this is happening on the newer release branch? Current stable is 2015.5.2. I know I was seeing some volume creation and attachment problems on the 2014.7 branch that have cleared up in the 2015.5.x releases. I am wondering if this one is fixed as well.

**Comment by rallytime** [comment]
@marek-obuchowicz I can not longer reproduce this failure at the HEAD of 2015.5. Creating and attaching the volume occurred without any problems in this successful provision on an instance on EC2:
```
nt-testing-4:
    ----------
    amiLaunchIndex:
        0
    architecture:
        x86_64
    blockDeviceMapping:
        ----------
        item:
            ----------
            deviceName:
                /dev/sda1
            ebs:
                ----------
                attachTime:
                    2015-08-13T18:48:47.000Z
                deleteOnTermination:
                    true
                status:
                    attaching
                volumeId:
                    vol-f5050b1f
<snipped>
```
Versions:
```
# salt-cloud --versions
            Salt: 2015.5.3-229-g65ab5aa
          Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
          Jinja2: 2.7.3
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.11
           ioflo: Not Installed
           PyZMQ: 14.0.1
            RAET: Not Installed
             ZMQ: 4.0.4
            Mako: 0.9.1
         Tornado: 4.2
         timelib: 0.2.4
 Apache Libcloud: 0.14.1
```
Are you still still hitting this in a newer release of salt?

**Comment by marek-obuchowicz** [comment]
Checked 2015.5.3 and it works fine, problem does not exist anymore

**Comment by rallytime** [comment]
Awesome! Thanks @marek-obuchowicz for confirming.
