### ISSUE TITLE
[BUG] v3002.5/salt/modules/cmdmod.py trying to split a tuple object

### ISSUE THREAD

**Issue by sugarraysam** [saltstack/salt#59793]
**Description**
While executing a custom module from `salt://_modules/<module>.py`, using `__salt__["cmd.run"]` with version `3002.5` , received the following Traceback:

```python
<minion_id>:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1890, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1846, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/covariant.py", line 51, in init_data_disk
        __salt__["partition.mklabel"](device=target_drive, label_type="gpt")  # noqa: F821
      File "/usr/lib/python3/dist-packages/salt/modules/parted_partition.py", line 495, in mklabel
        out = __salt__["cmd.run"](cmd, python_shell=False).splitlines()
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 1201, in run
        **kwargs
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 401, in _run
        _log_cmd(cmd),
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 82, in _log_cmd
        return cmd.split()[0].strip()
    AttributeError: 'tuple' object has no attribute 'split'
ERROR: Minions returned with non-zero exit code
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

We are running 3002.5 on this minion, it is unclear to me why ` $ salt --versions-report` show 2018.3.4. `salt-minion.service` has been restarted.

```
$ salt --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Feb 27 2021, 15:10:58)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-112-generic
         system: Linux
        version: Ubuntu 18.04 bionic


$ salt-minion --version
salt-minion 3002.5

$ pip3 show salt
Name: salt
Version: 3002.5
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /usr/lib/python3/dist-packages
Requires:
```
</details>

**Additional context**
Seems the easy fix is just to add a check see if the object is either a `tuple` or a `list`:

```python
def _log_cmd(cmd):
    if not isinstance(cmd, (tuple,list)):
        return cmd.split()[0].strip()
    return cmd[0].strip()
```

**Comment by sagetherage** [comment]
@sugarraysam Salt v2018.3.4 is no longer supported, are you able to upgrade to a supported version >v3000.8?

**Comment by sugarraysam** [comment]
@sagetherage Please note we are using `3002.5`, this is another issue where the `/usr/bin/salt` script was not upgraded. It still loads the python2 salt package and runs `salt_main`, causing mis-reporting by `$ salt -V`:

```python
#!/usr/bin/python2.7
'''
Publish commands to the salt system from the command line on the master.
'''
from salt.scripts import salt_main

if __name__ == '__main__':
    salt_main()
```

This is what we have on the minion:

```bash
$ salt-minion --version
salt-minion 3002.5

$ pip3 show salt
Name: salt
Version: 3002.5
Summary: Portable, distributed, remote execution and configuration management system
Home-page: http://saltstack.org
Author: Thomas S Hatch
Author-email: thatch45@gmail.com
License: Apache Software License 2.0
Location: /usr/lib/python3/dist-packages
Requires:
```

`salt "<minion>" grains.get pythonversion` == 3.6.9
`salt "<minion>" grains.get saltversion` == 3002.5

**Comment by danielrobbins** [comment]
@sugarraysam this looks like it is caused because cmd.run is expecting a string, not a tuple. I think the appropriate fix would be to pass a string. Can you try that?

**Comment by danielrobbins** [comment]
> @sagetherage Please note we are using `3002.5`, this is another issue where the `/usr/bin/salt` script was not upgraded. It still loads the python2 salt package and runs `salt_main`, causing mis-reporting by `$ salt -V`:

For this particular issue, I would recommend removing the vestiges of salt 2018 from your system, so that 3002.5 is the only thing on it. If there is some issue with the install/upgrade process that causes this problem to happen frequently (2 different versions of salt installed, or leftover remains of an old release still installed), then please open an independent issue for it, and we will investigate.

**Comment by sugarraysam** [comment]
@danielrobbins the confusion comes from reading the docs [Cross Calling Execution Modules](https://docs.saltproject.io/en/latest/ref/modules/index.html#cross-calling-execution-modules). It seems we can pass in the parameters required by the module we are trying to call.

In our case, the failing snippet is this:
 
```python
mkpart_out = __salt__["cmd.run"](mkpart_cmd, python_shell=False).splitlines()
```

We pass in two arguments to conform with the [`cmd.run` interface](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run).

How should we set the `python_shell` parameter?

**Comment by sugarraysam** [comment]
> @danielrobbins the confusion comes from reading the docs [Cross Calling Execution Modules](https://docs.saltproject.io/en/latest/ref/modules/index.html#cross-calling-execution-modules). It seems we can pass in the parameters required by the module we are trying to call.
> 
> In our case, the failing snippet is this:
> 
> ```python
> mkpart_out = __salt__["cmd.run"](mkpart_cmd, python_shell=False).splitlines()
> ```
> 
> We pass in two arguments to conform with the [`cmd.run` interface](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run).
> 
> How should we set the `python_shell` parameter?

**Comment by danielrobbins** [comment]
@sugarraysam yes, you can pass in arguments, but cmd.run wants a string as a first argument. If you pass in a string, it will be happy.

**Comment by toddtimes** [comment]
@danielrobbins sorry for the lack of response on this. I've been working with @sugarraysam to try to diagnose and fix this and I don't understand what the correct input format is to get this to work. I've tried a dozen combinations with no luck, including:

`target_drive = "/dev/sdb"`

`_salt__["partition.mklabel"]("device=/dev/sbd label_type=gpt")`
`__salt__["partition.mklabel"]("%s gpt" % target_drive)`

and other combinations that use only a string and start with a string, and all produce either tracebacks for the line referenced below or `Passed invalid arguments to covariant.init_data_disk: mklabel() missing 1 required positional argument: 'label_type'`

Given that `__salt__["partition.mklabel"](target_drive, "gpt")` works perfectly with https://github.com/saltstack/salt/blame/v3002.5/salt/modules/cmdmod.py#L80 modified to handle tuples by adding `if not isinstance(cmd, (list, tuple)):` it seems like there's a bug that was introduced here by not handling lists along with tuples.

Can you help point me to what I'm missing?

**Comment by danielrobbins** [comment]
A positional argument in python looks like this:

```
foo("bleh")
```

In this case, the function is ``foo``, the positional argument is ``"bleh"``, a string. It is called 'positional' because python/jinja will recognize what variable you are referring to by its order -- ie. "position" within the parenthesis.

Besides positional arguments, there are also keyword arguments. Keyword arguments look like this:

```
foo(mork="nanu nanu")
```

In this case, the keyword argument is ``mork``, indicating that you are providing a value to the function for a parameter named ``mork``, and you are giving it a string (in this case, ``"nanu nanu"``.)

These can also be combined, but when they are, positional arguments must come first, as follows. Each argument, whether positional or keyword, must be separated by a comma. You'll also notice that the arguments are not combined together with quotes. They just sit inside the parenthesis. We will only quote the literal strings we are passing as arguments.

```
foo("bleh", mork="nanu nanu")
```

Above, this specifies that whatever is foo's first positional argument will get the value of "bleh", and then afterwards we specify a keyword argument.

So based on this information, and looking at the errors provided by salt, partition.mklabel requires two positional arguments -- the first being the block device, and the second being the label type (or in other words, the "format" or the partition type, such as "mbr" or "gpt". These are both strings, so you would specify it like this, using your first example:

```
__salt__["partition.mklabel"]("/dev/sdb", "gpt")

I'll show you how to figure out the exact calling convention for each execution function. Let's look at the docs here:

https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.parted_partition.html#salt.modules.parted_partition.mklabel

You'll see the "signature" listed for partition.mklabel as follows:

```
salt.modules.parted_partition.mklabel(device, label_type)
```

Look inside the parenthesis. ``device`` means "the positional argument of the device" and ``label_type`` means "the positional argument of the label_type.``. This means you just specify two literal quoted string, separated by commas. Now, let's look at another signature that is different:

https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.parted_partition.html#salt.modules.parted_partition.mkpart

Mkpart has this signature:

```
salt.modules.parted_partition.mkpart(device, part_type, fs_type=None, start=None, end=None)
```

You will see that the first two arguments are positional, meaning you just provide quoted strings separated by commas for the device and part_type. The remaining arguments are keywords arguments, and in fact, they are optional and have default values so you don't need to specify them. See the example calls, which closely maps to what you would call with ``__salt__``:

```
salt '*' partition.mkpart /dev/sda primary fs_type=fat32 start=0 end=639
salt '*' partition.mkpart /dev/sda primary start=0 end=639
```

The steps to convert from our salt command examples to ``__salt__`` calls which should work reliably are:

1. Anything that is a string, put double quotes around it. So ``/dev/sda`` would be written as ``"/dev/sda"``.
2. Each argument is separated from every other argument by a comma and optionally a space (but the comma is required)
3. Keyword arguments convert using similar rules. So ``fs_type=fat32`` would convert to ``fs_type="fat32"``.
4. Keyword arguments generally have defaults so they are optional. Positional arguments are required and you just pass the value they should have without mentioning them my name, as the value you pass is assigned to the correct variable in the function by the position they appear in the argument list.

This should help you to leverage our documentation to call execution functions directly from .sls files.

**Comment by toddtimes** [comment]
@danielrobbins thanks for the very comprehensive reply. But this just lands me right back where we started, when I have salt 3002.5 installed and format the command exactly as you suggested `__salt__["partition.mklabel"](target_drive, "gpt")` (where target_drive = "/dev/sdb") I get the original error @sugarraysam reported:

```    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1890, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1846, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/covariant.py", line 51, in init_data_disk
        __salt__["partition.mklabel"](target_drive, "gpt")  # noqa: F821
      File "/usr/lib/python3/dist-packages/salt/modules/parted_partition.py", line 495, in mklabel
        out = __salt__["cmd.run"](cmd, python_shell=False).splitlines()
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 1201, in run
        **kwargs
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 401, in _run
        _log_cmd(cmd),
      File "/usr/lib/python3/dist-packages/salt/modules/cmdmod.py", line 82, in _log_cmd
        return cmd.split()[0].strip()
    AttributeError: 'tuple' object has no attribute 'split'```
   
   This is why I'm VERY confident there was a bug introduced with https://github.com/saltstack/salt/commit/ac2ce3a3a000e428122bc120179e083de95c1de7 when it no longer handled a tuple with the else:
https://github.com/saltstack/salt/commit/ac2ce3a3a000e428122bc120179e083de95c1de7#diff-700b7d75700c9eafa3ee48d01236e59f37b2ed81d998267136fbcc0224766497L395

**Comment by danielrobbins** [comment]
OK, I think the challenge is that you are starting the troubleshooting process but the specific command that is failing has not yet been described. Let's document this first, and then I will attempt to reproduce the issue. You are stating that something like:

```
__salt__("partition.mklabel")("/dev/sdb", "gpt")
```

... is producing a traceback? If so, I will try to reproduce here.

**Comment by toddtimes** [comment]
That is correct, thanks.

**Comment by danielrobbins** [comment]
@toddtimes @sugarraysam OK, I get it now. Yes, it looks like this code dropped a condition.

**Comment by toddtimes** [comment]
Thanks for confirming. I’m happy to submit a PR if you think modifying the first check to look for an instance match on list or tuple is the right approach, that’s the temporary fix I used

**Comment by danielrobbins** [comment]
So the issue is that ``salt/modules/parted_partition.py`` uses a rare form of calling ``cmd.run()`` and passes things as a TUPLE, not a string or a list. This functionality was likely unintentionally dropped with commit https://github.com/saltstack/salt/commit/ac2ce3a3a000e428122bc120179e083de95c1de7 where ``_log_cmd()`` assumes a string or a list, but does not handle the case of a tuple. This means that this commit unintentionally broke some execution functions in ``salt/modules/parted_partition.py`` (and possibly other places) that rely on this behavior.

Rather than track all these down and convert to lists, the likely best fix is to address the regression that broke ``mklabel`` and others.

Recommended fix is to change ``_log_cmd`` to be more robust:

```
def _log_cmd(cmd):
    if isinstance(cmd, str):
        return cmd.split()[0].strip()
    elif isinstance(cmd, (tuple, list)):    
        return cmd[0].strip()
    else:
      return str(cmd)
```

**Comment by danielrobbins** [comment]
@toddtimes a PR implementing a fix very similar or identical to the fix I included above would be welcome :) Sorry for the confusion in understanding what you were reporting. I think we are on the same page now :)
