### PR TITLE
[2017.7] Fix docstring integration test failure

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?
Fixes the following test failure:
- integration.modules.test_sysmod.SysModuleTest.test_valid_docs

### What issues does this PR fix or reference?
This was introduced with #44552.

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by sathieu** [comment]
A similar bug is currently happening [only on win2016-py2](https://jenkinsci.saltstack.com/job/pr-kitchen-windows2016-py2/job/PR-50417/3/console):
```
03:06:47        ============================  Overall Tests Report  ============================
03:06:47        *** integration.modules.test_sysmod Tests  *************************************
03:06:47         --------  Tests with Errors  --------------------------------------------------
03:06:47           -> integration.modules.test_sysmod.SysModuleTest.test_valid_docs  ...........
03:06:47        Traceback (most recent call last):
03:06:47          File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_sysmod.py", line 29, in test_valid_docs
03:06:47            '\n'.join(['  - {0}'.format(f) for f in ret['missing_docstring']]),
03:06:47        TypeError: 'bool' object has no attribute '__getitem__'
03:06:47           .............................................................................
03:06:47         -------------------------------------------------------------------------------
03:06:47        ================================================================================
03:06:47        FAILED (total=1, skipped=0, passed=0, failures=0, errors=1) 
03:06:47        ============================  Overall Tests Report  ============================
```

Any idea how to fix it?
