### ISSUE TITLE
CloudClient vmware driver reusing SI bug

### ISSUE THREAD

**Issue by ikkaro** [saltstack/salt#36598]
### Description of Issue/Question

I get this error when executing a second command using CloudClient:
ConnectionResetError: [Errno 104] Connection reset by peer
Seems related to ServiceIntance.
If I run the commands separately it works fine.
### Setup

Standar installation from git. 
All dependencies installed.
### Steps to Reproduce Issue

```
import logging
import json
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")
from salt.cloud import CloudClient
folderToCreate='TESTDC/vm/DevDeploys03'
folderSpecstr='{"path":"'+folderToCreate+'"}'
folderSpec=json.loads(folderSpecstr)

client= CloudClient(path='/var/www/html/api/salt/cloud',config_dir='/var/www/html/api/salt/cloud.profiles.d')
client.action(fun='create_folder',provider='vmware',kwargs=folderSpec)
client.profile('vmware-57e946358a5da51360a475ea',names=['testigj99',])
```

```
>>> client.action(fun='create_folder',provider='vmware',kwargs=folderSpec)
{'vmware': {'vmware': {'/TESTDC/vm/DevDeploys03': 'specfied path already exists'}}}
>>> client.profile('vmware-57e946358a5da51360a475ea',names=['testigj99',])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/install/salt_code_git/salt_develop/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/home/install/salt_code_git/salt_develop/salt/cloud/__init__.py", line 1455, in run_profile
    ret[name] = self.create(vm_)
  File "/home/install/salt_code_git/salt_develop/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/home/install/salt_code_git/salt_develop/salt/cloud/clouds/vmware.py", line 2340, in create
    datacenter_ref = salt.utils.vmware.get_mor_by_property(_get_si(), vim.Datacenter, datacenter)
  File "/home/install/salt_code_git/salt_develop/salt/utils/vmware.py", line 696, in get_mor_by_property
    object_list = get_mors_with_properties(service_instance, object_type, property_list=[property_name], container_ref=container_ref)
  File "/home/install/salt_code_git/salt_develop/salt/utils/vmware.py", line 738, in get_mors_with_properties
    local_properties=local_properties)
  File "/home/install/salt_code_git/salt_develop/salt/utils/vmware.py", line 622, in get_content
    container_ref = service_instance.content.rootFolder
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/var/www/html/api/venv_api2/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1327, in InvokeMethod
    resp = conn.getresponse()
  File "/usr/lib/python2.7/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python2.7/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python2.7/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python2.7/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python2.7/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python2.7/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
```

This code is working

```
import logging
import json
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")
from salt.cloud import CloudClient
folderToCreate='vdc_CLARA_02_IFR/vm/DevDeploys03'
folderSpecstr='{"path":"'+folderToCreate+'"}'
print (folderSpecstr)
folderSpec=json.loads(folderSpecstr)

client= CloudClient(path='/var/www/html/api/salt/cloud',config_dir='/var/www/html/api/salt/cloud.profiles.d')
client.action(fun='create_folder',provider='vmware',kwargs=folderSpec)
```

```
{'vmware': {'vmware': {'/TESTDC/vm/DevDeploys03': 'specfied path already exists'}}}
```

This code is algo working

```
import logging
import json
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")
from salt.cloud import CloudClient
folderToCreate='/TESTDC/vm/DevDeploys03'
client= CloudClient(path='/var/www/html/api/salt/cloud',config_dir='/var/www/html/api/salt/cloud.profiles.d')
client.profile('vmware-57e946358a5da51360a475ea',names=['testigj99',])
```
### Versions Report

pyvmomi (5.5.0.2014.1.1)
salt from git develop branch
also 2016.3

**Comment by Ch3LL** [comment]
@nmadhok do you happen to have any ideas on this one?

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/issues/34547#issuecomment-253036952

confirmed.

```
salt --version : salt 2016.11.0-187-g8b9648c
python --version : Python 2.7.12
pip install --upgrade pyvmomi : latest
```

state: test.sls
```
t1:
    cloudtest.get_instance:
        - name: salt-play-test.xxx.ca
t2:
    cloudtest.get_instance:
        - name: salt-play-test.xxx.ca
t3:
    cloudtest.get_instance:
        - name: salt-play-test.xxx.ca
t4:
    cloudtest.get_instance:
        - name: salt-play-test.xxx.ca
```

state module: cloudtest.py
```
def get_instance(name):
    return {'name': name, 'result': False, 'comment': '', 'changes': __salt__['cloud.get_instance'](name)}
```

salt-call state.apply test
```
t1: works
t2: fails
t3: works
t4: fails
```

fail looks like
```
----------
          ID: t4
    Function: cloudtest.get_instance
        Name: salt-play-test.xxxx.ca
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1753, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1709, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/cloudtest.py", line 2, in get_instance
                  return {'name': name, 'result': False, 'comment': '', 'changes': __salt__['cloud.get_instance'](name)}
                File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 176, in get_instance
                  data = action(fun='show_instance', names=[name], provider=provider)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 237, in action
                  info = client.action(fun, cloudmap, names, provider, instance, kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 482, in action
                  return mapper.do_action(names, kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1529, in do_action
                  vm_name, call='action'
                File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1719, in show_instance
                  vm_list = salt.utils.vmware.get_mors_with_properties(_get_si(), vim.VirtualMachine, vm_properties)
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 738, in get_mors_with_properties
                  local_properties=local_properties)
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 622, in get_content
                  container_ref = service_instance.content.rootFolder
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
                  return self.f(*args, **kwargs)
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
                  return self._stub.InvokeAccessor(self, info)
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
                  options=self._pcType.RetrieveOptions(maxObjects=1))
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
                  self.f(*(self.args + (obj,) + args), **kwargs)
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
                  return self._stub.InvokeMethod(self, info, args)
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1327, in InvokeMethod
                  resp = conn.getresponse()
                File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
                  response.begin()
                File "/usr/lib/python2.7/httplib.py", line 453, in begin
                  version, status, reason = self._read_status()
                File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
                  raise BadStatusLine(line)
              BadStatusLine: ''
     Started: 15:02:56.995859
    Duration: 264.907 ms
     Changes:   
----------

```

**Comment by steverweber** [comment]
```
salt --version : salt 2016.11.0-187-g8b9648c
python --version : Python 2.7.12
pip install --upgrade pyvmomi : latest
```

Well since i need this to work i created a little hack of a patch.

vi /usr/lib/python2.7/dist-packages/salt/utils/vmware.py
in function `get_service_instance`
after `service_instance = GetSi()` force the `service_instance` to `None`
```
    service_instance = GetSi()
    # HACK to ensure a new connection
    if service_instance:
        Disconnect(service_instance)
        service_instance = None
```

this will keep my happy until the cached connection issue is resolved.
Perhaps this hack fix should be pushed into the dev branch until a proper fix is found.

**Comment by steverweber** [comment]
@Ch3LL can you try the `hacky` fix to confirm it resolves the issue.
thanks.

**Comment by Ch3LL** [comment]
Okay so I am getting the Bad status line same as @steverweber but when I try your change I am now seeing a different error:

```
Traceback (most recent call last):
  File "cloud-36598.py", line 12, in <module>
    client.profile('qa-test-vm', names=['megtest2',])
  File "/home/ch3ll/git/salt/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/home/ch3ll/git/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/home/ch3ll/git/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/home/ch3ll/git/salt/salt/cloud/clouds/vmware.py", line 2347, in create
    folder_ref = datacenter_ref.vmFolder
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Datacenter:datacenter',
   privilegeId = '<id>'

```

**Comment by steverweber** [comment]
@Ch3LL 
can you run:
```
pip install --upgrade pyvmomi
```
and retest. thanks.

**Comment by steverweber** [comment]
also might want to try the latest salt dev branch and reapply the /hack/ fix and retest.

**Comment by Ch3LL** [comment]
Okay I wanted to post this in here before I forget. 

I did a git bisect and it shows this as the first commit:

```
64e9334d567814ade59aea27080253b3f831b554 is the first bad commit
commit 64e9334d567814ade59aea27080253b3f831b554
Author: Daniel Hobley <danielh@unity3d.com>
Date:   Thu Jun 2 09:20:14 2016 +0200

    Fix a bug with self signed certificates and creating a new VM
    
    - Removed the GetConnection call as all this does is cause connections that are connected with the overrides for "CERTIFICATE_VERIFY_FAILED" to not be able to connect the 2nd time the si is fetched

:040000 040000 df59d557a863a6db97c1569a697d91179b581c37 f8ae792c487a8e1eb6756f5af2b25cde366c11e9 M      salt
```

From what I could tell this was working previously and broke in 2016.3.1 

I'll try to re-apply your fix one moment.

**Comment by steverweber** [comment]
i'm using a self signed cert with the latest salt and pyvmomi without issue.

**Comment by steverweber** [comment]
opps i reread that commit message ... "2nd time the si is fetched" interesting.

**Comment by Ch3LL** [comment]
hmmm okay so i started on a clean box cuz I was having issues with my pyvmomi issue and now with your fix I'm seeing the following on develop with pyvmomi at the latest version:

```
AttributeError: 'NoneType' object has no attribute 'content'
Traceback (most recent call last):
  File "cloudtest.py", line 12, in <module>
    client.profile('qa-test-vm', names=['megtest3'])
  File "/home/vagrant/salt/salt/cloud/__init__.py", line 348, in profile
    mapper.run_profile(profile, names, vm_overrides=vm_overrides)
  File "/home/vagrant/salt/salt/cloud/__init__.py", line 1454, in run_profile
    ret[name] = self.create(vm_)
  File "/home/vagrant/salt/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/home/vagrant/salt/salt/cloud/clouds/vmware.py", line 2280, in create
    datacenter_ref = salt.utils.vmware.get_mor_by_property(_get_si(), vim.Datacenter, datacenter)
  File "/home/vagrant/salt/salt/utils/vmware.py", line 664, in get_mor_by_property
    object_list = get_mors_with_properties(service_instance, object_type, property_list=[property_name], container_ref=container_ref)
  File "/home/vagrant/salt/salt/utils/vmware.py", line 706, in get_mors_with_properties
    local_properties=local_properties)
  File "/home/vagrant/salt/salt/utils/vmware.py", line 590, in get_content
    container_ref = service_instance.content.rootFolder
AttributeError: 'NoneType' object has no attribute 'content'
```

When I re-add that line from that PR: https://github.com/saltstack/salt/pull/33698 it does work though.

And for reference heres the entire file i'm using:

```
import logging
import json
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")
from salt.cloud import CloudClient
folderToCreate='TESTDC/vm/DevDeploys03'
folderSpecstr='{"path":"'+folderToCreate+'"}'
folderSpec=json.loads(folderSpecstr)

client= CloudClient(path='/etc/salt/cloud',config_dir='/etc/salt/cloud.profiles.d')
client.action(fun='create_folder',provider='vsphere01',kwargs=folderSpec)
client.profile('qa-test-vm', names=['megtest3'])
```
and just running `sudo python cloudtest.py`

**Comment by steverweber** [comment]
note: the /hach/ fix i posted only works when using `salt-call`
```
# fails when run from master... 
salt salt-cloud\* state.apply cloudtest
                File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
                  raise BadStatusLine(line)
              BadStatusLine: ''

# success when run from client
salt-call state.apply cloudtest
```

**Comment by steverweber** [comment]
confirmed @Ch3LL workaround seems to work however at what cost..?
```
    if service_instance:
        stub = GetStub()
        if salt.utils.is_proxy() or (hasattr(stub, 'host') and stub.host != ':'.join([host, str(port)])):
            # Proxies will fork and mess up the cached service instance.
            # If this is a proxy or we are connecting to a different host
            # invalidate the service instance to avoid a potential memory leak
            # and reconnect
            ## >>> PATCH
            service_instance._GetStub().GetConnection()
            ## <<<
            Disconnect(service_instance)
            service_instance = None
        else:
            return service_instance
```

anyways it feels good to have something working. Thanks :)

**Comment by cachedout** [comment]
@steverweber I'm having a little trouble following this conversation. Is there a PR which needs to be backported to 2016.3 for this to work properly?

**Comment by steverweber** [comment]
no PR yet... no solution seems to work 100% yet. this is still a bad bug :(

**Comment by steverweber** [comment]
i'll try the latest dev code perhaps something had made it in..

**Comment by steverweber** [comment]
current dev branch seems to be working... haven't preformed much testing yet.

**Comment by gtmanfred** [comment]
@steverweber can you check if https://github.com/saltstack/salt/pull/37607 this fixed the issue for you?

**Comment by steverweber** [comment]
i did give the dev branch a try last week... it seemed to be working but then yesterday i got.
```

          ID: scinage-p01.xxxxx.ca
    Function: cloud_instance.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1754, in call                                                                                  
                  **cdata['kwargs'])                                                                                                                                       
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1708, in wrapper                                                                              
                  return f(*args, **kwargs)                                                                                                                                
                File "/var/cache/salt/minion/extmods/states/cloud_instance.py", line 56, in present                                                                        
                  sub_ret = __states__['cloud.profile'](name=name, profile=profile, **profile_overrides)                                                                   
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1708, in wrapper                                                                              
                  return f(*args, **kwargs)                                                                                                                                
                File "/usr/lib/python2.7/dist-packages/salt/states/cloud.py", line 277, in profile                                                                         
                  info = __salt__['cloud.profile'](profile, name, vm_overrides=kwargs, opts=opts)                                                                          
                File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 199, in profile_                                                                       
                  info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)                                                                               
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 345, in profile                                                                       
                  mapper.run_profile(profile, names, vm_overrides=vm_overrides)                                                                                            
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1444, in run_profile                                                                  
                  ret[name] = self.create(vm_)                                                                                                                             
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1274, in create                                                                       
                  output = self.clouds[func](vm_)                                                                                                                          
                File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2373, in create                                                                  
                  datacenter_ref = salt.utils.vmware.get_mor_by_property(_get_si(), vim.Datacenter, datacenter)                                                            
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 772, in get_mor_by_property                                                             
                  object_list = get_mors_with_properties(service_instance, object_type, property_list=[property_name], container_ref=container_ref)                        
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 817, in get_mors_with_properties                                                        
                  content = get_content(*content_args, **content_kwargs)                                                                                                   
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 682, in get_content                                                                     
                  container_ref = get_root_folder(service_instance)                                                                                                        
                File "/usr/lib/python2.7/dist-packages/salt/utils/vmware.py", line 642, in get_root_folder                                                                 
                  return service_instance.RetrieveContent().rootFolder                                                                                                     
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>                                                               
                  self.f(*(self.args + (obj,) + args), **kwargs)                                                                                                           
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod                                                          
                  return self._stub.InvokeMethod(self, info, args)                                                                                                         
                File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1323, in InvokeMethod                                                           
                  conn.request('POST', self.path, req, headers)                                                                                                            
                File "/usr/lib/python2.7/httplib.py", line 1057, in request                                                                                                
                  self._send_request(method, url, body, headers)                                                                                                           
                File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request                                                                                          
                  self.endheaders(body)                                                                                                                                    
                File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders                                                                                             
                  self._send_output(message_body)                                                                                                                          
                File "/usr/lib/python2.7/httplib.py", line 897, in _send_output                                                                                            
                  self.send(msg)                                                                                                                                           
                File "/usr/lib/python2.7/httplib.py", line 873, in send                                                                                                    
                  self.sock.sendall(data)                                                                                                                                  
                File "/usr/lib/python2.7/ssl.py", line 743, in sendall                                                                                                     
                  v = self.send(data[count:])                                                                                                                              
                File "/usr/lib/python2.7/ssl.py", line 709, in send                                                                                                        
                  v = self._sslobj.write(data)                                                                                                                             
              error: [Errno 32] Broken pipe                                                                                                                                
     Started: 16:07:02.832844
    Duration: 1793.561 ms
     Changes:   

root@salt-cloud-p01:~/mfcfinventory# salt --version
salt 2016.11.0-603-g4dd22f5 (Carbon)
```
im swamped with work.. not much time for testing this out.

**Comment by gtmanfred** [comment]
When you get a minute, can you try https://github.com/saltstack/salt/pull/38813 ?

thanks,
Daniel

**Comment by steverweber** [comment]
using salt develop branch seems to have improved but hit a new bug
```
                File "/usr/lib/python2.7/dist-packages/salt/modules/cloud.py", line 199, in profile_
                  info = client.profile(profile, names, vm_overrides=vm_overrides, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 345, in profile
                  mapper.run_profile(profile, names, vm_overrides=vm_overrides)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1444, in run_profile
                  ret[name] = self.create(vm_)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1274, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 2682, in create
                  ip = _wait_for_ip(new_vm_ref, wait_for_ip_timeout)
                File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 917, in _wait_for_ip
                  if len(resolved_ips) > 0:
              TypeError: object of type 'NoneType' has no len()
     Started: 11:27:37.448715
```

after changing that line to":
```
if resolved_ips != None and len(resolved_ips) > 0:
```

we seem to be good.

**Comment by gtmanfred** [comment]
I have fixed this in https://github.com/saltstack/salt/pull/38882

Thanks,
Daniel

**Comment by gtmanfred** [comment]
I am going to close this issue since the original issue has been fixed.

Thanks!
Daniel

**Comment by steverweber** [comment]
think this issue should be closed.

**Comment by steverweber** [comment]
lol we keep stomping on each other :)
