### ISSUE TITLE
[BUG] Upgrade to 3004+ds-1 breaks beacons, fills logs

### ISSUE THREAD

**Issue by bensteinberg** [saltstack/salt#61135]
**Description**
After upgrade from 3003.3+ds-1 to 3004+ds-1, beacons stopped working, and /var/log/salt/minion filled up with an entry like this every second (matched by the same entry in /var/log/syslog):
```
2021-10-25 21:09:11,439 [salt.minion      :2955][CRITICAL][1036] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2953, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 517, in process_beacons
    b_conf, self.opts["grains"]
  File "/usr/lib/python3/dist-packages/salt/beacons/__init__.py", line 118, in process
    valid, vcomment = self.beacons[validate_str](b_config[mod])
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/beacons/btmp.py", line 205, in validate
    config = salt.utils.beacons.list_to_dict(config)
AttributeError: module 'salt.utils' has no attribute 'beacons'
```

**Setup**

All minions in question included in their pillars
```
beacons:
  btmp: []
  wtmp: []
```
Minions concerned included 
- [x] on-prem machines, including x86_64 and armv7l
- [x] VMs running on-prem (KVM/QEMU/libvirt)
- [x] VMs running on a cloud service: Digital Ocean droplets
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Expected behavior**
Prior to the upgrade, successful and failed logins to the minions in question would trigger a beacon, which would then be handled by a reactor for notification.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
$ salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: 0.4.4
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
1. I still haven't pinned this down, but as I was trying to address this, the system did not always respond as I was expecting to various combinations of removing beacons, refreshing pillar, clearing cache, and restarting the minion service. 

2. Has the format for the `wtmp` and `btmp` beacons changed? Although it's what's in the docs, e.g. at https://docs.saltproject.io/en/latest/ref/beacons/all/salt.beacons.wtmp.html, and it's been my practice in the pillar, I can't add an empty list on the command line:
```
sudo salt 'minion1' beacons.add wtmp "[]"
minion1:
    Passed invalid arguments to beacons.add: 'NoneType' object is not subscriptable
    
        Add a beacon on the minion
    
        :param name:            Name of the beacon to configure
        :param beacon_data:     Dictionary or list containing configuration for beacon.
        :return:                Boolean and status message on success or failure of add.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' beacons.add ps "[{'processes': {'salt-master': 'stopped', 'apache2': 'stopped'}}]"
```

3. Finally, I have the sense that this changelog element may be implicated:

> Move the commonly used code that converts a list to a dictionary into salt.utils.beacons. Fixing inotify beacon close function to ensure the configuration is converted from the provided list format into a dictionary. (#60241)

**Comment by ymasson** [comment]
Hello @waynew 
Is a 3004.x release planned soon ?

**Comment by waynew** [comment]
@ymasson We don't currently have a 3004.1 release planned, but this will definitely be available in 3005
