### PR TITLE
Pass full_return to saltutil.runner

### LINKED ISSUE #38000: 2016.11.0: saltutil.runner returns a different dict structure and breaks template rendering
### Description of Issue/Question
saltutil.runner is now returning a different dict structure to older Salt versions, which caused the majority of my reactors to break.

### Setup
On 2016.3.4 my reactors were working by calling the following function:
<pre>{% set my_variable = salt['saltutil.runner']('pillar.show_pillar', minion='minion')['pillar-key'] %}</pre>

After upgrade to 2016.11.0 I got the following error when reactors were being rendered:
<pre>SaltRenderError: Jinja variable 'dict object' has no attribute 'pillar-key'</pre>

To access the pillar data successfully I had to include the 'return' key for the dict:
<pre>{% set my_variable = salt['saltutil.runner']('pillar.show_pillar', minion='minion')['return']['pillar-key'] %}</pre>

I've had a look through the release notes and I don't think anything like this is documented.

### Steps to Reproduce Issue
Attempt to read pillar data from a Jinja2 based reactor with:
<pre>salt['saltutil.runner']('pillar.show_pillar', minion='minion')['pillar-key']</pre>

### Versions Report
<pre>Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.6 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6</pre>

### PR DESCRIPTION
**Pull request by terminalmage**
This preserves the traditional return data structure for normal usage
while allowing for the full return in orchestration.

Resolves #38000.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!
