### ISSUE TITLE
2014.7.5 Won't Change Windows minion's IP Address

### ISSUE THREAD

**Issue by sdm24** [saltstack/salt#23415]
This is my first time posting here, so please forgive me if I don't include something I should.

Whenever I try to change the IP address of my Windows minion running v2014.7.5, I get this error:
```python 
 The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1020, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_ip.py", line 262, in set_static_ip
        if not salt.utils.validate.net.ipv4_addr(addr):
      File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 67, in ipv4_addr
        return __ip_addr(addr, socket.AF_INET)
      File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 46, in __ip_addr
        socket.inet_pton(address_family, ip)
    AttributeError: 'module' object has no attribute 'inet_pton'
```
I can recreate this error when I try to change the IP via network.managed in a state, or ip.set_static_ip in the command line, and both using salt-call and salt 'WindowsMinion'. 

The expected outcome should be that the IP address is set to static and will get changed to the value I input. I can successfully change the IP to DCHP via states and modules. On IRC chat, I was told that restarting WMI would fix the issue, but after restarting WMI (and also the whole machine), the issue was still there.

Both of these methods worked with minions on v2014.7.2, and rolling my windows minion back to v2014.7.2 removed the error and the IP address is changed. I have tried across multiple Windows OSes (Server 2012 R2, Server 2008, and Windows 7) and none of them work with v2014.7.5. I am using Virtual Machines created with vSphere as my minions and using the v2014.7.5 installer from http://docs.saltstack.com/en/latest/topics/installation/windows.html
```yaml
salt master --versions-report:
                 Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1

C:salt\salt-minion --versions-report
          Salt: 2014.7.5
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
If you have any questions, I will try to answer them as well as I can. Thanks!

**Comment by jfindlay** [comment]
@sdm24, thanks for reporting.  It looks like the windows version of the python socket module does not have the `socket.inet_pton` function, so something else will likely need to be done on that platform.

**Comment by sdm24** [comment]
I upgraded my Windows minion to 2015.5.0 and I still get the same issue

**Comment by sdm24** [comment]
Pull #23688 fixes the issue. How can I add it to all of my windows minions? For the one test machine, I manually edited the net.py file and copied the win_inet_pton.py file.

**Comment by jfindlay** [comment]
That is one way to make it work.  You can also download 2015.5.1, which should be out in about two weeks.

**Comment by jfindlay** [comment]
@sdm24, since you've confirmed that the pull request fixed your issue, I'm going to close this.  Please comment here if it has not been resolved and we'll reopen it.
