### ISSUE TITLE
salt can't find local cache return file

### ISSUE THREAD

**Issue by anlutro** [saltstack/salt#30204]
I'm running salt-ssh from a virtualenv locally. I git pulled the latest 2015.8 HEAD right now and am getting these errors:

```
$ salt-ssh odin test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory: '/home/andreas/salt/personal/.cache/jobs/a2/8a0f7d25aa5f22c9004ed82db41682/odin/return.p'
Traceback (most recent call last):
  File "/home/andreas/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/andreas/dev/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/home/andreas/dev/salt/salt/scripts.py", line 381, in salt_ssh
    client.run()
  File "/home/andreas/dev/salt/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/home/andreas/dev/salt/salt/client/ssh/__init__.py", line 548, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/home/andreas/dev/salt/salt/client/ssh/__init__.py", line 493, in cache_job
    'fun': fun})
  File "/home/andreas/dev/salt/salt/returners/local_cache.py", line 161, in returner
    os.path.join(hn_dir, RETURN_P), 'w+b'
  File "/home/andreas/dev/salt/salt/payload.py", line 224, in dump
    fn_.close()
  File "/home/andreas/dev/salt/salt/utils/atomicfile.py", line 121, in close
    shutil.copymode(self._filename, self._tmp_filename)
  File "/usr/lib/python2.7/shutil.py", line 89, in copymode
    st = os.stat(src)
OSError: [Errno 2] No such file or directory: '/home/andreas/salt/personal/.cache/jobs/a2/8a0f7d25aa5f22c9004ed82db41682/odin/return.p'
Traceback (most recent call last):
  File "/home/andreas/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/andreas/dev/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/home/andreas/dev/salt/salt/scripts.py", line 381, in salt_ssh
    client.run()
  File "/home/andreas/dev/salt/salt/cli/ssh.py", line 21, in run
    ssh.run()
  File "/home/andreas/dev/salt/salt/client/ssh/__init__.py", line 548, in run
    self.cache_job(jid, host, ret[host], fun)
  File "/home/andreas/dev/salt/salt/client/ssh/__init__.py", line 493, in cache_job
    'fun': fun})
  File "/home/andreas/dev/salt/salt/returners/local_cache.py", line 161, in returner
    os.path.join(hn_dir, RETURN_P), 'w+b'
  File "/home/andreas/dev/salt/salt/payload.py", line 224, in dump
    fn_.close()
  File "/home/andreas/dev/salt/salt/utils/atomicfile.py", line 121, in close
    shutil.copymode(self._filename, self._tmp_filename)
  File "/usr/lib/python2.7/shutil.py", line 89, in copymode
    st = os.stat(src)
OSError: [Errno 2] No such file or directory: '/home/andreas/salt/personal/.cache/jobs/a2/8a0f7d25aa5f22c9004ed82db41682/odin/return.p
```

**Comment by anlutro** [comment]
I tried using `git bisect` to localize the error, but I got another error in the progress:

```
Traceback (most recent call last):
  File "/home/andreas/bin/salt-ssh", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/andreas/dev/salt/scripts/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/home/andreas/dev/salt/salt/scripts.py", line 267, in salt_ssh
    import salt.cli.ssh
  File "/home/andreas/dev/salt/salt/cli/ssh.py", line 5, in <module>
    import salt.client.ssh
  File "/home/andreas/dev/salt/salt/client/__init__.py", line 34, in <module>
    import salt.config
  File "/home/andreas/dev/salt/salt/config/__init__.py", line 821, in <module>
    
AttributeError: 'module' object has no attribute 'SPM_FORMULA_PATH
```

**Comment by jfindlay** [comment]
@anlutro, thanks for the report.  I can reproduce the first issue but not the second.  Will you open another issue for that?

**Comment by cachedout** [comment]
The second is stale *.pyc files.

**Comment by cachedout** [comment]
Offending commit is here: 79daa25a159bdf2ce1d2405d7c36d9225773a605

**Comment by cachedout** [comment]
This is now fixed. Closing.
