### PR TITLE
Fix issue with redismod.hmset method

### PR DESCRIPTION
**Pull request by discogestalt**
redis.StrictRedis.hmset expects a dict as its second arg, not a series of keyword args.

hmset(self, name, mapping) method of redis.client.StrictRedis instance
    Set key to value within hash ``name`` for each corresponding
    key and value from the ``mapping`` dict.

### What does this PR do?

Fixes the call to redis.StrictRedis.hmset in the redismod.hmset method

### What issues does this PR fix or reference?

N/A

### Previous Behavior

Calling the redismod.hmset method either from the command line or a state/orchestration would return an invalid arguments error because the `fieldsvars` dict would be unpacked and passed as individual args:

`Passed invalid arguments: hmset() got an unexpected keyword argument 'test1'.`

### New Behavior

`fieldsvars` dict is passed as a dict, method runs successfully.

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

File: salt/modules/redismod.py [hunk 1]
```diff
@@ -395,7 +395,14 @@ def hmset(key, **fieldsvals):
     database = fieldsvals.pop('db', None)
     password = fieldsvals.pop('password', None)
     server = _connect(host, port, database, password)
-    return server.hmset(key, fieldsvals)
+    # orchestration passes several private key/var pairs in that we don't want
+    # to set in redis.
+    redispairs = {}
+    for field, value in fieldsvals.iteritems():
+        if not field.startswith('__'):
+            redispairs[field] = value
```
Comment (gtmanfred) [inline salt/modules/redismod.py]: You don't need to do this, use `salt.utils.args.clean_kwargs`

```
return server.hmset(key, __utils__['args.clean_kwargs'](**fieldvals))
```

**Review by gtmanfred — CHANGES_REQUESTED** [review]

File: salt/modules/redismod.py (hunk 1 above)
Comment (discogestalt) [reply salt/modules/redismod.py]: That works in 2018.3, but I'm working from 2017.7 and `salt.utils.args.clean_kwargs` isn't available there...

Comment (gtmanfred) [reply salt/modules/redismod.py]: it will be in `salt.utils.clean_kwargs` in 2017.7, so you cannot use the __utils__ syntax, but you should still use this builtin.

Comment (discogestalt) [reply salt/modules/redismod.py]: Excellent, updating now.

**Review by gtmanfred — APPROVED** [review]

**Review by mirceaulinic — APPROVED** [review]

**Comment by rallytime** [comment]
re-run all

**Comment by rallytime** [comment]
Thank you for contributing @discogestalt and welcome!
